(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.SwingFling = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{reset:2});
  var self = this;
  this.frame1 = function(){
    //loadMovie("/flash/GameController.swf", "GameEndClip");
    this.GameWon = false;  
  }
  this.frame2 = function(){
    this.stop ();
    if(!this.hasEventListener("tick"))
    this.on("tick", function ()
    {
      self.camera.x = Math.round(250 - self.camera.charX);
    });
    this.camera.starLine.x = this.camera.starLine.x - this.starPoints.currentFrame * 200;  
    this.camera.init()
  }
  this.frame35 = function(){this.gotoAndStop(1)}
	// Layer 5
	this.starPoints = new lib.sprite64();
	this.starPoints.setTransform(28.1,26);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.starPoints}]}).wait(35));

	// Layer 4
	this.instance = new lib.sprite62();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).wait(35));

	// Layer 3
	this.instance_1 = new lib.shape61("synched",0);
	this.instance_1.setTransform(433.7,44.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).wait(35));

	// Layer 2
	this.camera = new lib.sprite8();

	this.timeline.addTween(cjs.Tween.get(this.camera).to({_off:true},34).wait(1));

	// Layer 1
	this.instance_2 = new lib.shape7("synched",0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).wait(35));
  this.timeline.addTween(cjs.Tween.get(this).call(this.frame1).wait(1).call(this.frame2).wait(33).call(this.frame35))
}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2156.9,-90.9,2836.2,590.9);


// symbols:
(lib.image60 = function() {
	this.initialize(img.image60);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,90,15);


(lib.sprite69 = function() {
	this.initialize();

}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


(lib.sprite57 = function() {
	this.initialize();

	// Layer 1
	this.scoreFld = new cjs.Text("0", "30px Arial", "#37414D");
	this.scoreFld.lineHeight = 30;
	this.scoreFld.lineWidth = 96;
	this.scoreFld.setTransform(-45.3,-19.4);

	this.addChild(this.scoreFld);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-45.3,-19.4,99.9,38.9);


(lib.sprite24 = function() {
	this.initialize();

}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


(lib.shape67 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(0,0,0,0.2)").ss(4,1,0,3).p("AC7ghIhVBDQgGAFgDAJQgDAKACAIIAcBpQACAIgEADIgKgCIhcg8QgGgEgKAAIgPAEIhcA8IgKACQgEgDACgIIAdhpQACgIgDgKQgDgJgHgFIhVhDQgGgFABgEQACgEAIgBIBtgGQAIAAAIgGQAIgGADgHIAnhmQADgIADAAQAEAAADAIIAnBmQADAHAIAGQAIAGAIAAIBtAGQAIABACAEQABAEgGAFg");
	this.shape.setTransform(0,1.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.2,-17,38.5,36.6);


(lib.shape63 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#4E84DC").ss(2,0,0,3).p("EAnEAaQMhOHAAAMAAAg0fMBOHAAAg");
	this.shape.setTransform(250,168);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,500,336);


(lib.shape61 = function() {
	this.initialize();

	// Layer 1
	this.shape = new lib.image60(); 
	this.shape.setTransform(-45, -7.5); 

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-44.9,-7.4,90,15);


(lib.shape56 = function() {
	this.initialize();

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#476501").ss(1,0,0,3).p("A96gTQAQhYBMhDQBhhVCIAAQCHAABfBTQBXg/BxAAQBsAABVA5QAZhhBMhMQBzhyChAAQCiAAByByQBCBCAcBTQCRhdDMAAQDOAACTBeQBAApAkAxIAlgEQBaAABBBNQAZAdAPAgQBfg/CCgEQAFh3B7hUQCBhYC3AAQC2AACABYQBnBGAVBcQAGAYAAAaQAAB7iCBYQiABYi2AAIhCgDQgTBNhRA7QhqBNiUAAQiWAAhphNQgegWgWgYQg6A1hLAAQhcAAhAhNQgTgWgOgaQiCBBirAAQjOAAiSheQgvgegggiIgMANQhyBziiAAQiIAAhnhSQgZBHg6A6QhnBniRAAQiRAAhmhnQgdgdgVggQg9AYhIAAQiIAAhhhVQhhhVAAh4QAAgaAFgXg");
	this.shape.setTransform(249.1,-11.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#608701").s().p("AMlDLQgegWgWgZQg6A1hLAAQhbABhBhNQgTgXgNgZQiDBBisgBQjMAAiTheQgugdghggIgMALQhyByiiAAQiIABhnhSQgZBHg6A6QhmBmiRABQiSgBhmhmQgdgdgUggQg+AYhIgBQiIAAhhhUQhghUgBh4QAAgaAFgYQARBZBLBDQBhBSCIAAQBIABA+gYQAUAgAdAdQBmBmCSABQCRgBBmhmQA6g6AZhFQBnBPCIABQCigBByhwIAMgNQAhAiAuAeQCTBbDMAAQCsAACDg+QANAYATAWQBBBNBbAAQBLgBA6g1QAWAZAeAWQBpBMCWABQCVgBBphMQBRg7AThMIBBADQC3AACBhXQBmhGAVhcQAFAXAAAaQAAB9iABYQiBBVi3ABIhBgEQgTBOhRA7QhpBNiVAAQiWAAhphNg");
	this.shape_1.setTransform(249.1,7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#669900").s().p("AMmFXQgfgWgWgZQg5A1hMABQhbAAhAhNQgUgWgNgaQiDBAirAAQjNAAiThdQgugegggiIgNANQhxByiiABQiIgBhohRQgZBHg5A6QhnBmiRABQiRgBhmhmQgegdgUggQg9AYhIgBQiIAAhhhUQhMhDgRhZQARhWBMhDQBhhUCIAAQCHgBBfBTQBXg+BxgBQBsAABVA5QAZhgBMhNQByhxCigBQCiABBxBxQBDBCAcBTQCRhdDLAAQDPAACSBeQBBApAkAxIAkgEQBbAABABLQAZAdAQAiQBehBCDgEQAEh1B7hUQCChXC2AAQC2AACBBXQBmBGAVBdQgVBahmBGQiBBXi2AAIhCgDQgSBOhSA7QhpBMiVABQiVgBhphMg");
	this.shape_2.setTransform(249.1,-16.9);

	// Layer 3
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#303030").ss(1,0,0,3).p("AA+ioQAcACAYAKIgYgEQhHgGg1AtQg3AugGBGQgGBFAvA2QAdAhAkAQQg3gMgnguQgug1AGhFQAGhGA3guQA3gtBFAGg");
	this.shape_3.setTransform(231.9,60.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#37414D").s().p("AhNBvQgug2AFhFQAGhGA3guQA3gtBFAGQAcADAZAJIgYgDQhHgGg1AtQg4AugGBGQgFBFAuA1QAdAiAlAPQg3gMgngtg");
	this.shape_4.setTransform(231.3,60.3);

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#303030").ss(1,0,0,3).p("ABoikIg1gFQhGADgwA0QgxA0ADBFQAEBHA1AvQAtAoA3AEQgogKgfgdQg1gvgDhHQgEhFAxg0QAvg0BHgEg");
	this.shape_5.setTransform(245.7,65.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#37414D").s().p("AgzB+Qg1gwgEhHQgDhEAxg0QAwg0BGgEIA1AFIgYAAQhHADgvA0QgxA1AEBEQADBHA1AvQAfAeAoAKQg3gFgtgng");
	this.shape_6.setTransform(245.2,65);

	// Layer 1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#5C3701").ss(1,0,0,3).p("AE/ATIAGgTQBLjXA/ktIjWgiQABFLhkDHIgLAUQhSCUiNBFQg2gag0gCIgVAAIgGgFQhGgzhWgFQg1gDgoAWACtFPQBNh8BFjAAnSGwIAfAWQBIAtBPAHQAvAaBIAOQBiATA0glQBSgrBLhpIAfgt");
	this.shape_7.setTransform(265.6,27.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#875101").s().p("AiCIiQhJgOgugbQhQgHhIgsIgegWQgbgYgSgdQgNgVgIgYQHTDlDtjlIgeAtQhMBphUArQggAZg3AAQgcAAgggGgAC5gUQBkjHgClMIDXAjQg/EthLDXIgHATQhChKhmAjg");
	this.shape_8.setTransform(262.2,27.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#996600").s().p("AmjB+IgDgKQgYhTAxg5QATgWAZgNQAngWA1ADQBWAEBGAzIAHAFIAUAAQA0ADA0AYQCPhDBSiVIAMgVQBmgjBCBMQhEC+hOB7Qh3ByivAAQiwAAjqhyg");
	this.shape_9.setTransform(254.4,48.3);

	this.addChild(this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(57.1,-58.9,384,141.8);


(lib.shape55 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAUAjQgGAAgDgLQgCgKADgOQAEgOAHgLQAIgKAGABQAGAAADAJQACAMgDAOQgDAOgHAKQgHAKgHAAIgBAAgAgjAhQgGgBgDgKQgDgKABgMQACgNAGgJQAFgIAHABQAFABAEAJQADALgCALQgCAOgGAIQgEAJgFAAIgCgBg");
	this.shape.setTransform(0,-81.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.7,-85.1,9.5,7.1);


(lib.shape54 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("ABQllIgOADIgdAJIgaALIgLAHIgNAHIgQAKIgBABIgSALIgDABIgEADIgDADIAAABIgBAAIgDABIgXASIgFAEIgEADIgGADIgEAEIgCABIgMALIgRAPIgEAEIgXAZIgQAUIggA0IgRAkIgHAQIgCAFIgSAxQgGAWgBAYIAAAFIABABIgBABIgEgDIgNgHIgHgFIAAAAIgLgKAkqAEIgQgMIgHgHIgFgGQgRgUgTgQIAAAAIgFgEQgWgSgVgCQgIgCgGADAlrg5IABAAABuliIggAiIgaAhIgBAAIgDAFIgBACABAkZIgTAFIACgEABGkaIAbgEIAqgCIAAAAIAZACIBzAGIA3gFIA5gKIAigGIgkASIgmAYQgWANgTAQIghAhIAzAEIA4gHIA4gIIA3gJIAVgIQgOAZgVASQgXATgWAOQgYAOgZALQgZAMgaAKIgmAQIA3AMIAqAIIAMADIAJABQgPAOgXAGIgJACIguAOIg6AUIg2AQQgaAKgbAFIgQAFIgIABIgCgBIgLACIgDABIgCAAIgEAAIgBABIACAAIABAAIABAAIAeAGIAKACIApAIIgnAIIgCAAIgMACIAAAAABplpIAKACIgFAFAAaALQAQgCAZAKQAaAMAHAaIAEAMIAKgDIARgEIAFAAIAGgCAgfCsIgCghIgBgxIgCgaIgLAPIgoAnQgVARgYAOIgIAEIgTALQgdAMgeAJIg9AKIgXADIgMgBAi8E7IgEgFIgBgCQgOgXgHgWIgBgEIgFgXIgCgWQAAgHACgHQAAgIACgHAgfCsIgBAQQgBAWgGAaQgHAbgPAUQgVAagSgGQgUgHgKgTIgQgfQAOgaAYgSQAYgRAZgIgAAyEHIgBABIgFANIgEAGIgHAPIgSAeIgKATAhqFqIgCAAIgOgIIgggOIgQgIIgQgPIgBgCIgBAAABoBFIACAjQgBAWgIAZQgIAZgLAZIgUAtAoDBVIgEgSIgBgTQgBgWAHgaQAHgYASgWQAQgWAVgIQALgFAMACAnOCgQgigWgOgjIgFgSAmGC/QgfgIgbgOIgDgCIgLgHAlnDEIgfgFAkFAeIAWAHQAXAGAbgGAk7DGIgsgCAifCkQACAeAFAWIAGAe");
	this.shape.setTransform(11.8,-76.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#423A28").s().p("Ag4A8QgFgVgBgfIASgJIAIgDQAYgOATgSIApgnIALgPIABAaIACAxIABAfIgcAGQgZAHgVARQgZASgNAbg");
	this.shape_1.setTransform(2.2,-60.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CF1010").s().p("AgKBAQgUgHgKgTIgQgfQAOgYAYgSQAWgRAZgIIAcgFIgBAQQgBAWgGAaQgHAZgPAUQgRAWgNAAIgHgCg");
	this.shape_2.setTransform(2.8,-52.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F5F386").s().p("AhjFoIgGgCIgDgBIgNgHIghgPIgPgHIgQgQIgBgBIgBgBIgCgCIgXgzIgHgaQgFgUAEgPQgCgIACgGQgZAIgmACIgSABIAXgCIA9gLQAdgIAegMQgeAMgdAIIg9ALIgXACIgMAAIgBABIgsgDIgfgFIgrgRIgegOQghgVgOgkIgFgSIABgHQgFgSAFggQAJg2AognQAPgPAVABIAFAAQAVAAAdAQIAKAGIABAAIABABQATAQAQATIAGAHIAHAHIAPAMIADABIALAJIAAABIAHAEIANAIIADACIACgBIgCgBIABgEQgLgcAkhEQAAgEABgCIAIgPIgIARIgBAEIABgEIAIgRIARgjIAgg0IAQgVIAWgYIAEgEIARgPIANgLIACgBIAEgEIAFgEIAEgCIAFgFIAYgSIADgBIAAAAIABgBIADgDIAEgCIACgBIASgLIACgCIANgHIAPgKIAMgGQAmgUAQAAIAIACIAHgGQAFgDAFACQAIgIAHAGIABABIAEAFQABAEgCACIgPANQgQAQgRAUIARgVIAggiIggAiIgRAVIgKAMIAKgMIgKAMIgBABIgCAEIgBADIARgBIgTAEIACgDIgCADIATgEIAFgBIABAAQArgDATADIADgFIADgBIABAAIAZACIBzAFIA3gFIA4gJIAjgHIgkASIgmAYQgWANgTARIghAgIAyAFIA4gHIA5gIIA3gKIAVgIQgOAagWARQgWATgXAOQgXAOgZAMQgZAMgaAJIgmAQIA3ANIAqAIIAMACIAJACQgQANgWAGIgJADIguAOIg6AUIg2APQgaALgcAFIgQAEIgBgBIgGACIgDAAIgLACIgCAAIgCABIgEgBIAAABIgBAAIABAAIABAAIACAAIAFAAIAAgBQARAAAIAIIgegHIAeAHIAEAHIAGADQADAEgDADIgMACIAAAAIgBAAIgCAAIAAAAIgEACIgGABIgMgBIgGAAIAAAAIABAFQAGAngWA8QgSAzgVAdIATgsQAMgZAHgZQAJgaABgVIgDgkIAKgCIgKACIgDgLQgHgbgbgLIgBgBIgFgCQgPgFgMgBIgDAAIAAAAIgEAAIAEAAIAAAAIADAAQAMABAPAFIAFACIABABQAbALAHAbIADALIADAkQgBAVgJAaQgHAZgMAZIgTAsIgCAFQgCAHgFAGIAAABIgDAFIgCAHIgEAGIgHAQIgSAeIgLASQgfAbghAAQgUAAgUgJgAguBLIgoAnQgVARgYAOIgIAEIgTALQABAeAGAWIAGAeIAPAeQALAUATAHQATAGAVgaQAPgUAHgcQAGgaABgWIABgPIgCgiIgBgxIgCgZgAjcDEQABgJACgHQgCAHgBAJgAi9AgQgNADgMAAQgNAAgLgDIgXgHIAXAHQALADANAAQAMAAANgDgAiIFbIgegRIgKgFIgJgNIAQAQIAPAHIAhAPIANAHQgMgCgQgIgAi5E4gAl4C9IgNgDIAfAFgAmFC6gAnqCJQgRgRgGgRIgCgTIABgEIAFASQAOAkAhAVQgWgLgGgHgAoCBQgABoBAgACQA3gACcA1IgBABIgLABgACcA1gABwAdIABAAIAAAAgADUAFgAEKgKIgDACIgzANgAEKgKgAClkigACMkkQAJgIANAIIADACg");
	this.shape_3.setTransform(11.8,-75.8);

	// Layer 2
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#463800").ss(1,0,0,3).p("AB7DAQgzAphIAAQhHAAgzgpQgzgnAAg5QAAg4AzgoQAegWAlgKQBChIAjheQA0gwBHATQgCArgOA2IgUBTQgGAcABAXQAuAnAAA1QAAA5gzAng");
	this.shape_4.setTransform(-4.3,-22.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F5F386").s().p("Ah6DAQgzgnABg5QgBg4AzgoQAegWAlgKQBChIAjheQA0gwBHATQgCArgOA2IgUBTQgGAcAAAXQAvAngBA1QABA5gzAnQg0AphHAAQhHAAgzgpg");
	this.shape_5.setTransform(-4.3,-22.5);

	// Layer 1
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#463800").ss(1,0,0,3).p("AlIArIgSgFIgSgEAlDAsIACABIACAAIABABIADAAIABABIA0AGIATAAICOgEIBAgLIAqgJIAOgEIAGgBIACgBAA3APIgcAIAj2BPQgqAEgqgJIgggJAjKBSQgWACgWgFACsh0IAFABIABACIgHAYQgEAMgJANIgHAJIAAABIgOANIgHAGAClhBIAIgGIAagMIAbgGIAFAAIAWgBIAKADIANAHQACACgBADQACABgBAEQAHAGgDAIIAAABIgNASIgPAKIgBABIgGADQADgEADAAIABAAIAZgCIACAAIAPACIAMACIAWAKQAJAEAHAHIAMAKIgKAEQgOAHgNAFIgBAAIgRAFIgIABIgbADIgcADABRhBQAHgKAKgIIAXgQQAGgEAHgBQAHgEAHgCIAYgGABEguIALgSIACgBACJgpQABACAEgFIAJgKACXg3IAKgHIAEgDAA1AHIADgTQACgOAGgNIAEgHAAXA6QhFAWhHAHQgqAFgrgKAA6AyIgDgDIAAAAQgQAGgQAFABjBQIAaACIAbAAIAVgHAD6BcIAIAKIgMAEIgbAHIgFABIgVADIgagCIgZgGIgbgKQgMgGgFgOIABABABiBPQgMgEgMgIQgKgGgGgLAD0gWQACgBABAAADvBLIAGAIIABABIADAHIABABADcA5IgHgDIAIAGIASAPAEZAvQgLAFgKACIgbAFIgMgCIgBAAAErAhIgIAHIgGADIgEAEAEvAbIgEAG");
	this.shape_6.setTransform(43.6,-8.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#734917").s().p("AAAAAIAAAAIABABg");
	this.shape_7.setTransform(6.6,-2.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F5F386").s().p("ACYBpQgggNgKgJIAaACIAbAAIAVgHIgVAHIgbAAIgagCIgBgCIgBAAQgXgNgGgMIgDgFIgHACIgDgDIAAAAIggALIhpASIh4AGIgJAAIgEAAIAAAAIgBAAIgIAAIgWgDIgRgCIgmgGIgrgCQgUgJgEgFIAAgCQgCgEABgCIgBgBIgBgFIAHgHIASAEIASAFIADABIACAAIACAAIAAABIgCgBIACABIACAAIABABIADAAIABABIA0AGIAFABIAOgBIAnABIAYgBIBPgEIATgCIAtgJIAqgJIAOgEIAGgBIACgBIAbgFIABgDIgCgIQgEgdATgYQAFgLAIgIQASgYAjgPQAHgEAHgCIAYgGIAGADIABADQADAHgHARIgKAVIgEADIgKAHIAKgHIAEgDIgBADIgBABIACgBQAOgGAQgCQASgQASgDIAfADQALAEAEAHQAAAAABAAQAAABAAAAQAAAAAAABQAAAAAAABIAAACIAAgCQAAgBAAAAQAAgBAAAAQAAAAAAgBQgBAAAAAAIABABQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAABQAEAGgDAIQgFAOgSAJIgDABIAAAFIAAABIgGADQADgEADAAQgDAAgDAEIAGgDIgBADIAHgCIAUgEIACAAQAeABAlAZQAEAHgEAGQgOAHgNAFIgBAAIgRAFIgIABIgbADIgcADIAcgDIAbgDIAIgBIARgFIABAAQANgFAOgHIgDADQgFAFgUAJIgVAGIAEgGIgEAGIgDAAIgFAHIgGADIgEAEIgdAEIgeAFIgCABIgHgDIAIAGIASAPIAGAIIAAABIABAAIADAHIABABIgJANIgWADQgNAFgOAAQgXAAgcgLgAD/gTIADgBIgDABgAC2hWQgEAMgJANIgHAJIAAABIgOANIgHAGIAHgGIAOgNIAAgBIAHgJQAJgNAEgMIAHgYgACWgmIAAAAIAAAAIAAAAIABgBIABgBIABAAIAAAAIAAgBIAJgKIgJAKIAAABIAAAAIgBAAIgBABIgBABIAAAAIAAAAIAAAAIgBAAIgBAAIAAAAIAAAAIAAAAIAAAAIABAAIABAAgAEFBfIgBgBIgDgHIAFABIgBAHgAD6BOIAEADIACAFgAjVBVIAIAAIABAAIAAAAIAEAAIgIABgAjIBVIACAAIgCAAgAi/BVIgHAAIAHAAgAjhBUIAMABIAAAAIgMgBgAjjBUIACAAIgCAAgAjmBTIADABIgDgBgAjoBTIACAAIgCAAgAjpBTIABAAIgBAAgAjrBSIACABIgCgBgAD6BOIgSgPIgIgGIAHADIAAAAIABACIASAQgABCAyIAAAAIADADIgjAIIAggLgABFA1gAEoAuIAGgDIgFAFIgFACgAk9AugAlPApIgSgEIABgDIACAAIATAFIAOAHgAEIgXgACwg+gACehuQARgIAIAFIgYAGQgHACgHAEQAGgGAHgDgAC3hxIAAAAg");
	this.shape_8.setTransform(42.5,-9);

	this.addChild(this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-40.3,-112.8,119.8,115.8);


(lib.shape53 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("Aggg5IAtADIApACQAOgJAPgBIACAAIANACIABAAQANAFAIAIIANgPIADgCQAEgCADgBIAFAAIgBgBIADABIACAAIAGABIAGADIAGAFQAUAPgJAWIgHAMIADAKQABAHgDAFQAaAWgMAYQgMAZgaAMQgSAJgSgCIgIgBQgOgCgPgIIgIgEIgKgFQgagPgRgYIhCgPQgjgKgngRIgFgCIgDAAIgggOIgBgCAggg5QhJgGhagoACvANQgEAOgNAKQgQAMgRAAACugJQgLAPgVACAB4gvQAJAJACAP");
	this.shape.setTransform(17.9,19.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F5F386").s().p("AB5BkIgIgBQgPgCgPgIIgIgEIgJgFQgagPgSgYIhCgPIgFgDQgXgOgtgJIgGgBIgCgBIgggPIgCgCQgIgJAEgNQAJgdgrgdQBSAiBYAFIAuADIAoACQAPgJAPgBIABAAIAOACIABAAQANAFAIAIIANgPIADgCIAHgDIAEAAIAAgBIACABIACAAIAGABIAGADIAHAFQATAPgJAWIgGAMIACAMQABAFgCAFQAaAWgNAYQgMAZgaAMQgPAHgOAAIgGAAgACkAiQgRAMgRAAQARAAARgMQANgKAEgOQgEAOgNAKgACUAFQAUgCAMgPQgMAPgUACgACIgaQgCgPgIgJQAIAJACAPgAgCAmQgWgDgUgJIBCAPg");
	this.shape_1.setTransform(17.4,19.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.4,9.1,39.8,20.8);


(lib.shape51 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("AjciLIAXgfQARgWAZgXIAUgRIAbgTIAEgDIAUgMIAOgIIACgBIAFgCIAHgDIADgCIAGgEIAbgMIADgBIABABIABgBIADgDIAFgBIACgBIASgHIABgBAAulDIAOgEIAcgGIAegDIAOAAIALAAIAPACIAJADIgGAEIgmAbQgTAOgNAMIgBABIgDAEIgCACABlkJIgTABIADgDADIj5QBWAYAaAEIA2AGIA7ACIAiABIgmAKIgrAQQgYAIgVAMIgnAaQAUAKAdAEIA4AFIA4ADIA4ACIAWgEQgTAXgYAMQgaAOgZAJIg0AQIg3ALIgnAIQAYAMAaALIApAOQAFAEAGABIAIADQgSAKgXACIgJAAIgxAFIg8AIIg4AGIg4AFIgRABIgHgBIgCAAIgOgBIgCAAIgEAAIgBAAIABAAIABABIACAAIAcAMIAJAEIAnARIgogBIgCAAIgMgBIgBAAABuBVIgHAAACwkAIABAAIAXAHABrkIIAcABIApAHAhTCgIAGghIAIgwIAEgaIgOAMQgWARgaAOQgXANgbAIIgIADIgUAGIg/AJQgeACgfgDIgYgDIgLgDAkIEMIgDgFIgBgDQgJgYgCgXIgBgEIABgYIABgWQACgIAEgHQABgHADgGAjSDSQATgYAcgMQAbgNAagCIAbABIgDAPQgFAVgMAZQgLAZgTARQgaAWgRgKQgSgLgGgWgAAGAOQAQABAWAPQAYAQACAcIAAAMIALgBIARAAIAFAAABGBWQABASgFARQgGAVgNAXIgcAtIgXAkIgGAIIgJALIAAABIgIALIgFAGIgKANIgYAbIgOAQAjBFLIgCgBIgMgKIgdgVIgOgKIgNgSIgBgCIAAgBAmfikIAMABQARAFAQATQADABADADIAEAEAlpiDIABAAIAAABQAPAUANAWIAEAHIAFAIIAMARAk1g2IAKALIAAABIAGAGIALAKIADACQALAIAKAEQAUAKAcAAAkVgeQAGgZAKgVIAcgtIACgDIALgPAoagTIgBgTIADgTQAEgWALgYQAMgYAWgTQAUgRAXgEIAVACAnbBSQgIgEgGgFIgDgCIgKgJQgdgcgGgjIgBgSAkXgYIABAAIAAgCIABgEAltCBQgXgEgUgHAjNB+IgFA1IAAAf");
	this.shape.setTransform(20.4,-69.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#423A28").s().p("AhHAvIAFgzIAUgGIAIgDQAbgIAVgNQAagOAWgRIAOgMIgEAaIgIAwIgGAfIgbgBQgaACgZANQgcAMgTAYg");
	this.shape_1.setTransform(6.5,-56.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CF1010").s().p("AgcA4QgSgLgGgWIgKgeQATgYAcgMQAZgNAagCIAbABIgEAPQgEAVgMAXQgLAZgUARQgPAPgOAAQgGAAgFgDg");
	this.shape_2.setTransform(5.7,-47.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F5F386").s().p("Ai2FIIgGgDIgCgCIgMgJIgdgVIgOgKIgNgTIgBgCIAAAAIAAgDQgHgUgGgiIgCgbQgBgWAIgOQgCgIAEgFQgbAEgmgFIgSgEIAYADIABABQASABARAAIABAAIAAAAIAUAAIAEgBIA/gIIg/AIIgEABIgUAAIAAAAIgBAAQgRAAgSgBIgBgBIgYgDIgLgCIgBAAQgXgEgUgHIgRgGIgMgFQgOgIgYgRIgbgUQgdgbgGgkIgBgSIACgHQgCgTAMgfQAVg1AugdQARgLATAFIAIAAQAUAFAZAUIAJAJIABAAIAAAAQAPAUANAWIAEAIIAFAIIAMARIACACIAKALIAAAAIAGAGIALAKIADADQALAHAKAFIABABIABAAQATAIAYAAIABAAIAAAAIABAAIABAAIgBAAIgBAAIAAAAIgBAAQgYAAgTgIIgBAAIgBgBQgKgFgLgHIABgBIAAgBIABgEQgEgfAwg8IACgEIALgPIAXgfQARgVAZgYIAUgQIAbgTIAEgEIAUgLIAOgIIACgBIAFgDIAHgDIADgBIAGgEIAbgMIADgBIABAAIABgBIADgCIAFgCIACAAIASgHIABgBIAPgGIADgBIAOgFIAOgDQApgMARADIAGADIAIgEQASgHAIAJIAAABIADAGIgmAbQgTAPgNAMIgBABIgDAEIgCACIAQACIgTAAIADgCIgDACIATAAIAGAAQArAGATAHIAEgEIADgBIABAAQAKgFALAJIACADQBWAYAaAEIA2AHIA7ABIAiABIgmAKIgrAQQgYAJgVAMIgnAZQAUALAdAEIA4AEIA4ADIA4ACIAWgEQgTAXgYAMQgaAPgZAJIg0AQIg3AKIgnAIQAYAMAaALIApAOQAFAEAGABIAIAEQgSAKgXABIgJABIgxAEIg8AIIg4AHIg4AEIgRABIAAgBIgHABIgCgBIgOAAIgCAAIgEgCIAAABIAAABIgBgBIABAAIgBAAIABABIABAAIACABIAEAAIABAAIgCgBIAOAAIgMABQAQACAHAKIACAHIAGAFQABAEgDADIgMgBIgBAAIAAAAIgCAAIAAgBIgFACIgFAAIgMgDIgFgCIAAABIAAAEIgLAAIAAgLQgCgcgYgRQgWgOgQgCQAQACAWAOQAYARACAcIAAALIAAAEQAAAQgEAPQgGAVgNAYIgcAtIgYAjQgGAMgIAIIAAABIgFAEIgDAHIgFAFIgKAOIgYAaIgOAQQgbAPgaAAQgcAAgagTgAhKA7QgWARgaAOQgXAMgbAJIgIACIgUAHIgFA1IAAAeIAKAhQAGAVASALQARAKAagWQATgRALgZQAMgYAFgWIADgPIAGghIAIgwIAEgZgAkLCOQABgIADgGQgDAGgBAIgAB6A8IgcgMgADNkAIgXgHgAjXE0IgcgXIgIgHIgHgOIANATIAOAKIAdAVIAMAJQgMgFgNgKgAkCEIgAAYDMIAcgtQANgYAGgVQAEgPAAgQIAAgEIALAAQgDAnghA3QgaArgYAXgAB0BOIAMABIgBABIgEABQgDAAgEgDgABWBPIAAAAgAB0BOgAoKAgQgNgVgBgPQgCgKADgJIACgDIABASQAGAkAdAbQgTgPgGgIgABhAvgABbAvgADBArgAD5AkIgEACIg0AFgAD5AkgAoVgagAjiiFIALgNIgLAPIgCAEQAAgEACgCgAjXiSgABgkYIAAAAgACAkzIAmgbIgCAGIgRAKQgYAQgbAWQANgMATgPgACmlOg");
	this.shape_3.setTransform(19.9,-68.7);

	// Layer 2
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#463800").ss(1,0,0,3).p("ACuBgQAAA5gzAnQgzAphIAAQhHAAgzgpQgzgnAAg5QAAg4AzgoQAegWAlgKQBChIAjheQA0gwBHATQgCArgOA2IgUBTQgGAcABAXQAuAnAAA1g");
	this.shape_4.setTransform(-4.3,-16.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F5F386").s().p("Ah6DAQgzgnABg5QgBg4AzgoQAegWAlgKQBChIAjheQA0gwBHATQgCArgOA2IgUBTQgGAcAAAXQAvAngBA1QABA5gzAnQg0AphHAAQhHAAgzgpg");
	this.shape_5.setTransform(-4.3,-16.5);

	// Layer 1
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#463800").ss(1,0,0,3).p("AjlBvQBDgLBGgaQAdgKAfgPIAmgTIANgHIAGgDIACAAAA0AFIgZAPAj4ByIATgDACNhiIAHgIIAWgRIAZgMIAZgHIALAAIAOAFQACABAAADQACABABADQAHAFAAAIIAAABQgDALgGAJIgNAOIAAAAIAAABACIiWIAFAAIABACIgBAZIgHAbIgFALIAAABIgKAQIgFAIABniCQAEgFAGgCIAXgNACBhVIAIgJIAEgEAA6hOQAGgMAHgKIATgVQAGgGAHgDAB3hEQABACADgGIAGgMAAwAAIgCgWQgBgOADgNIADgJAA/AnIgDgCIgBgBQgNAKgQAIQg9AmhEAYQgoAOgrAAQgWAHgXAAQgnAOgrAAIgigBAlgB4IATAAIATAAAkzB5IgHgBABtA6QgNgBgOgGQgKgDgJgJABuA6IAagDQAMgCAOgFQALgFAIgGAEEAkIAKAIIgMAGIgXANIgFACIgUAIIgaAEIgagBIgcgDQgNgDgIgMAEGhZIAPgCIAMgBIAYAEIASAIIANAJIgIAHIgXARIgCABIgPAIAEmggIgGAKIgGAEIgDAEQgJAIgKAFQgLAFgOADIgLACIgCgBIgHgBQADADAGABQALACAKAJIAHAGIACABIAFAGIABABADtgQIAagKIAagJIAHgDIgCAGAEEhYIACgBADkhKQABgCABAAQACgEADAAADrhRIAZgHAkzB5IACAAIABAAIADgBIABABIA0gH");
	this.shape_6.setTransform(41.6,-11.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#734917").s().p("AAAAAIAAAAIABABg");
	this.shape_7.setTransform(6.6,3.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F5F386").s().p("Ak6CWQgWgEgEgEIgBgBQgDgEABgCIgBgBIgCgEIAEgJIATAAIATAAIADABIAEAAIAAAAIACAAIABAAIADgBIABABIA0gHIAGAAIANgDIAmgIIAXgHIBMgWIASgFIAqgUIAmgTIANgHIAGgDIACAAIAagMQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAIgEgGQgKgdANgcQACgKAEgJIABgBQANgcAggYQAEgGAFgEQAPgMAJACIgXANQgGACgEAFQAEgFAGgCIAXgNIAGACIACADQAFAGgEASIgEAXIgEAEIgIAJIAIgJIAEgEIAAADIgBABIABgBIAbgOQAOgUARgHQAPgHAQADQAMABAFAGQABAAAAAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAQABABAAAAQAAABAAAAQAAABAAAAQAEAGgBAIQgBAOgPANIgEADIACAEIAAABQgDAAgCAEIgCACIACgCQACgEADAAIgBADIAHgDQAIgFALgDIACgBQAegGApARQAGAHgDAHIgXARIgCABIgPAIIAPgIIACgBIAXgRIgCADIgWAUIgSAJIACgGIgHADIgaAJIgaAKIAagKIAagJIAHgDIgCAGIgEACIgCAIIgGAEIgDAEIgbALIgcAKIgCABIgHgBQADADAGABIALAEIAKAHIAHAGIABABIABAAIAFAAIABAHIgBgBIgFgGIAFAGIABABIgGAOQgIAGgNADQgcASgxgHQgjgFgLgHIAagDQAMgCAOgFQALgFAIgGQgIAGgLAFQgOAFgMACIgaADIgBAAIgBgBIgBAAQgZgHgIgLIgEgEIgHAEIgDgCIgBgBQgNAKgQAIQAQgIANgKIABABIADACIghAPIhhAqQhMAegnAEIgRAEIgcADIgQACIgnACQgNAJgRAAIgMgBgACXh6IgHAbIgFALIAAABIgKAQIgFAIIAFgIIAKgQIAAgBIAFgLIAHgbIABgZgACBhDIABAAIAAAAIABgBIABgBIAAgBIABAAIAAgBIAAAAIAGgMIgGAMIAAAAIAAABIgBAAIAAABIgBABIgBABIAAAAIgBAAIAAAAIAAAAIAAAAIAAAAIAAAAIAAAAIAAAAIAAAAgAEEiAQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQABAAAAABQAAAAABABQAAAAAAABQABAAAAABgAjZCKQAOAAAOgDQgOADgOAAgAisCDQgJAEgHAAIgBAAIARgEgAlDB5IgTAAIABgDIACgBIAUABIAPADgAD/AXIAEACIADAEgAD/AXIAAAAgAD/AXIgKgHIAKAHIAAAAgADqAMQgGgBgDgDIAHABIAAABIACABIALAFIgLgEgAEkgRIAGgEIgEAGIgFACgACXhhg");
	this.shape_8.setTransform(40.6,-11.5);

	this.addChild(this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-33.8,-103.5,110,110.4);


(lib.shape49 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("AjLi3IAdgaIAygjIAXgNIAegNIAFgDIAWgHIAPgFIACgBIAFgCIAHgBIAFgBIAGgCIAbgHIADAAIABAAIAAgBIAEgBIAFgBIACAAIAVgDIACgBIATgDIAOgBIAPgBIAcgBIAeADIAPADADOksIAJAFIgHADIgrATQgUAKgQAKIgCAAIgEADIgCACACJjyIgTgDIADgDADnjQQBQAoAYAKIA1AQIA4AOIAiAHIgoADIgtAHIgwALIgsASQASAOAbAJQAbAKAcAGIA2AOIA3ANIAXAAQgXARgbAIQgcAIgaAEIg3AFQgbACgcgCIgpAAQAVARAYAQIAkAXIALAHIAHAFIgrADIgIgBIgygFIg8gDIg5gFIg3gHIgQgCIgHgDIgCAAIgMgCIgCgBIgCgBIgEgBIgBAAIABABIABAAIABABIAaARIAIAGIAjAYIgngJIgCAAIgMgDIAAAAADRjcIAAABIAWALACOjxIAbAHIAoAOAjfijIAHgHIANgNAkYhWQALgYAOgTIAggiAkbhRIARAQQATAOAbAFAh/CKIALggIATgtIAIgZIgQAKQgZAMgcAIQgZAIgcADIgJABIgVADIg/gEQgegEgegJIgXgIIgKgFAmOA0QgWgJgSgKAnQAQQgagRgUgYIgBgDIgIgLQgXghABglIACgTIAEgSIAGgSQAIgVAQgVQARgVAYgOQAPgJAQABAmNj4QgKgGgLAAQgIAAgHAFAh/CKIgGAOQgKAUgQAWQgQAWgWAMQgeARgOgNQgQgOgCgWIgCgjQAXgSAdgHIA3gEgAjxBRQgKAcgFAXIgFAdABMBmIgGAAAgJAMQANAFATATQAUAVgEAbIgBAMIAKABIARADIAFACAAmBgIgMAhQgJAUgRAUIgjAmIgnAkAhWD9IAAABIgKAKIgGAEIgMAMIgdAVIgRANAkNEcIgCgBIgJgMIgZgaIgMgNIgJgVIAAgCIAAAAIgCgGIgBgDQgDgaACgXIAAgEIAFgXIAGgWQADgIAFgGQADgGAEgFAlXjKIABAAIAAABQALAWAIAYIADAJIADAIIAJAUAkzh0IAIANIAAAAIAEAHIAJAMIADADIABAAIgBgCIADgDAmFj2QAGAAAGAEQAPAIAMAWQADACACADIADAF");
	this.shape.setTransform(28.4,-73.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#423A28").s().p("AhPAgQAEgWALgbIAVgCIAIgBQAcgDAYgIQAbgIAZgMIARgKIgJAYIgSAsIgLAgIgcgHIg1AFQgdAHgXASg");
	this.shape_1.setTransform(10.7,-63.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CF1010").s().p("AguAvQgPgOgCgWIgDghQAXgSAdgHIA1gEIAcAGIgHAOQgJAUgQAUQgRAWgUAMQgRAJgLAAQgJAAgHgFg");
	this.shape_2.setTransform(8.8,-54.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F5F386").s().p("AkBEdIgEgFIgDgBIgJgMIgYgaIgMgNIgJgUIAAgCIgBgBIAAgDQgDgVABgiIADgbQAEgXALgMQAAgHAEgEQgZgCgggMQAdAJAfAEIA/AEIg/gEQgfgEgdgJIgXgHIgLgFIgBABQgVgJgTgLIgPgJIgLgIIgggeIgXgYQgWgfAAgjIABgFIACgSIAEgHQACgSARgcQAfgwAzgVQASgHASAJIAIACQATAIAVAaIAHAJIABABIAAAAQALAWAHAZIADAIIADAJIAJATIACACIAIANIgBABIAEAGIAKAMIACAEIASAPQASAPAcAEQgcgEgSgPIgSgPIABgBIAAgBIACgEQACgeA3guQADgGAEgEIAOgKIgOAMIgHAIIAHgIIAOgMIAcgaIAzgkIAWgMIAegOIAFgCIAWgIIAPgFIADAAIAFgCIAGgCIAFAAIAFgDIAcgGIADgBIABABIABgBIAEgBIAFgBIACAAIAVgDIACgBIAPgCIASgDIAOgBIA7ADIAFAFIAJgDQAGgBAEAEQAKgEAFAIIAAABIACAHIgrATQgVAKgQAKIgBAAIgEADIgCACIAQAFIgTgDIADgCIgDACIATADIAFACQAqAOAQAKIAEgDIAEAAIABAAIAVALQBQApAYAJIA1ARIA5ANIAhAIIgnACIguAIIgwALIgrARQARAOAcAKQAbAJAcAGIA2APIA3AMIAWABQgXASgaAGQgcAJgbAEIg3AFQgbABgcgCIgpABQAWAQAXAQIAlAYIAKAHIAHAFIgqADIgJgBIgxgFIg8gEIg5gFIg4gGIgQgDIAAgCIgHAAIgCgBIgLgCIgDAAIgCgBIgDgCIAAABIgCAAIACAAIgCAAIACAAIAAAAIAAABIACAAIAFACIABAAQAPAFAEALIABAIIAFAGQABAEgEACIgMgDIgBAAIAAAAIgBgBIAAAAIgGAAIgEgBIgMgGIgFgCIAAAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABABABIgLgCIACgLIAAgIQAAgXgRgSQgTgTgNgEQANAEATATQARASAAAXIAAAIIgCALIALACQgLAmgrAvQglAqggATIAngkIAjgmQARgVAKgTIALgiIgLAiQgKATgRAVIgjAmIgnAkIAAAAQgFAGgGAEIgBABIgGADIgDAHIgHAEIgMALIgcAVIgRANQgTAGgRAAQgoAAgdgfgAhiArQgZALgbAJQgaAIgcADIgIABIgVACQgLAdgEAWIgGAeIADAiQACAWAPAPQAPAMAdgQQAWgNARgWQAQgVAJgVIAHgOIALgfIASguIAJgYgAkvBVQACgHAFgFQgFAFgCAHgABeBSIgZgSgAkdEDIgWgcIgHgIIgEgPIAJAUIAMANIAYAaIAJAMgAk+DQgABVBjIAMADIgCAAIgDABQgEAAgDgEgABVBjgACnBPIA5AFIgFABgACnBPgAlqA7IgRgGIAXAHgAl7A1gAoThGQgKgXADgSQAAgJAFgIIACgDIgCASIgBAFQAAAjAWAfgADujUgADZjfQAMgDAIALIABADgACIkAIAAAAgACtkUIArgTIgDAFIgUAGQgbALgeARQAQgKAVgKgADYkng");
	this.shape_3.setTransform(27.6,-73);

	// Layer 2
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#463800").ss(1,0,0,3).p("AB7DAQgzAphIAAQhHAAgzgpQgzgnAAg5QAAg4AzgoQAegWAlgKQBChIAjheQA0gwBHATQgCArgOA2IgUBTQgGAcABAXQAuAnAAA1QAAA5gzAng");
	this.shape_4.setTransform(-4.3,-23);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F5F386").s().p("Ah6DAQgzgnABg5QgBg4AzgoQAegWAlgKQBChIAjheQA0gwBHATQgCArgOA2IgUBTQgGAcAAAXQAvAngBA1QABA5gzAnQg0AphHAAQhHAAgzgpg");
	this.shape_5.setTransform(-4.3,-23);

	// Layer 1
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#463800").ss(1,0,0,3).p("AkoCOIgHAAIgTACIgTABAjuCCIASgFQBCgSBDghQAcgNAdgSIAkgXIAMgIIAGgEIACgBIAYgOAkoCOIACAAIABAAIADgBIABAAIAzgLAjaCXQgkAQgpAFIgiADAAhAqQg5AshCAeQgmARgrAFQgWAKgZADADoijQAJAEAAAJIAAAAQgBALgGAKIgLAPIAAABIgFAFQABgEADgBIABgBIAYgJIACgBIAOgEIAMgCIAYACIAUAGIAOAIIgIAHIgVATIgBABIgPALIgCAGIgFAKIgFAFIgDAEIgRAOIgYANIgLADIgCgBIgIAAQAEADAGAAQAMACALAHIAHAFIACABIAFAEIABAAQAEADAHAEIgLAIIgWAPIgEACIgUALQgMAFgNABIgaACIgcgBQgNgBgKgMIACAAIAZgFQAMgEANgGIASgMADmimQACAAAAADACAh4IAFgJIAVgUIAXgOIAZgKIAKgBIAPAEQACABABADADYhqQABgBABgBABAAXIgDgCIgBAAIgbAVAEghMIgHADIgZAMIgZALAB7iqIACAZIgEAbIgEALIAAABIgJARIgEAIAB1isIAFAAIABACAAwheQADgMAHgJIARgYIALgKIAJgIIAWgPAAtgOIgEgVQgDgOACgOIACgIIAEgUIACgDAB1hrIAHgJIAEgEABshZIAEgEIAFgNABvAlIgbgDQgLgDgJgI");
	this.shape_6.setTransform(40.2,-20.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#734917").s().p("AAAAAIAAAAIABAAg");
	this.shape_7.setTransform(6.5,-2.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#F5F386").s().p("AksCsQgWgCgFgDIgBgBQgDgEAAgCIgBgBIgDgEIAEgJIATgBIATgCIADAAIAEAAIAAAAIACgBIABAAIADAAIABAAIAzgLIAFgBIANgFIAmgMIAWgJIBJgdIASgIQAJgEAegTIAkgYIAMgIIAGgDIACgBIAYgMQAAAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBIgFgHQgNgcAKgdQABgMAFgLQAKgcAcgbQADgGAFgEQAOgOAJACIgWAOIgJAIIAJgIIAWgOIAGABIACAZIgEAcIgEALIAAABIgJARIgEAIIAEgIIAJgRIAAgBIAEgLIAEgcIgCgZIADADQAFAFgCASIgBAYIgEAEIgHAKIAHgKIAEgEIgBADIAAABIABgBQAMgLANgGQANgVAPgIQAOgJAQABQANAAAGAFQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAgBAAgBQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAABAAABQAFAFAAAJQABAOgOAOIgDADIABAEQgDACgBAEIAFgFIAAADIAFgDIATgLIACgBIBHAEQAHAGgCAHIgVAUIgBABIgPAKIgHAEIgZALIgZAMIAZgMIAZgLIAHgEIgCAHIgDACIgCAIIgFAEIgDAEIgaAOIgaAPIgCABIgIAAQAEADAGAAIAGABIARAHIAHAGIABABIABAAIAFADIABABIgEAPQgHAHgNADQgaAVgygCQgigCgMgFIAZgGQAMgDANgHIASgMIgSAMQgNAHgMADIgZAGIgCgBIgBAAQgagFgKgJIgEgEIgGAEIgDgBIgBAAIgbAUIhdAzQhJAmgmAIIgWAHIgZAGIgNACIgmAGQgOAMgXAAIgEAAgAB6hcIgEAEIAEgEIAFgNgADihpIACgCIgCACgAjQCYQANgCAMgEQgMAEgNACgAihCLQgJAFgHABIgGABIAWgHgAlKCPIABAAIAUgCIAQACIgTACIgTABgABGAWIABAAIADABIgfATgAENABgAEMAAIgFgDIAFgBIABAFgAD+gKIAEACIADAEgAD+gKgAD+gKQgIgFgJgCQAJACAIAFgADngSQgGAAgEgDIAIAAIAAAAIACABIAGADIgGgBgAEeg3IAFgEIgDAGIgFACgAEqhMIAPgKIABgBIAVgUIgCAEIgTAWIgSAMgAFPhrgADohxIABABIgFAFQABgEADgCgADphwgACKh4g");
	this.shape_8.setTransform(39.2,-20.5);

	this.addChild(this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-26.3,-104.7,108.1,105);


(lib.shape48 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.702)").s().p("AAwAjQgEABgJgIQgJgGgIgKQgFgJgBgEQgBgGAFABQAHAAAIAGIAPAOQAGAJABAGQABAGgFAAIgBAAgAgjgRIgOgHQgEgGABgDIALgBIAQAFIANAJQAFAEgDADIgKABQgIAAgHgFg");
	this.shape.setTransform(20.1,-82.6);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(14.7,-86.2,10.7,7.1);


(lib.shape47 = function() {
	this.initialize();

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("AADg0QgqBIA5Af");
	this.shape.setTransform(22,-64.8);

	// Layer 3
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#463800").ss(1,0,0,3).p("Ai1jEIAhgVQAXgOAggOIAYgIIAggJIAFgBIAWgFIAOgCIACAAIAGgBIAHAAIAFgBIAGgBIAegCIADAAIAAAAIACAAIADgBIAdAAIABAAIAUAAIAOAAIAVACIAWADIAdAIIAOAFIAJADIAOAHIAIAHIgHABIgtAMIgUAHIgUAHIgBABIgEACIgDABQgCACgBAAIASAGIAFACIAZAMIAlAUIABAAIATAPQBJA0AXAMIAxAZIA2AWIAgAMIgogDIgtAAIgyAEIgtALQAPAQAaAMQAZANAaAKIA0AXQAbAMAZAJIAWAEQgaAPgbADIg3AEIg4gDIg2gJIgogGIAnAnIAhAdIAIAJIAHAFIgrgDIgIgDIgwgMIg7gNIg3gNQgcgFgagKIgPgFIgIgDIgBgBIgNgFIgCgBIgEgCIgBAAIABABIABAAIABABIAXAVIAHAHIAfAdQgSgFgTgKIgCAAIgBAAQAAgBAAABIgKgFIgBgBAAzCBIgEgBIgBAAIgBAAIgFgDIgRgFAiFD+IAAAAIgLAIIgHAEIgOAJIgfAQIgSALAk+EAIgCgCIgIgNIgUgeIgJgPIgGgVIAAgCIAAgBIgBgGIAAgDQAAgaAFgXIABgEIAJgWIABgCIAIgSIAJgKIAKgMQgdgJgcgOIgWgKIgJgHAmaAHIglgYIgMgLAnOgeIgIgHQgXgXgPgbIgBgDIgHgMQgRgkAHglIAFgSIAGgRIAJgRQALgUATgSQAUgSAagKQAZgKAXAEQALACAJAHAlkkfQAGABAGAFQAPALAHAXQADACABAEIADAFIAAABQAHAYAEAZIACAIIABAJIAGAVAkmiSIAGAOIgBAAIADAIIAIANIACAEIABAAIAAgCIADgDQAOgWARgQIAngfIAFgEIAQgLAk8jsIABAAAjbg/QgagJgQgRIgPgSAgUAbQAOAGAOAWQAQAYgHAaIgEAMIAKADAANB1QgGAQgIAPQgMASgVARIgpAhIgtAeAiBBeQh4AMhIg8");
	this.shape_1.setTransform(33.6,-74.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F5F386").s().p("AkyEDIgEgFIgDgCIgHgNIgVgeIgIgPIgGgVIgBgCIAAgBIABgDQAAgVAGgiIAIgaIABgCQAFgSALgKQADgIAFgFQgagFgigSIgQgJIAWAKQAbAOAeAJIgLAMIALgMQgegJgbgOIgWgKIgKgHIgBABIgkgYIgNgLIgBgBIgCgBIgIgHIgbglIgSgcQgNgaAAgaQAAgKACgLIAFgSIAFgFQAFgTAWgYQAlgrA2gMQATgFARALIAHADQARAMARAcIAFALIABAAIAAABQAIAYAEAZIABAIIACAJIAFAVIABACIAGAOIAAAAIADAIIAIANIABAEIACAAIAAgCIACgDQAHgeBAgnQADgEADgCIAOgJIgPALIgFAEIAFgEIAPgLIAhgVQAXgOAggOIAYgIIAggJIAGgBIAWgFIAOgCIACAAIAGgBIAHAAIAEgBIAGgBIAfgCIACAAIABAAIABAAIAEgBIAcAAIACAAIAQAAIASAAIAVACQAlADANAIIAFAGIAJgBQATgCAFAMIAAABIABAHIguAMIgTAHIATgHIAugMIgEAFIgVADQgTAEgVAHIgUAHIgBABIgFACIgCABIAPAIIAEACQAnAVAPAMIAFgCIAEABIAAAAIAUAPQBJA0AWAMIAxAZIA2AWIAhAMIgogDIguAAIgxAEIguALQAPAQAaAMQAZANAbAKIAzAXQAbAMAaAJIAVAEQgZAPgbADIg4AEIg3gDIg3gJIgogGIAoAnIAgAdIAJAJIAGAFIgqgDIgJgDIgvgMIg7gNIg3gNQgcgFgbgKIgPgFIAAgCIgHgBIgCgBIgNgFIgCgBIgDgDIAAABIgCAAIACABIgCgBIACAAIAAABIAAAAIACABIAFACIAAAAIgCgBIANAFIgKgEIgBAAQAOAIADALIgWgVIAWAVIAAAJIADAGQAAAEgEACIAAAAIgBAAIgKgFIAAgBIgBAAIgBgBIgCAAIgBAAIgCAAIgFgDQgFgCgFgEIgEgEIgBABIgBAEIgKgDIADgMQADgIAAgIQAAgSgMgQQgPgWgNgGQANAGAPAWQAMAQAAASQAAAIgDAIIgDAMIAKADQgQAkgwAoQgtAkgjAOIAtgeIAqghQAUgRALgSQAKgPAGgQQgGAQgKAPQgLASgUARIgqAhIgtAeQgGAFgGADIgBAAIgGADIgEAFIgHAEIgPAJIgeAQIgTALIgSABQg1AAgcgqgAigBeQASAAATgCIACAAIgCAAQgTACgSAAIAAAAIAAAAQhcAAg7gxIAAAAIgCgBIACABIAAAAQA7AxBcAAIAAAAIAAAAgAj+hbQAQARAbAJQgbgJgQgRIgPgSgACZjSIATAGIgTgGIAEgCIgEACIAAAAgAlLDlIgSggIgFgJIgBgPIAGAVIAIAPIAVAeIAHANQgJgJgJgOgAljCtgADCCGIgygNIA3ANgACQB5gAAfB2gAA0BcgAmIALgAoMiGQgFgYAFgRQACgKAGgHIACgDIgFASQgCALAAAKQAAAaANAagAEDibgADviqQAMgBAGAMIACAEg");
	this.shape_2.setTransform(32.8,-74.3);

	// Layer 2
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#463800").ss(1,0,0,3).p("AB7DAQgzAphIAAQhHAAgzgpQgzgnAAg5QAAg4AzgoQAegWAlgKQBChIAjheQA0gwBHATQgCArgOA2IgUBTQgGAcABAXQAuAnAAA1QAAA5gzAng");
	this.shape_3.setTransform(-4.3,-27.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F5F386").s().p("Ah6DAQgzgnABg5QgBg4AzgoQAegWAlgKQBChIAjheQA0gwBHATQgCArgOA2IgUBTQgGAcAAAXQAvAngBA1QABA5gzAnQg0AphHAAQhHAAgzgpg");
	this.shape_4.setTransform(-4.3,-27.5);

	// Layer 1
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#463800").ss(1,0,0,3).p("ADNjKQgBgEgDAAIgPgCIgKADQgMAEgLAIIgWASIgSAWIgEAKIgDAEIgFAKAgZAoIAhgdIAKgJIAFgCIACgCIAWgUAAhhqQACgNAGgLIANgZQAEgHAGgEABcjBQADgDACABIACACAjcCZIARgIQA/gaA/gqIA0glAk/C2QAKgCAIgDIATgEIAGgBAiWCXQgWAOgaAGQghAVgnAKIgiAHAkTCsIABAAIABgBIADgBIABAAIAxgRAiWCXQApgKAigWQA9gmAzg0AEzicIAGgJIgPgGIgUgDIgXABIgMAEIgOAGIgCABIgDABIgBABIgSALADNiUIgEAEIAAABQgBAAgBACAEzicIgTAVIgBACIgNALIAAAHADdhXIAYgQIAXgOIAGgFAEHheIADgFIAEgGIAEgKAD5gtIgCgBIgIgEQgMgGgLAAIgLgBIAIgBIACAAIALgEQAMgGAKgKIAPgQAD5gtIAGAFIABAAABzAOIgBABQALAKANAAIAcgDIAagGQANgCALgIIASgKIAEgDIAUgSIAKgJIgMgGADMiVIABAAIAJgRQAEgLAAgLIAAAAQgCgKgJgCQgBgCgBAAADNiUIAAgBADJiQQABgDACgCABbhmIADgIIAHgSIAAgBIACgLIAAgcIgEgZABcjBIgTARQgFAEgEAGABliAIgDANQgCAGgCgBAAehTIAAAHQAAAOAFAOIAGAUABBAHIgDgCIgBAAIgYAYABzAOQAMgCANgGIAXgLIARgPABBAHQALAGALACQAOACANgC");
	this.shape_5.setTransform(37.8,-28.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#734917").s().p("AAAAAIAAAAIABAAg");
	this.shape_6.setTransform(6.7,-7.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#F5F386").s().p("AkxDMIgBgBIgEgFIgBgBIgDgEIADgJQAKgCAIgDIATgEIACAAIAEgBIAAAAIABAAIABAAIABgBIADgBIABAAIAxgRIAFgBIAMgHIAkgQIAVgNIBFgnIARgJIAjgcIAhgdIAKgJIAFgEIACAAIAXgRIgBgDIgGgGQgQgaAFgdQAAgLACgLIABgBQAGgeAZgeQAEgGAFgEIATgRIAHAAIACACQAGAFABATIABAYIgDAEIgFAKIAFgKIADgEIAAACIABAAQAKgMANgIQAJgXAPgKQANgLAQgBQANgCAGAGIABAAIABACQAHAEAAAKQADAOgNAQIgCADIACAEIABABIgEAEQABgDACgCQgCACgBADIAAABIgCACIACgCIAAgBIAEgEIAAADIAFgFQAGgFAHgFIAOA/IgQAKIAQgKIADATIgBABIgYARIgCACIAAAAIACABIAHACIgGgBIgLgBIAIgBIgIABIALABIAGABIANADIAEACIAIAEIABACIABgBIAFgBIACAGIgBAAIgGgFIAGAFIABAAIgCAQIgTANQgXAWgxAFIgwgCQAMgCANgGIAXgLIARgPIgRAPIgXALQgNAGgMACIgCAAIgBAAQgagBgKgIIgGgDIgFAFIgDgCIgBAAIgYAYIAYgYIABAAIADACIgcAWIhVBAQhBAsglAOQgJAGgKAFIgdAJIgMAEIglAMQgNAOgZACgABviKIgCALIAAABIgHASIgDAIIADgIIAHgSIAAgBIACgLIAAgcIgEgZIAEAZgABqhxIADgNIgDANQgCAFgCAAIAAAAIAAAAQACAAACgFgADXjGQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAABgAk3C1IABgBIAUgEIAQgBIgTAEQgIADgKACgAkSCvgAi+CtQAPgDAOgGQgOAGgPADgAiOCZQgJAHgIADIgCABQAKgFAJgGgAD/gsgAD4hMIABgBIAGAhgAD3gwIgEgCIAIADIAEADgADzgyQgHgCgGgBQAGABAHACgAD2hgIAHgFIAXgOIAGgFIAAAHIgDACIgBAIIgEAGIgDAFIADgFIAEgGIgCAHIgFAEIgWAPgAD1hfIABgBIgBABgADrigIACgBQAbgNAsAHQAHAFAAAIIgTAVIgBACIgNALIgGAFIgXAOIgHAFgAEah4IANgLIABgCIATgVIgCAEIgQAXIgPAOgAB1iNgADRiOIAAAAgADViSgAE7iagABPixQALgPAKABIgTARQgFAEgEAGQADgHAEgGgABki/IAAAAg");
	this.shape_7.setTransform(37,-29.1);

	this.addChild(this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-21.7,-104.7,107.4,100.5);


(lib.shape45 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.051)").s().p("AlCA4QiGgXAAghQAAggCGgXQCGgYC8AAQC9AACGAYQCGAXAAAgQAAAhiGAXQiGAYi9AAQi8AAiGgYg");
	this.shape.setTransform(-9.9,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-55.7,-8,91.5,16.1);


(lib.shape43 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("ABBBEIgNgIIgLgFIgrABQgNALgPADIgBAAIgOgBIgBABQgOgEgJgHQgFALgGAFIgCADIgHADIgFABIABABIgDAAIgCAAIgGgBIgGgCIgHgEQgVgNAGgXQACgHADgGIgEgLIAAgMQgcgRAJgZQAKgbAYgOQARgLASgBIAIAAIAeAGIAJADIAKAFQAZAMANAWIAigBQAaAAAXAKQAaAMAQAWQAOASAAAcQgBAMgHAQQgGAPgFADAiDAEQADgNALgLQAPgOARgCAh/AbQAKgSATgFAhSAkQAEAPAJAI");
	this.shape.setTransform(6.8,1.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F5F386").s().p("ABBBEIgNgIIgLgFIgrABQgNALgPADIgBAAIgOgBIgBABQgOgEgJgHQgJgIgEgPQAEAPAJAIQgFALgGAFIgCADIgHADIgFABIABABIgDAAIgCAAIgGgBIgGgCIgHgEQgVgNAGgXQACgHADgGIgEgLIAAgMQgcgRAJgZQAKgbAYgOQARgLASgBIAIAAIAeAGIAJADIAKAFQAZAMANAWIAigBQAaAAAXAKQAaAMAQAWQAOASAAAcQgBAMgHAQQgGAPgFADIgBAAQgIAAg8gYgAh/AbQAKgSATgFQgTAFgKASgAh1gUQgLALgDANQADgNALgLQAPgOARgCQgRACgPAOgAhFA7IAAAAg");
	this.shape_1.setTransform(6.8,1.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.5,-7.7,30.7,18.5);


(lib.shape41 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("ADsgPQgvAZgKAHIgQALIgQANIgDADIgCABIgcAbIgBABQgXAbgSAfIgIAPIgDACQABAGgBAGQAAAbgNAOIgGAFQgIAGgKAAIgYgCQgLgFgJgHIgNgOIgCgDQgOgXgIgbIgGgSIgFgTIgEgNQgHgagLgaIgFgLIgVglIgJgTIgTgaIgLgQIgZgCIgRgIIgGgEIgJgGIgCgDIgHgJIgKgWIgBgRIAAgEIACgKIAHgQIADgDQAOgSAfAGIAYAGQACgKAKgJQAJgIAsARIABAAIABAAIAAAAQAQgJAQAMIAJAIQAPAOAHARIAIAWIAEANIADAJIABADIAHAaABCAiIABABIABABIAFAEIAFgFIAWgZQAMgOAPgOQARgRA2gpAiXi+IAAALIgBABIAAACQABAXASAKIACABIAAABIACABIACACIABAAIABAAIAKACAg9h/QgHAGgKgDIgCgBQgKgDgHgGIgEgHQgEgHAAgLIAAgHIgBgDIACgJIAMgRIAHgFAADhTIAAACIAGAVIAUAzQAHAPAJAKIAVASAgcAPQggADgSgTQgPgSAIgf");
	this.shape.setTransform(-21.9,4.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F5F386").s().p("AgCDSQgNgFgJgHIgNgOIgCgDQgOgXgIgbIgGgSIgFgTIgEgNQgHgagLgaIgFgLIgVglIgJgTIgTgaIgLgQIgZgCIgRgIIgGgEIgJgGIgCgDIgHgJIgKgWIgBgRIAAgEIACgKIAHgQIADgDQAOgSAfAGIAYAGQACgKAKgJQAJgIAsARIABAAIABAAIAAAAQAQgJAQAMIAJAIQAPAOAHARIAIAWIAEANIADAJIABADIADAJIAGARIAAACIAMAgIAPAhIAIASQALATAQAPIgVgSQgJgKgHgPIgUgzIgFgVIAAgCIAAACIAFAVIAUAzQAHAPAJAKIAVASIABABIABABIAFAEIAFgFIAWgZQAMgOAPgOQARgRA2gpQA5APgTAuQgvAZgKAHIgQALIgQANIgDADIgCABIgcAbIgBABQgXAbgSAfIgIAPIgDACIAAAMQAAAbgNAOIgGAFQgIAGgKAAgAgmAQIAGgBIgGABIAAAAIgBAAQgZgBgPgPIgDgBQgKgMAAgRQAAgKADgKQgDAKAAAKQAAARAKAMIADABQAPAPAZABIABAAIAAAAgAhLh7QAFAAAEgDIABAAIAAgBIAAABIgBAAQgEADgFAAIAAAAIgBAAIgEAAIAAAAIgBgBIgBAAIgCgBQgKgDgHgGIgEgHQgEgHAAgLIAAgHIgBgDIACgJIAMgRIAHgFIgHAFIgMARIgCAJIABADIAAAHQAAALAEAHIAEAHQAHAGAKADIACABIABAAIABABIAAAAIAEAAIABAAIAAAAgAiciwQABAXASAKIACABIAAABIACABIACACIABAAIABAAIAKACIgKgCIgBAAIgBAAIgCgCIgCgBIAAgBIgCgBQgSgKgBgXIAAgCIABgBIAAgLIAAALIgBABIAAACg");
	this.shape_1.setTransform(-21.5,4.3);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-45.3,-16.9,47.5,42.6);


(lib.shape39 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("AhZBMIBUgUIBLgUQAcgHAOgUQAQgSgFgXIgBAAQgEgXgXgMQgWgMgcAGIhQAVQhTAVgFAF");
	this.shape.setTransform(9.4,10);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F5F386").s().p("AhuAZQgQgxADgCQAGgFBTgVIBQgVQAbgGAWAMQAXAMAFAXIAAAAQAGAXgQASQgPAUgcAHIhLAUIhTAUIgBAAQgFAAgQgzg");
	this.shape_1.setTransform(9.4,10);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-3,2.4,25,15.3);


(lib.shape37 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.702)").s().p("Ag+AJIAIgHIARgFIAPAAQAGABAAACIgIAGIgPAGIgPABQgHgBgBgDgAAWADIgOgGQgEgEAFgDIAQgCIAVADQAKADAFAFQAEACgFADIgPADg");
	this.shape.setTransform(-0.4,2.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.8,1.4,12.7,2.8);


(lib.shape36 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgfAlQgGgBgEgJQgEgKAAgNQABgMAFgJQAFgJAGAAQAFABAFAJQAEAKgBALQgBAOgFAJQgEAJgFAAIgBAAgAAOAYQgDgKACgOQACgPAHgLQAGgKAGAAQAHgBADAKQAEALgDAQQgBANgHAKQgGALgIAAIAAAAQgGAAgDgKg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-4.6,-3.7,9.4,7.5);


(lib.shape34 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("ACTkrIB0gEIA2gKIA5gOIAhgJIgiAUIglAcQgUAOgRASIgfAkQAWAEAdgEIA4gMIA3gMIA2gPQANgFAHgEQgLAbgUATQgVAUgWAQIguAeQgYAOgZAMIgkATIA3AIIArAEIAMABIAJABQgOAPgWAIIgJADIgtASIg4AZIg0AWQgaAKgbAIIgPAFIgIACIgCAAIgLADIgCABIgCAAIgEABIgBAAIABAAIABAAIACAAIAeAEIAKABIAqAFQgRAHgVADIgCABIgMADIgBAAACbAwIgGACIgFABIgRAFIgKAEABPECIAAABIgEANIgDAHIgGAQIgPAfIgJAUAhDFyIgDAAIgOgGIgigMIgQgGIgRgOIgCgCIAAAAIgEgEIgCgDQgQgVgJgWIgBgDIgGgXAjDDZQgCAHABAIIAFAWABYlrIAFgGIgKAAAA6lsIgOAFAAkkkIAXgiIAdglAA1kfIAcgHIApgFIABAAIAYAAABWDwIARguIAOgzQAGgaAAgWIgGgjIgEgLQgJgagcgKQgZgIgQADAjihLIAOgkQAKgZASgeIAOgWIAUgaIAEgEIAPgRIAMgLIABgCIAEgEIAGgEIADgDIAFgFIAWgUIADgBIABAAIAAgBIADgDIAEgDIACgBIARgNIABgBIAPgMIAMgIIANgHIAXgOIAcgLAAfkcIgBAEIASgGAAkkkIgBABIgCAFIgCACAnzCAIgFgSIgDgTQgDgWAFgbQAFgaAPgWQAPgWAUgKQALgGALABAmlgsQAFgEAHABQAVABAZAQIAFADIAAAAIAmAfIAGAGIAHAGQAIAHAJAGAkgAeIANAIIAAABIAHAEIAOAGIAEACIABgBIgBgBIAAgEQgBgaADgVIAOgwIACgHIAGgSAlngbIABAAAltDfQgggFgcgNIgDgBQgHgDgFgDQgkgTgQgiIgHgRAgJCuIgEghIgGgxIgDgZIgKAQQgRAWgUAUQgUATgXAQIgHAFIgSAMIALA0IAJAdQALgcAXgTQAWgUAZgJgAiyA0QgaAJgXgEIgXgGAjDDZQgBgIACgHQgdALgfAFIgXAFIgMAAAkiDgIgsABIgfgCAh1ECIASAdQAMATAUAFQATAFATgcQANgWAFgbQAEgbgBgWIgBgQAjCDKQAdgLAcgO");
	this.shape.setTransform(-3.8,-34.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#423A28").s().p("Ag0BCIgKg0IARgMIAIgDQAXgPARgUQAUgUARgWIAKgQIAEAaIAFAwIAEAgIgbAHQgYAKgUATQgXAUgMAbg");
	this.shape_1.setTransform(-11.3,-18.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CF1010").s().p("AgDBEQgUgGgMgTIgSgdQALgZAXgUQAUgTAZgKIAbgHIABAPQABAXgEAaQgFAagNAVQgQAYgQAAIgEAAg");
	this.shape_2.setTransform(-10.2,-10.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F5F386").s().p("Ag9FxIgGgCIgDAAIgOgGIgigMIgQgGIgRgOIgCgCIAAAAIgCgDIgbgwIgJgZQgIgVAEgQIgBgFIACgKQgdALgfAFIgXAFIAXgFQAfgFAdgLIgCAKIABAFQgEgHACgGQgYALgmAFIgSADIgMAAIgBABIgsABIgfgCQgQgEgcgKIgfgLQgkgTgQgiIgHgRIABgIQgHgRADghQAEg5AlgoQANgPAUgBIAHgBQAVgCAeAOIALAFIABAAIAAAAIAmAfIAGAGIAHAGIARANIACABIANAIIAAABIAHAEIAOAGIAEACIABgBIgBgBIAAgEQgNgcAdhDQgBgFACgEIAHgQIAOgkQAKgZASgeIAOgWIAUgaIAEgEIAPgRIAMgLIABgCIAEgEIAGgEIADgDIAFgFIAWgUIADgBIABAAIAAgBIADgDIAEgDIACgBIARgNIABgBIANgJIAOgLIANgHQAigYARgBIAHABIAHgGQAEgEAGACQAIgIAHAFIABABIAEAFQACADgCADIgOAOQgNAPgNATIALgRIAdglIgdAlIgLARIgMARIAMgRIgMARIgBABIgCAFIgCACIgBAEIASgGIAFgBIBAgGIACgEIADgCIABAAQAJgIAMAGIADACIgYAAIAYAAIB0gEIA2gKIA5gOIAhgJIgiAUIglAcQgUAOgRASIgfAkQAWAEAdgEIA4gMIA3gMIA2gPIAUgJQgLAbgUATQgVAUgWAQIguAeQgYAOgZAMIgkATIA3AIIArAEIAMABIAJABQgOAPgWAIIgJADIgtASIg4AZIg0AWQgaAKgbAIIgPAFIgBgBIgHADIgCAAIgLADIgCABIgCAAIgEAAIAAABIAAAAIABAAIACAAIAFgBIAAAAQAQgDAJAIIAFAHIAHADQACADgCAEIgMADIAMgDIgBABQgEAEgHgCIgBAAIAAAAIgCAAIAAgBIgEADIgFABIgNABIgFAAIAAAAIABAEQAJAngRA+QgOA1gTAeIARguIAOgzQAGgYAAgVIAAgDIgGgjIAKgEIgKAEIgEgLQgJgagcgKIgBAAIgBAAIAAAAQgRgFgMAAIgBAAIAAAAIgHAAIgCAAIACAAIAHAAIAAAAIABAAQAMAAARAFIAAAAIABAAIABAAQAcAKAJAaIAEALIAGAjIAAADQAAAVgGAYIgOAzIgRAuIgBAFQgCAHgEAGIAAABIgDAGIgBAHIgDAHIgGAQIgPAfIgJAUQgiAggjAAQgRAAgRgGgAggBQQgRAWgUAUQgUATgXAQIgHAFIgSAMIALA0IAJAdIASAdQAMATAUAFQATAFATgcQANgWAFgbQAEgbgBgWIgBgQIgEghIgGgxIgDgZgAjCDHQAdgLAcgOQgcAOgdALgAjUA3QAOAAAQgEIABgBIABAAIABAAIAAAAIABgBIgBABIAAAAIgBAAIgBAAIgBABQgQAEgOAAIAAAAIAAAAIgNgBIgBAAIAAAAIgBAAIgXgGIAXAGIABAAIAAAAIABAAIANABIAAAAIAAAAgACcAZIgegEgAB6AVIABAAIgBAAIABAAIgBAAgAjog8IgCAHIACgHIAGgSgAhiFnIghgOIgKgFIgKgLIARAOIAQAGIAiAMIAOAGgAiXFJgAlgDdIgNgBIAfACgAnXCzQgSgQgHgQQgEgJAAgKIABgDIAHARQAQAiAkATQgXgJgIgHgAnzB9gAB1A5gADcgJgAEQgfIgDADIgxATgAEQgfgAAfkfIARgCIgSAGgAAwkhg");
	this.shape_3.setTransform(-3.8,-34.3);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-54.8,-71.9,101.5,75.2);


(lib.shape32 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("AB7DAQgzAphIAAQhHAAgzgpQgzgnAAg5QAAg4AzgoQAegWAlgKQBChIAjheQA0gwBHATQgCArgOA2IgUBTQgGAcABAXQAuAnAAA1QAAA5gzAng");
	this.shape.setTransform(-12.2,-26.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F5F386").s().p("Ah6DAQgzgnAAg5QAAg4AzgoQAegWAlgKQBChIAjheQA0gwBHATQgDArgNA2IgUBTQgGAcABAXQAuAnAAA1QAAA5gzAnQg0AphHAAQhHAAgzgpg");
	this.shape_1.setTransform(-12.2,-26.4);

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#463800").ss(1,0,0,3).p("AAwg9IgDAIQgCANACAOIACAVAAaAQIgCABIgGADIgMAHIgmAVIgKAFAhbBKQhFAdhDANAj2B4IgzAIIgBgBIgEABIgBAAIgBAAAk3CAIgTAAIgTABAi2CFQgUAIgWABQgnAOgqACIgiABAA3hTQAFgMAHgKIASgVQAGgGAHgEACCidQAEgCABACIABACACJhoIAGgJIAWgSIAYgNIAagIIAKAAIAPAEQACABAAAEQACAAAAACACJhoIgEADIgHAJIAAABIgGANQgDAFgCgBIgFAHAk3CAIAGAAAhbBKQAYgJAZgMAj2B4IATgEAAaAQIAZgPABvA0IAZgEIAagIQAMgFAHgGAAfAzQAOgJAOgKIABAAIADACIAUAMQANAFAOABAi2CFQAtgCAogPQBDgZA9goAFNhNIAJgHIgOgJIgTgHIgYgEIgMACIgPACIgCABIgYAIIgBABIAAAAIgEAEIgDACADrgaIAbgLIAZgJIAHgDIAPgKIABgBIAXgRAEkgrIACgGAEegiIgFAEIgDAFAEegiIAGgJAB+hcIAEgLQAFgNABgNIAAgaACCidQgLAIgLAGQgGACgEAFABzhKIALgRADohbIAMgOQAGgKACgLIAAAAQAAgKgIgFADjhWIAEgEADdAAIACAAIALgBQANgEAMgHIATgNAEEAZIgBgBIgFgFIgBgBIgIgGQgLgIgLgDQgGAAgDgBIAHAAABvA0IgBAAQAIAMANADIAcACIAaAAQANAAANgFIAUgJIAEgCQAOgHAKgGIALgIQgHgEgDgD");
	this.shape_2.setTransform(33.4,-22.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#734917").s().p("AAAAAIAAAAIABABg");
	this.shape_3.setTransform(-1.2,-6.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#F5F386").s().p("Ak2CdIgagHIgBgBIgDgGIgBgBIgCgEIAFgJIAAgDIACgBIAUABIAPACIgTABIgSAAIASAAIATgBIADABIAEgBIAAAAIACAAIABAAIADAAIACAAIAzgIIAFAAIANgDIAngKIAWgIIBMgYIASgGIAegQIALgFIAmgUIAMgIIAFgCIADgBIAZgNIgBgDIgDgFQgLgdALgcQACgKAEgKIABgBQANgcAegZQAEgHAFgEQAOgMAKACIAGACIACACQAFAGgDASIgDAYIgFAEIgHAJIAFgLQAFgOABgNIAAgZIAAAZQgBANgFAOIgFALIAAABIgKAQIgFAIIAFgIIAAAAIAAAAIAAAAIABAAIAAAAIABAAIAAgBIACgCIAAAAIABgBIAFgMIAAgBIAHgJIAFgEIgBACIAAACIABgCQAMgJAOgGQAOgUAQgHQAPgIAQACQANABAFAGIAAAAIABADQAGAGgBAJQgBAOgPAOIgDACIACAFIgFAFIgCACIACgCIAFgEIgBADIAHgDQAIgGAKgEIACAAQAegHAqAPQAGAHgCAHIgXARIgCACIgOAJIgIADIgZAKIgaAKIAagKIAZgKIAIgDIAOgJIACgCIAXgRIgCAEIgVAUIgSAKIACgGIgCAGIgEACIgCAIIgGAEIgDAFIgbALIgbANIgCAAIgIAAQADABAHABIAJADIAHADIAFAEIAIAGIAAACIACgBIAFAAIAAAGIAAgBIgFgFIAFAFIAAABIgEAPQgIAHgOACQgbAUgxgGQgjgEgLgHIAZgDIAZgIQAMgFAIgHQgIAHgMAFIgZAIIgZADIgCAAIgBgBQgagGgJgKIgEgEIgGAEIgEgCIAAAAIgcASQgoAUg5AZQhNAhgnAFIgQAEIgbAEIgQADIgmADQgNAKgUAAIgJgBgAB2iPQgFADgFAFQAFgFAFgDQAMgGALgHQgLAHgMAGgAjWCOQAOAAANgEQgNAEgOAAgAirCGQgHAEgHAAIgCAAIAQgEgABGAhIAAAAIAEACIggAQIAcgSgABKAjgAD/AMIgFgEIAKAGIADAEgAD6AIIgHgDIAHADgADqACQgHgBgDgBIAIAAIAAAAIACAAIAJAFIgJgDgAEjgdIAGgEIgEAGIgFADgAB+hKIAAAAIAAAAIAKgQIgFAMIgBABIAAAAIgCACIAAABIgBAAIAAAAIgBAAIAAAAgAB+hKIAAAAgADthVgADyhaIAAABIgFAEgADyhagACIhbgACUhogAD9iPIABABQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAABIgBgDgAD9iPIAAAAIAAAAg");
	this.shape_4.setTransform(32.3,-22.5);

	this.addChild(this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-29.6,-49.8,97.3,46.7);


(lib.shape30 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("AjmhMQgQgUAOgYQAOgVAgAFIAAAAIAAgBIgBgBQgLgbAMgZQAMgWAYgEIABAAQARgEANAEQAKACAIAHIAMALAhXjCIAHAJIAIAHIAGAEIARAtIATAvIALAbIACAFIACAGIABACIABACIAAACIAAABIADAGIANAvIAAACIAAABIACAEIAVA3IBYhKQAJgKARgNIBIg2AD6gLQgwAYgJAHIgQAMIgQAMIgEADIgCABIhuBSIAEAPQADAegNAVQgOAVgYABQgbADgRgSQgRgRgGgXIgRgwIgMgbIgKgUQgNgZgOgTIgiglQgNAIgRgCQgegCgOgSQgOgWATgVIACgEIACgCAifhTQAEARgaAFQgeAHgRgUIgCgCAi6iIQALAXAVAIQAJAFAIAAQAQgCAKgQAABAMIACAGAguAeQgfAHgQgVIgHgIQgLgQAAgWQABgOAGgBAiTgeIgGAHIgNAK");
	this.shape.setTransform(-23.3,3.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F5F386").s().p("AguDLQgSgRgFgXIgRgwIgNgbIgJgUQgOgZgOgTIghglIANgKIAGgHIgGAHIgNAKQgOAIgRgCQgdgCgOgSQgPgWATgVIADgEIACgCIAAAAQgPgUANgYQAOgVAgAFIABAAIAAgBIgBgBQgMgbAMgZQAMgWAYgEIACAAQAQgEAOAEQAKACAHAHIANALIAAACQABABAAAAQAAABABAAQAAAAAAgBQgBAAAAgBIAHAJIAIAHIAGAEIARAtIAUAvIALAbIABAFIADAGIAAACIABACIAAACIAAABIADAGIAOAvIgBgEIABAGIAAABIACAEIAVA3IBXhKQAKgKARgNIBHg2QA5AQgTAuQgvAYgKAHIgQAMIgQAMIgDADIgCABIhuBSIAEAPQACAegNAVQgOAVgVABIgIABQgYAAgOgQgAg/AgIALgBIACgBIgCABIgLABIgBAAIAAAAQgTAAgMgOIgCgCIgGgIQgLgQAAgWQABgOAGgBQgGABgBAOQAAAWALAQIAGAIIACACQAMAOATAAIAAAAIABAAgAjHg7IAOgBIAAAAIABgBQAWgEAAgOIgBgEIABAEQAAAOgWAEIgBABIAAAAIgOABIAAAAIAAAAQgTAAgMgNIgBgCIgDgCIADACIABACQAMANATAAIAAAAIAAAAgAiMhkQAPgCALgQQgLAQgPACQgJAAgJgFQgVgIgKgXQAKAXAVAIQAJAFAJAAIAAAAg");
	this.shape_1.setTransform(-22.9,3.9);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-48.1,-18,50.3,43.9);


(lib.shape28 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("AAIgoIhcAEQgUABgNALQgNALgBAPQgBARAKAKQAKAKAdACICWgCQAjgDAQgJQAPgKAAgH");
	this.shape.setTransform(0.1,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F5F386").s().p("Ah6AdQgKgKABgRQABgPANgLQANgLAUgBIBcgEIBMAAQASAAANANQAOAOACAJIACAOQAAAHgPAKQgQAJgjADIiWACQgdgCgKgKg");
	this.shape_1.setTransform(0.1,-0.3);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-13.1,-4.4,26.6,8.3);


(lib.shape26 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,0,0,3).p("AhDAgIh9iUIAABVIB9CUIAAhVIEEAAAjAh0IEEAAIB9CUIAABVIkEAA");
	this.shape.setTransform(-7.7,-7.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#37414D").s().p("AiBAqIAAhTIEDAAIAABTg");
	this.shape_1.setTransform(-1.4,-0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#515E70").s().p("AjAgfIAAhVIB9CUIAABVgAhDAgIh9iUIEDAAIB9CUgAjAh0g");
	this.shape_2.setTransform(-7.7,-7.7);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-27,-19.5,38.6,23.5);


(lib.shape23 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#463800").ss(1,0,0,3).p("AAsBJIgKAKQgQARgdAAQgSgBgNgGIgXgPIgQgWIgFgOIgBgNQABgNAHgNIAFgFQgNgJABgOQABgPAJgKIAIgGIgBgOQACgOAMgIQALgGANgBQAMAAAJAGIAFAEQAIAKACANQADgIAIgGQAMgIAPAFQANAGAJALIAPAWQAHANABAOIAAAJQgBAIgGAIIgWAfAAohBQAIAHAFAOQAEANgCAPQgBAMgIAGIgDADIgKADIgFAAQgGgCgGgEQgDgCgDgEAAFhCIAAACQAAAJgEAHIABAQIADAQQAAADACACAgGgPQAEgNgEgMIAAgCQgHgNgOgEIgagEQgIACgHAFAgbAvQAFgBADgDIAEgCIAJgPQAHgPgPgNIgDgDQgIgGgMgDIgYAEQgHABgGAHAgEgoIAFgIAgFgoIABAAAgGgoIABAA");
	this.shape.setTransform(-0.5,-1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#F5F386").s().p("AgqBdIgYgPIgPgWIgGgOIAAgNQABgNAHgNIAEgFQgMgJAAgOQABgPAKgKIAIgGIgCgOQADgOAMgIQAKgGAOgBQALAAAKAGIAFAEQAIAKABANQAEgIAIgGQAMgIAPAFQANAGAIALIAQAWQAHANABAOIAAAJQgBAIgGAIIgWAfQgQAWACAFQABAFgCACIgKAKQgQARgeAAQgRgBgNgGgAgGAaIgKAPIgDACQgDADgFABQAFgBADgDIADgCIAKgPQADgFAAgFQAAgKgLgIIgDgDQgIgGgMgDIgYAEQgHABgHAHQAHgHAHgBIAYgEQAMADAIAGIADADQALAIAAAKQAAAFgDAFgAAQACQAGAEAGACIAFAAIAKgDIADgDQAIgGABgMIABgJQAAgKgDgJQgGgOgIgHQAIAHAGAOQADAJAAAKIgBAJQgBAMgIAGIgDADIgKADIgFAAQgGgCgGgEQgDgCgDgEQADAEADACgAAAgwIABAQIAEAQQAAADACACQgCgCAAgDIgEgQIgBgQQAFgGAAgIIgBgCIAAgCIAAACIABACQAAAIgFAGIAAAAgAgGgPQACgGAAgHQAAgGgCgGIAAAAIABAAIgBgCIAAACIAAAAIAAgCQgHgNgOgEIgagEQgIACgHAFQAHgFAIgCIAaAEQAOAEAHANIAAACQACAGAAAGQAAAHgCAGgAgFgoIAFgIgAgGgog");
	this.shape_1.setTransform(-0.5,-1);

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#463800").ss(1,0,0,3).p("AgWBmQgxgqAShPIA+hLQADBsAsA4g");
	this.shape_2.setTransform(5.6,9.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#F5F386").s().p("Ag0gXIA/hLQACBsAtA5IhPAgQgxgqAShQg");
	this.shape_3.setTransform(5.5,9.4);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-9.3,-11.1,20.7,30.5);


(lib.shape20 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,1,0,3).p("AC7ghIhVBDQgGAFgDAJQgDAKACAIIAcBpQACAIgEADIgKgCIhcg8QgGgEgKAAIgPAEIhcA8IgKACQgEgDACgIIAdhpQACgIgDgKQgDgJgHgFIhVhDQgGgFABgEQACgEAIgBIBtgGQAIAAAIgGQAIgGADgHIAnhmQADgIADAAQAEAAADAIIAnBmQADAHAIAGQAIAGAIAAIBtAGQAIABACAEQABAEgGAFg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0)").s().p("ABsC0Ihcg7QgGgEgKAAIgPAEIhcA7IgKACQgEgCACgIIAdhqQACgIgDgJQgDgJgHgGIhVhCQgGgGABgEQACgEAIAAIBtgGQAIAAAIgGQAIgGADgIIAnhmQADgHADAAQAEAAADAHIAnBmQADAIAIAGQAIAGAIAAIBtAGQAIAAACAEQABAEgGAGIhVBCQgGAGgDAJQgDAJACAIIAcBqQACAIgEACg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,38.5,36.6);


(lib.shape18 = function() {
	this.initialize();

	// Layer 6
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.753)"],[0,1],5.3,-0.1,-4.3,-2.6).s().p("Ag2gRIBtAEIgGAfg");
	this.shape.setTransform(-8.8,-1.3);

	// Layer 5
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.753)"],[0,1],1.3,-4.5,-3.6,4).s().p("AABg0IAeAQIg9BZg");
	this.shape_1.setTransform(-5.5,7.9);

	// Layer 4
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.753)"],[0,1],-2.4,-3.8,2.3,4.9).s().p("AgkggIAdgRIAsBkg");
	this.shape_2.setTransform(5.5,8.4);

	// Layer 3
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.753)"],[0,1],-5,0.5,4.8,-0.3).s().p("Ag2gPQA2AAA3gBIhpAhg");
	this.shape_3.setTransform(8.6,-1.3);

	// Layer 2
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.753)"],[0,1],0.4,5.4,0.9,-4.4).s().p("AgPA2IANhsIATBtg");
	this.shape_4.setTransform(0.3,-8.5);

	// Layer 1
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.rf(["#FFEF24","#FCCA01"],[0,1],0,0,0,0,0,21.8).s().p("ABsC0Ihcg7QgGgEgKAAIgPAEIhcA7IgKACQgEgCACgIIAdhqQACgIgDgJQgDgJgHgGIhVhCQgGgGABgEQACgEAIAAIBtgGQAIAAAIgGQAIgGADgIIAnhmQADgHADAAQAEAAADAHIAnBmQADAIAIAGQAIAGAIAAIBtAGQAIAAACAEQABAEgGAGIhVBCQgGAGgDAJQgDAJACAIIAcBqQACAIgEACg");

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,38.5,36.6);


(lib.shape16 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0.251)","rgba(255,255,255,0)"],[0,1],7.8,50,-11.5,-47.7).s().p("AAAHYIiPuvIBAAAIDfOvg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-14.4,-47.2,29,94.6);


(lib.shape14 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#634C2C").ss(1,0,0,3).p("AD6DYIAAAYInzAAIAAnfIAXAAIHcAAg");
	this.shape.setTransform(-14.9,-54.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#997644").s().p("Aj5DwIAAnfIAXAAIAAHHIHcAAIAAAYg");
	this.shape_1.setTransform(-14.9,-54.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B39253").s().p("AjuDkIAAnHIHdAAIAAHHg");
	this.shape_2.setTransform(-13.7,-55.8);

	// Layer 2
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#634C2C").ss(1,0,0,3).p("AgBnXIAaAAIAABGIAAIOIAAFbIAjAAAgYHYIAAuvIAXAAAgBHYIAaAAAgYHYIAXAAAg7HYIAjAA");
	this.shape_3.setTransform(-15,-40.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#997644").s().p("AgYHYIAAuvIAXAAIAABGIAZAAIAAIOIgZAAIAAFbg");
	this.shape_4.setTransform(-15,-40.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#B39253").s().p("AgMHYIAAlbIAZAAIAAFbgAgMmRIAAhGIAZAAIAABGg");
	this.shape_5.setTransform(-13.9,-40.3);

	// Layer 1
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(0,0,0,0.051)").s().p("AhpAOQgsgGAAgIQAAgHAsgHIBpgGIBqAGQArAHABAHQgBAIgrAGIhqAHg");
	this.shape_6.setTransform(-21.4,7.2);

	this.addChild(this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-40,-87.6,50.2,97.1);


(lib.shape12 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FBAC09").s().p("AjRDSIAAmjIGjAAIAAGjg");
	this.shape.setTransform(21,21);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,42,42);


(lib.shape10 = function() {
	this.initialize();

	// Layer 28
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#875101").s().p("AgjAzQgQgWAAgdQAAgdAQgVQAPgVAUAAQAVAAAQAVQAPAVAAAdQAAAdgPAWQgQAVgVAAQgUAAgPgVg");
	this.shape.setTransform(2377.1,257.1);

	// Layer 27
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#5C3701").ss(1,0,0,3).p("AGV4aIAJgaIgJAAIsVAAQBWE0AwE9IAGAoQAqEkAHGrQAHGagbGQQgdGgg4EDQg+EdhSAXAG8Y1QhLggg+kqQg5kQgfmlQgemaAEmNQAEmmArkEIAGgoQA3k8Bokb");
	this.shape_1.setTransform(2378.5,213.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#875101").s().p("AjrZKQhFgfh4ggQBSgXA+keQA4kDAdmgQAbmPgHmbQgHmrgqkkIgGgoQgwk9hWk0IMVAAIAAAaQhoEbg3E8QgvAOg5gZIheg1Qg0gggYAAQglAAgXAzQgGLmAbITIAFAAIABAAQgDAIASAHQARAGAKAIIAHABIgEAAQgEAAAEAAQgyAQgXAkIgOAaQgPBJAXBKQAZBTA7ASQg7ARgEBBQgCHLATD3QARDcAeApQg3AFguAAQhiAAgugWg");
	this.shape_2.setTransform(2376.5,217.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#996600").s().p("AjgVYQgTj3ACnKQAEhBA9gSQg9gRgZhUQgXhJAPhJIAOgaQAXgkA0gQQgFgBAFAAIAEAAIgHAAQgMgIgRgHQgSgGADgJIgBAAIgFAAQgboSAGrmQAXg0AlABQAaAAA0AgIBeA1QA3AYAvgNIgGAoQgrEEgEGmQgEGNAeGaQAfGlA5EQQA+EqBLAgQiiAAhgAYQhfAYhjAgQgggogRjdgADu5cIAJAAIgJAag");
	this.shape_3.setTransform(2395.2,217.2);

	// Layer 26
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#5C3701").ss(1,0,0,3).p("AHEiwQBFh+AxiWIhjAEQhBCBhMBoQlGG4oZgKQgbAHgLAhADuBtQB7h5BbikAoxGpQANAYAXAFQHbg5Egkg");
	this.shape_4.setTransform(2441.5,144.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#875101").s().p("AorGpQgIgNgEgRQgEgSgCgWIgBgPIAAgCQGHBLGrkxQkhEgnbA6QgWgGgNgXgAFPjXQBMhoBBiBIBkgEQgyCWhFB+QgRguhpAHg");
	this.shape_5.setTransform(2441,144.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#996600").s().p("AoDEOIAAgCIAAgfQABgeAHgUQAMghAagHQIaAKFFm4QBpgHARAuQhaCkh7B5QlWD0lAAAQhPAAhNgPg");
	this.shape_6.setTransform(2435,151);

	// Layer 25
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#5C3701").ss(1,0,0,3).p("AHAFSIgBBdQn6ARj7nfIgXgvQhHiVgwjAIBSgLQBdDvB8CRIANAPQDvEOFjhQg");
	this.shape_7.setTransform(2319.8,135);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#875101").s().p("AkzgfIgYgvQhGiVgwjAIBSgMQBdDvB7CSQg2guhNAsQEOGMHOgKIgBBdIgiABQngAAjynPg");
	this.shape_8.setTransform(2319.5,135);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#996600").s().p("Alwi2QBMgsA2AuIAOAPQDvEOFihQIgGCzIgXAAQm9AAkHmCg");
	this.shape_9.setTransform(2328.2,148.4);

	// Layer 24
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#476501").ss(1,0,0,3).p("AVQiwQhXg/hxAAQhtAAhVA6QgZhihMhMQhyhyihAAQiiAAhyByQhCBCgcBTQiRhdjMAAQjOAAiTBeQhAApglAxIgkgEQhaAAhBBMQgZAegPAgQhfg/iCgEQgFh2h7hVQiBhYi3AAQi2AAiABYQiCBYAAB8QAAB7CCBYQCABYC2AAIBCgDQATBNBRA7QBpBNCVAAQCWAABphNQAegWAWgZQA6A2BLAAQBbAABBhNQATgXAOgZQCCBBCrAAQDNAACThfQAvgeAfghIANANQByBzCiAAQCIAABnhSQAZBHA6A6QBnBnCRAAQCRAABmhnQAdgdAUggQA+AYBIAAQCIAABhhVQBhhVAAh4QAAh3hhhVQhhhViIAAQiHAAhfBTg");
	this.shape_10.setTransform(2383,93.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#597E01").s().p("A0hGJQhRg7gThOIhCAEQi2gBiAhXQiChYAAh7QAAh8CChYQCAhXC2AAQC3AACBBXQB7BUAFB3QCCAEBfA/QAPggAZgdQBAhNBbAAIAlAEQAkgxBAgpQCSheDPAAQDMAACRBdQAchTBChCQByhxChgBQCiABByBxQBNBNAYBgQBVg5BtAAQBwABBYA+QBfhTCGABQCJAABhBUQBgBWAAB2QAAB3hgBWQhhBUiJAAQhIABg8gYQgVAggdAdQhnBmiQABQiSgBhmhmQg6g6gZhHQhnBSiJgBQihAAhyhyIgNgNQggAiguAdQiSBejOAAQirABiChBQgOAZgTAXQhABNhcgBQhLAAg6g1QgWAZgeAWQhpBNiWAAQiVAAhphNg");
	this.shape_11.setTransform(2383,93.8);

	// Layer 23
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("rgba(0,0,0,0.051)").s().p("AmwB0QjBgQgkhAQgmg9DHgxQDHgwEhAAQEfAAC/AuQDAAuAKApQAKAsjGATInNAmQiQALh8AAQhjAAhUgHg");
	this.shape_12.setTransform(2374.3,374.8);

	// Layer 22
	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(255,255,255,0.102)").s().p("EA9YAN1QgvgZghgcQh2BGilAAQipAAh2hIQh3hIABhlQAAglAPghQAcA6BLAtQB2BICpAAQClAAB2hGQAhAcAvAaQCdBWDgAAQDfAACfhWIAxgfQBtBDCWAAQChAABzhOQBLgzAahCQANAiAAAkQAABuhyBOQhzBNihAAQiWAAhthCIgxAdQifBXjfAAQjgAAidhXgEguQAIYQgagOgXgQQhtBCiWAAQihAAhyhNQhzhNAAhuQAAglANghQAaBCBMAzQByBOChAAQCWAABthDQAXAPAaAPQCfBXDfgBQDfABCehXQAvgaAhgbQB1BGCnAAQCnAAB3hIQBLguAcg6QAPAiABAlQAABlh3BHQh3BJingBQinABh1hHQghAdgvAZQieBWjfABQjfgBifhWgEAi8AHwIgZgPQg2AhhLAAQhRABg4gnQg6gnAAg3QAAgnAdgfQAMAMARALQA4AnBRAAQBLABA2giIAZAPQBPArBwAAQBwAABPgrQAXgNARgOQA6AjBUAAQBUAAA6gkIAYgQQAkAeAAAoQAAAzg8AkQg6AkhUAAQhUAAg6gkQgRAPgXAMQhPAshwAAQhwAAhPgsgECRtAFeIgmgcQg4AUhDAAQhzAAhQg7QhRg6AAhTQAAglARghQAUAnAsAhQBQA6BzAAQBDAAA4gVIAmAdQCIBcDAAAQCNAABvgxQBbAnB7AAQCNAABjgzQAwgZAYgdQAcAggBAmQAABIhjAzQhjA0iNAAQh7AAhbgnQhvAxiNAAQjAAAiIhcgAmzgCQg1gXgmgbIgSALQhXA1h6AAQh7AAhXg1QhXg2AAhOQAAgmAVgfQAVAhAtAdQBXA3B7AAQB6AABXg3IASgMQAmAbA1AYQC8BTEIAAQEKAAC8hTQBVgnAugsIANAGQBxA/CigBQCiABByg/QBCgkAdgtQATAgABAmQAABYhzA/QhyA/iiAAQiiAAhxg/IgNgHQguAuhVAlQi8BSkKAAQkIAAi8hSgEhRJgCAIglgdQg4AVhEAAQhyAAhQg7QhRg6ABhTQAAgmAQggQAUAoAsAfQBQA7ByAAQBEAAA4gUIAlAcQCJBcDBAAQCMAABvgxQBaAnB8AAQCMAABkg0QAvgYAZgdQAbAgAAAmQAABIhjA0QhkAziMAAQh8AAhagnQhvAxiMAAQjBAAiJhcgEiSCgEeQi3BCj3gBQkaAAjIhXQjIhXAAh7QAAglASghQAqBPCMA9QDIBYEaAAQD3AAC3hDQDdBUEaAAQGCAAESidQApgXAigZQBwAiCIABQDkgBCihjQB4hKAfhhQAKAhAAAlQABCNiiBkQiiBjjkAAQiIABhwgkQgiAZgpAYQkSCdmCAAQkaAAjdhTgArxn0IADgJIAEAJgEicGgPLIAGAdIgKABg");
	this.shape_13.setTransform(1704.6,138);

	// Layer 21
	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(255,255,255,0.149)").s().p("AjPCyIgZgOQg2AhhLAAQhRAAg4gnQg6gmAAg3QAAg3A6glQAdgUAjgKIgCgOQAAgkAwgYQAwgZBDAAQA+AAAuAVQASgVAfgTQBKguBoAAQBpAABLAuQBLAuAABBIgBAKIAngCQBUAAA6AjQA8AjAAAzQAAAyg8AkQg6AkhUAAQhUAAg6gjQgRAOgXAMQhPAshuAAQhwAAhPgsg");
	this.shape_14.setTransform(1949.1,169.7);

	// Layer 20
	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("rgba(255,255,255,0.149)").s().p("AnOH4Qi3BCj2gBQkbAAjIhXQjHhXAAh7QAAh8DHhXQB7g1CYgTQgNgvAAgzQAAjGDDiLQDCiMERAAQDsAACyBoQAkgCAnABQGCgBETCdQBHApA0AuQBcgWBrgBQDlABCiBjQChBkAACLQAACNihBkQiiBjjlAAQiHABhwgkQgjAZgoAYQkTCdmCAAQkYAAjdhTg");
	this.shape_15.setTransform(816.1,58.8);

	// Layer 19
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("rgba(255,255,255,0.149)").s().p("AlcD9IglgdQg4AVhEgBQhyAAhQg6QhRg6ABhTQgBhRBRg7QBQg7ByABQA2AAAuANQAagcAjgYQCJhbDBgBIAkABQBZg8B1gBQCJAABgBTQBhBSABB0QgBAegGAcQBMAJA9AgQBjAzAABJQAABIhjAzQhkA0iMgBQh8ABhagnQhvAwiKAAQjBABiJhcg");
	this.shape_16.setTransform(1220.1,99.7);

	// Layer 18
	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("rgba(255,255,255,0.149)").s().p("AmfFmQgbgOgWgQQhtBCiWAAQiiAAhyhNQhyhNAAhuQAAhuByhMQA7gnBHgUQgEgOAAgPQAAhGBfgyQBfgxCHAAQB9AABcArQAkgsA9gmQCVhbDRgBQDUABCVBbQCVBdAACCIgBATIBMgDQCoAAB3BHQB2BGAABmQAABlh2BHQh3BJiogBQimABh2hHQggAdgvAZQieBWjdABQjggBiehWg");
	this.shape_17.setTransform(1450.1,155.8);

	// Layer 17
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("rgba(255,255,255,0.149)").s().p("AolFXQg2gYgmgaIgSALQhXA3h6AAQh7AAhXg3QhXg2AAhOQAAhOBXg3QBXg1B7AAIAHAAQgTglAAgpQAAh1CThSQCUhSDQAAQDJAACRBNQAcgVAigTQCqhaDxAAQDxAACqBaQCqBaAACAQAAAigMAfIAoAUQBzA8AABZQAABYhzA/QhyA+ihAAQiiAAhyg+IgMgHQgvAthVAmQi8BUkIAAQkJAAi8hUg");
	this.shape_18.setTransform(1716,103.3);

	// Layer 16
	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("rgba(255,255,255,0.149)").s().p("AlZFmQgvgagggbQh2BGimAAQioAAh3hIQh2hIAAhmQAAhlB2hGQB3hICoAAIBMAFIgBgUQAAiCCVhcQCVhdDUAAQDRAACVBdQA9AlAkAsQBcgrB9AAQCHgBBfAyQBfAyAABHQAAAOgEAOQBHAUA7AoQByBLAABtQAABuhyBOQhyBNiiABQiWAAhthDIgxAeQieBXjggBQjdABiehXg");
	this.shape_19.setTransform(2132,190.7);

	// Layer 15
	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("rgba(255,255,255,0.149)").s().p("AlbD8IgmgcQg4AUhDAAQhzABhQg7QhRg7AAhTQAAhRBRg6QBQg6BzAAQA1gBAuANQAagbAkgXQCIhdDAAAIAlACQBZg+B1ABQCJAABgBSQBhBRAAB1QAAAdgGAcQBMALA9AeQBjA0AABJQAABIhjAzQhjAziNAAQh7AAhbgmQhvAxiLgBQjAAAiIhcg");
	this.shape_20.setTransform(2672,147.7);

	// Layer 14
	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#669900").s().p("Aq5CiIAGglQAAgLAIgaIAHgfIAoAhQATAPAUAAQAgAAAIgTIAWhgQAPAKAbAjQAdAmAMALIBLAAIAAgqQALAOASAHIAHg6IABg4IAIAAQAFAVAHAOQAOAZAegBQATABAUgoIALgbQAFAwAdAqQAlA7AlgBQAqAAAEgdQAAgvAKgfQAEAFAFACIAGAAIAXAUQASAQAJADIAAhJIApAyQAQAQAWAAQAWAAAihXQAbhHADgZIAAAAQAAAPgIAoQgHApAAAHQAAA5AXAXQASAVAiAAQASAAARgQQAPgPACgTQABAdACAFQAFAQAaAAQAWAAAghGQAlhTAKgJIAAAHIgCBlQgCBHAEAlQAlAMAnglIAigjQAWgXASgNIAAAHQgCANgKATIgRAeIAAApIBDAAIA5gIQAYgGAOgKIgEAFQgTAWgJAwg");
	this.shape_21.setTransform(69.9,328.3);

	// Layer 13
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#669900").s().p("Av8CiQgPgwgdgWIgGgFQAWAKAlAGIBXAIIBnAAIAAgpIgbgeQgPgTgDgNIAAgHQAbANAjAXIA0AjQA6AlA5gMQAIglgDhHIgFhlIAAgHQARAJA4BTQAxBGAiAAQAoAAAIgQQADgFAAgdQAEATAXAPQAaAQAcAAQA1AAAbgVQAjgXAAg5IgLgwQgMgoAAgPIABAAQAEAZApBHQA0BXAiAAQAhAAAZgQQALgGA0gsIAABJQAPgDAbgQIAlgUIAHAAIAPgHQAPAfAAAvQAHAdBBAAQA3ABA5g7QArgqAKgwQAGANAKAOQAfAoAegBQAtABAUgZQAMgOAIgVIAMAAIACA4QACAfAIAbQAdgHARgOIAAAqIBzAAQASgLAtgmQAogjAXgKQAcBYAFAIQANATAyAAQAeAAAdgPIA+ghQAAAFALAaQAMAaAAALIAJAlg");
	this.shape_22.setTransform(251.9,328.3);

	// Layer 12
	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#669900").s().p("AvgCiIAIglQAAgLALgaIALgfIA6AhQAaAPAbAAQAvAAAMgTQAFgIAahYQAVAKAmAjIA6AxIBrAAIAAgrQAPAPAbAHQAHgbACgfIACg4IALAAQAIAVAKAOQATAYArAAQAbAAAdgnIAOgbQAJAwAoAqQA1A7A0gBQA8AAAGgdQAAgvAOgfIAOAGIAHABIAiAVQAZAPAOADIAAhJIA6AyQAXAQAfAAQAgAAAwhXQAlhHAFgZIAAAAQAAAPgKAoQgLApAAAHQAAA5AgAXQAaAVAxAAQAaAAAXgQQAWgPADgTQABAdACAFQAHAQAmAAQAgAAAthGQA0hSAPgKIAAAHIgEBlQgCBHAGAlQA1AMA2glIAxgjQAfgXAbgMIAAAGQgEANgOATIgZAeIAAApIBgAAIBRgIQAigGAUgKIgFAFQgbAWgOAwg");
	this.shape_23.setTransform(850.4,329.3);

	// Layer 11
	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#669900").s().p("Aq5CiIAGglQAAgLAIgaIAHgfIAoAhQATAPATAAQAhAAAIgTIAWhgQAPAKAbAjQAdAmAMALIBLAAIAAgqQALAOASAHQAGgbABgfIABg4IAIAAQAFAVAHAOQAOAZAegBQATABAUgoIALgbQAFAwAdAqQAmA7AkgBQAqAAAEgdQAAgvAKgfIAJAHIAGAAIAXAUQASAQAJADIAAhJQAiAsAIAGQAPAQAWAAQAWAAAihXQAahHAEgZIAAAAQAAAPgHAoQgIApAAAHQAAA5AXAXQASAVAiAAQATAAAQgQQAPgPACgTQABAdABAFQAFAQAbAAQAXAAAfhGQAkhTALgJIAAAHIgCBlQgCBHAEAlQAlAMAnglIAigjQAWgXATgNIAAAHQgDANgKATIgRAeIAAApIBDAAIA5gIQAYgGAOgKIgEAFQgTAWgJAwg");
	this.shape_24.setTransform(419.9,328.3);

	// Layer 10
	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#669900").s().p("Av9CiQgPgwgdgWIgFgFQAWAKAkAGIBYAIIBnAAIAAgpIgbgeQgPgTgEgNIAAgHQAdANAhAXIA1AjQA7AlA5gMQAGglgChHIgEhlIAAgHQAQAJA4BTQAxBGAiAAQAoAAAIgQQADgFABgdQADATAYAPQAZAQAcAAQA1AAAcgVQAigXAAg5QAAgHgMgpQgLgoAAgPIAAAAQAFAZApBHQA0BXAjAAQAgAAAZgQQALgGA0gsIAABJQAPgDAbgQIAkgUIAIAAIAQgHQAPAfgBAvQAHAdBBAAQA3ABA6g7QArgqAKgwQAEANALAOQAfAoAegBQAtABAUgZQALgOAKgVIALAAIACA4QACAfAHAbQAegHAQgOIAAAqIB0AAIA+gxQApgjAXgKQAcBYAGAIQAMATAyAAQAeAAAcgPIA/ghQAAAFALAaQAMAaAAALIAJAlg");
	this.shape_25.setTransform(641.9,328.3);

	// Layer 9
	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#669900").s().p("AvgCiIAIglQAAgLALgaQALgaAAgFIA6AhQAaAPAbAAQAvAAAMgTQAFgIAahYQAVAKAmAjIA6AxIBrAAIAAgrQAPAPAbAHQAHgbACgfIACg4IALAAQAIAVAKAOQATAYArAAQAbAAAdgnIAOgbQAJAwAoAqQA1A7A0gBQA8AAAGgdQAAgvAOgfIAOAGIAHABIAiAVQAZAPAOADIAAhJIA6AyQAXAQAfAAQAgAAAwhXQAlhHAFgZIAAAAQAAAPgKAoQgLApAAAHQAAA5AgAXQAaAVAxAAQAaAAAXgQQAWgPADgTQABAdACAFQAHAQAmAAQAgAAAthGQA0hSAPgKIAAAHIgEBlQgCBHAGAlQA1AMA2glIAxgjQAfgXAbgMIAAAGQgEANgOATIgZAeIAAApIBgAAIBRgIQAigGAUgKIgFAFQgbAWgOAwg");
	this.shape_26.setTransform(1500.4,329.3);

	// Layer 8
	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#669900").s().p("Aq5CiIAGglQAAgLAHgaIAIgfIAoAhQATAPAUAAQAgAAAIgTIAWhgQAPAKAbAjQAdAmAMALIBKAAIAAgqQAMAOASAHQAGgbABgfIABg4IAHAAQAHAVAHAOQANAZAegBQATABAUgoIALgbQAFAwAdAqQAlA7AlgBQApAAAFgdQAAgvAJgfIAKAHIAGAAIAXAUQASAQAJADIAAhJIApAyQAQAQAWAAQAWAAAihXQAbhHADgZIAAAAQAAAPgIAoQgHApAAAHQAAA5AXAXQASAVAiAAQASAAARgQQAPgPACgTQABAdACAFQAEAQAbAAQAWAAAghGQAkhTALgJIAAAHIgDBlQgBBHAEAlQAlAMAnglIAigjQAWgXASgNIAAAHQgCANgKATIgRAeIAAApIBDAAIA5gIQAXgGAPgKIgEAFQgTAWgJAwg");
	this.shape_27.setTransform(1069.9,328.3);

	// Layer 7
	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#669900").s().p("Av9CiQgOgwgegWIgFgFQAXAKAjAGIBYAIIBoAAIAAgpIgcgeQgPgTgEgNIAAgHQAcANAiAXIA1AjQA7AlA4gMQAIglgDhHIgFhlIAAgHQARAJA4BTQAwBGAjAAQApAAAHgQQADgFABgdQADATAXAPQAaAQAcAAQA0AAAdgVQAigXAAg5IgMgwQgLgoAAgPIAAAAQAFAZApBHQA0BXAjAAQAgAAAZgQIA/gyIAABJQAPgDAbgQIAkgUIAIAAIAQgHQAPAfgBAvQAHAdBBAAQA3ABA6g7QAqgqALgwQAEANALAOQAfAoAdgBQAuABAVgZQAKgOAKgVIALAAIACA4QACAfAHAbQAegHAQgOIAAAqIBzAAIA/gxQApgjAXgKQAcBYAFAIQANATAyAAQAeAAAcgPIA/ghQAAAFAMAaQALAaAAALIAJAlg");
	this.shape_28.setTransform(1291.9,328.3);

	// Layer 6
	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#669900").s().p("AvgCiIAIglQAAgLALgaIALgfIA6AhQAaAPAbAAQAvAAAMgTQAFgIAahYQAVAKAmAjIA6AxIBrAAIAAgrQAPAPAbAHQAHgbACgfIACg4IALAAQAIAVAKAOQATAYArAAQAbAAAdgnIAOgbQAJAwAoAqQA1A7A0gBQA8AAAGgdQAAgvAOgfQAGAEAIACIAHABIAiAVQAZAPAOADIAAhJIA6AyQAXAQAfAAQAgAAAwhXQAlhHAFgZIAAAAQAAAPgKAoQgLApAAAHQAAA5AgAXQAaAVAxAAQAaAAAXgQQAWgPADgTQABAdACAFQAHAQAmAAQAgAAAthGQA0hSAPgKIAAAHIgEBlQgCBHAGAlQA1AMA2glIAxgjQAfgXAbgMIAAAGQgEANgOATIgZAeIAAApIBgAAIBRgIQAigGAUgKIgFAFQgbAWgOAwg");
	this.shape_29.setTransform(2130.4,329.3);

	// Layer 5
	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#669900").s().p("Aq5CiIAGglQAAgLAHgaIAIgfIAoAhQATAPAUAAQAgAAAIgTIAWhgQAPAKAbAjQAcAmANALIBKAAIAAgqQAMAOASAHQAGgbABgfIABg4IAHAAQAGAVAIAOQANAZAegBQATABAUgoIALgbQAFAwAdAqQAlA7AlgBQApAAAFgdQAAgvAJgfQAFAFAFACIAGAAIAXAUQASAQAJADIAAhJIApAyQAQAQAWAAQAWAAAihXQAbhHADgZIAAAAQAAAPgIAoQgHApAAAHQAAA5AXAXQASAVAiAAQASAAARgQQAPgPACgTQABAdACAFQAEAQAbAAQAWAAAghGQAlhTAKgJIAAAHIgDBlQgBBHAEAlQAlAMAnglIAigjQAWgXASgNIAAAHQgCANgKATIgRAeIAAApIBDAAIA5gIQAXgGAPgKIgEAFQgTAWgJAwg");
	this.shape_30.setTransform(1699.9,328.3);

	// Layer 4
	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#669900").s().p("Av9CiQgOgwgegWIgFgFQAXAKAjAGIBYAIIBoAAIAAgpIgcgeQgPgTgEgNIAAgHQAcANAiAXIA1AjQA7AlA4gMQAIglgDhHIgFhlIAAgHQARAJA4BTQAwBGAjAAQApAAAHgQQADgFABgdQADATAXAPQAaAQAcAAQA0AAAdgVQAigXAAg5IgMgwQgLgoAAgPIAAAAQAFAZApBHQA0BXAjAAQAgAAAZgQIA/gyIAABJQAPgDAbgQIAkgUIAIAAIAQgHQAPAfgBAvQAHAdBBAAQA3ABA6g7QAqgqALgwQAEANALAOQAfAoAdgBQAuABAVgZQAKgOAKgVIALAAIACA4QACAfAHAbQAegHAQgOIAAAqIBzAAIA/gxQApgjAXgKQAcBYAFAIQANATAyAAQAeAAAcgPIA/ghQAAAFAMAaQALAaAAALIAJAlg");
	this.shape_31.setTransform(1921.9,328.3);

	// Layer 3
	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#669900").s().p("AvOCiIAIglQAAgLALgaIALgfIA6AhQAaAOAbAAQAvAAAMgSQAFgIAahYQAVAKAmAjIA6AxIBrAAIAAgrQAPAPAbAIQAHgcACgfIACg4IALAAQAIAVAKAOQATAZArAAQAbAAAdgoIAOgbQAJAwAoAqQA1A7A0AAQA8AAAGgeQAAgvAOgfQAGAEAIACIAHABIAiAVQAXAPAQADIAAhJIA6AyQAXAQAfAAQAgAAAwhYQAlhGAFgZIAAABQAAAPgKAoQgLAoAAAHQAAA5AgAXQAaAVAxAAQAaAAAXgQQAWgOADgUQABAdACAGQAHAPAUAPQAUAPAvhJQAuhKgCBlQAxhIgCAhIgCAkQA9BUAwhYQAkAdARgMQAfgWAbgNIAAAHQgEANgOASQgJAKAPAHIBBgOIgOAVQAiAcAcAIQAsgEAFAJQAGAJgOAwg");
	this.shape_32.setTransform(2738.6,331.3);

	// Layer 2
	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#669900").s().p("Aq5CiIAGglQAAgLAIgaIAHgfIAoAhQATAPATAAQAhAAAJgTQADgIAShYQAPAKAbAjQAdAmALALIBLAAIAAgqQAMAOASAHQAGgbABgfIABg4IAHAAQAGAVAHAOQAOAZAegBQATABAUgoIALgbQAFAwAdAqQAmA7AkgBQAqAAAEgdQAAgvAJgfIAKAHIAFAAIAYAUQASAQAJADIAAhJIApAyQAQAQAWAAQAWAAAihXQAahHADgZIABAAQAAAPgIAoQgHApAAAHQAAA5AWAXQATAVAiAAQATAAAQgQQAPgPACgTQABAdABAFQAGAQAaAAQAWAAAghGQAkhTALgJIAAAHIgCBlQgCBHAEAlQAmAMAmglIAigjQAWgXASgNIAAAHQgCANgKATIgSAeIAAApIBEAAIA5gIQAXgGAPgKIgEAFQgSAWgKAwg");
	this.shape_33.setTransform(2309.9,328.3);

	// Layer 1
	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#669900").s().p("Av9CiQgPgwgdgWIgFgFQAWAKAkAGIBYAIIBnAAIAAgpIgbgeQgPgTgEgNIAAgHQAdANAhAXIA1AjQA6AlA6gMQAGglgChHIgEhlIAAgHQAQAJA4BTQAxBGAiAAQAoAAAIgQQADgFABgdQADATAYAPQAZAQAcAAQA1AAAcgVQAigXAAg5QAAgHgMgpQgLgoAAgPIABAAQAEAZApBHQA0BXAjAAQAhAAAYgQIA/gyIAABJQAPgDAbgQIAkgUIAIAAIAPgHQAPAfAAAvQAHAdBBAAQA3ABA6g7QAqgqALgwQAEANALAOQAfAoAdgBQAuABAUgZQALgOAKgVIALAAIACA4QACAfAHAbQAegHAQgOIAAAqIBzAAIBAgxQAogjAXgKQAcBYAGAIQAMATAyAAQAeAAAcgPIA/ghQAAAFALAaQAMAaAAALIAJAlg");
	this.shape_34.setTransform(2531.9,328.3);

	this.addChild(this.shape_34,this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,2836.2,387.2);


(lib.shape7 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#669900").s().p("EgnDAHCIAAuCMBOHAAAIAAOCg");
	this.shape.setTransform(250,295);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["#F5DD89","#E7803A"],[0,1],-2.8,90.1,-2.8,-169.8).s().p("EgnDAakMAAAg1HMBOHAAAMAAAA1Hg");
	this.shape_1.setTransform(250,170);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,500,340);


(lib.shape6 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhpBiQgZgZAAgjQAAgXALgQQgIgRAAgTQAAgkAZgZQAZgYAjAAQAfAAAVATIAVgCQApAAAeAdQAdAeAAApQAAAogdAdQgeAdgpAAIgMAAIgGAFQgWAZgkAAQgjAAgZgZg");
	this.shape.setTransform(0.5,-0.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-12.5,-12.5,26.3,24.8);


(lib.sprite62 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape63("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,500,336);


(lib.sprite52 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape53("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.4,9.1,39.8,20.8);


(lib.sprite50 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape37("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.8,1.4,12.7,2.8);


(lib.sprite44 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape45("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-55.7,-8,91.5,16.1);


(lib.sprite42 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape43("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.5,-7.7,30.7,18.5);


(lib.sprite40 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape41("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-45.3,-16.9,47.5,42.6);


(lib.sprite38 = function() {
	this.initialize();
  
	// Layer 1
	this.instance = new lib.shape39("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-3,2.4,25,15.3);


(lib.sprite35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});
  this.frame1 = function(){this.stop()}
	// Layer 1
	this.instance = new lib.shape36("synched",0);

	this.instance_1 = new lib.shape37("synched",0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).wait(5));
  this.timeline.addTween(cjs.Tween.get(this).call(this.frame1).wait(6))
}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4.6,-3.7,9.4,7.5);


(lib.sprite33 = function() {
	this.initialize();

	// Layer 2
	this.eyes = new lib.sprite35();
	this.eyes.setTransform(-15.4,-38.9);

	// Layer 1
	this.instance = new lib.shape34("synched",0);

	this.addChild(this.instance,this.eyes);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-54.8,-71.9,101.5,75.2);


(lib.sprite31 = function() {
	this.initialize();

	// Layer 2
	this.head = new lib.sprite33();
	this.head.setTransform(4.5,-49.5);

	// Layer 1
	this.instance = new lib.shape32("synched",0);

	this.addChild(this.instance,this.head);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-50.3,-121.4,118,118.3);


(lib.sprite29 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape30("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-48.1,-18,50.3,43.9);


(lib.sprite27 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape28("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-13.1,-4.4,26.6,8.3);


(lib.sprite25 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape26("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-27,-19.5,38.6,23.5);


(lib.sprite22 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape23("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-9.3,-11.1,20.7,30.5);


(lib.sprite21 = function() {
	this.initialize();
  var self = this;
	// Layer 11
	this.arm = new lib.sprite42();
	this.arm.setTransform(0,154);

	// Layer 10
	this.leg = new lib.sprite40();
	this.leg.setTransform(-26.5,197.3);
  
  //layer 9
  this.rope = new cjs.Shape();
 
	// Layer 8
	this.thigh = new lib.sprite27();
	this.thigh.setTransform(-16.8,196.4);

	// Layer 7
	this.bicep = new lib.sprite38();
	this.bicep.setTransform(-0.2,153.6,1.004,1.005);

	// Layer 6
	this.body = new lib.sprite31();
	this.body.setTransform(2.5,202);

	// Layer 5
	this.leg2 = new lib.sprite29();
	this.leg2.setTransform(-33.4,190.5);

	// Layer 4
	this.thigh2 = new lib.sprite27();
	this.thigh2.setTransform(-24.1,190.1);

	// Layer 3
	this.seat = new lib.sprite25();
	this.seat.setTransform(0,206.8);
  // layer 2
  this.rope2 = new cjs.Shape();
  this.rope2.setTransform(-15.0, -5.0);
	// Layer 1
	this.arm2 = new lib.sprite22();
	this.arm2.setTransform(-14.9,155.5);

	this.addChild(this.arm2, this.rope2, this.seat,this.thigh2,this.leg2,this.body,this.bicep,this.thigh, this.rope, this.leg,this.arm);
	this.on("tick", function ()
  {
    self.rope.graphics.clear();
    self.rope.graphics.beginStroke("#000000").setStrokeStyle(5);
    self.rope.graphics.moveTo(self.rope.x, self.rope.y);
    self.rope.graphics.lineTo(self.arm.x, self.arm.y);
    self.rope.graphics.lineTo(self.seat.x, self.seat.y);
    self.rope.graphics.beginStroke("#515E70").setStrokeStyle(3);     
    self.rope.graphics.moveTo(self.rope.x, self.rope.y);
    self.rope.graphics.lineTo(self.arm.x, self.arm.y);
    self.rope.graphics.lineTo(self.seat.x, self.seat.y);
    self.rope2.graphics.clear();
    self.rope2.graphics.beginStroke("#000000").setStrokeStyle(5);
    self.rope2.graphics.moveTo(self.rope.x, self.rope.y);
    self.rope2.graphics.lineTo(self.arm.x, self.arm.y);
    self.rope2.graphics.lineTo(self.seat.x, self.seat.y);
    self.rope2.graphics.beginStroke("#515E70").setStrokeStyle(3); 
    self.rope2.graphics.moveTo(self.rope.x, self.rope.y);
    self.rope2.graphics.lineTo(self.arm.x, self.arm.y);
    self.rope2.graphics.lineTo(self.seat.x, self.seat.y);
  });
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-81.5,80.5,151.7,142.4);


(lib.sprite19 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape20("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,38.5,36.6);


(lib.sprite17 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape18("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,38.5,36.6);


(lib.sprite15 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape16("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-14.4,-47.2,29,94.6);


(lib.sprite13 = function() {
	this.initialize();

	// Layer 4
	this.instance = new lib.sprite19();
	this.instance.setTransform(-14.6,-55.4);

	// Layer 3
	this.instance_1 = new lib.sprite17();
	this.instance_1.setTransform(-14.6,-55.4);

	// Layer 2
	this.instance_2 = new lib.sprite15();
	this.instance_2.setTransform(-4.7,40.4);

	// Layer 1
	this.instance_3 = new lib.shape14("synched",0);

	this.addChild(this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-40,-87.6,50.2,175.4);


(lib.sprite11 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape12("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,42,42);


(lib.sprite9 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape10("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,2836.2,387.2);


(lib.sprite5Puff = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape6("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-12.5,-12.5,26.3,24.8);


(lib.sprite65 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{point:1,loss:8});

	// timeline functions:
	this.frame_0 = function(){this.stop()}
	this.frame_1 = function() {
		playSound("sound66");
	}
	this.frame_7 = function(){
   this.stop ();
   if (!this.parent.gameWin)
   {
     this.parent.parent.gotoAndPlay("reset");
   }
   else
   {
    //this.parent.parent.GameEndClip.gotoAndPlay("GameWonPlayground");
    this.parent.parent.GameWon = true;
   } // end else if	
	}
	this.frame_8 = function() {
		playSound("sound68");
    var damp = 0.700000;
    for (var i = 1; i <= 20; i++)
    {
    this["puff" + i] = new lib.sprite5Puff(); //attachMovie("Puff", "puff" + i, i);
    this.addChild(this["puff" + i]);
    this["puff" + i].rotation = Math.random() * 360;
    this["puff" + i].scaleX = this["puff" + i].scaleY = (Math.random() * 40 + 80)/100;
    this["puff" + i].velX = Math.random() * 40 - 20;
    this["puff" + i].velY = Math.random() * 40 - 20;
    this["puff" + i].step = Math.random() * 10 + 10;
    this["puff" + i].on("tick", function (evt)
    {
        evt.currentTarget.velX = evt.currentTarget.velX * damp;
        evt.currentTarget.velY = evt.currentTarget.velY * damp;
        evt.currentTarget.x = evt.currentTarget.x + evt.currentTarget.velX;
        evt.currentTarget.y = evt.currentTarget.y + evt.currentTarget.velY;
        evt.currentTarget.scaleX = evt.currentTarget.scaleY = evt.currentTarget.scaleY - evt.currentTarget.step/100;
        if (evt.currentTarget.scaleX <= 0)
        {
            self.removeChild(evt.currentTarget);
            evt.remove();
            delete evt.currentTarget
        } // end if
    });
    } // end of for
		
	}
  this.frame_14 = function(){
   this.parent.gotoAndStop(this.parent.currentFrame - 1); //prevFrame();
   this.parent.lose();  
  }
	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(6).call(this.frame_7).wait(1).call(this.frame_8).wait(6).call(this.frame_14));

	// Layer 3
	this.instance = new lib.sprite19();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).wait(1).to({scaleX:1.19,scaleY:1.19},0).wait(1).to({scaleX:1.25,scaleY:1.25},0).wait(1).to({scaleX:1.21,scaleY:1.21},0).to({scaleX:1.13,scaleY:1.13},1).wait(1).to({scaleX:1.05,scaleY:1.05},0).wait(1).to({scaleX:1,scaleY:1},0).wait(8));

	// Layer 2
	this.instance_1 = new lib.sprite17();
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).wait(1).to({scaleX:1.19,scaleY:1.19,alpha:0.75},0).wait(1).to({scaleX:1.25,scaleY:1.25,alpha:1},0).wait(1).to({scaleX:1.21,scaleY:1.21},0).wait(1).to({scaleX:1.13,scaleY:1.13},0).to({scaleX:1.07,scaleY:1.07},1).wait(1).to({scaleX:1,scaleY:1},0).to({_off:true},1).wait(7));

	// Layer 1
	this.instance_2 = new lib.shape67("synched",0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(3).to({startPosition:0,_off:false},0).to({_off:true},5).wait(7));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,38.5,36.6);


(lib.sprite64 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});
  this.frame1 = function(){
   this.score = function ()
   {
    this.gotoAndStop(this.currentFrame + 1);    
    this["star" + this.currentFrame].gotoAndPlay("point");
   } // End of the function
   this.lose = function ()
   {
    if (this.currentFrame > 0)
    {
        this["star" + this.currentFrame].gotoAndPlay("loss");
    } // end if
   } // End of the function
   this.stop ();
   this.gameWin = false;  
  }
  this.frame4 = function(){
    this.gameWin = true
  }
  
	// Layer 3
	this.star3 = new lib.sprite65();
	this.star3.setTransform(74.4,-3.2,0.823,0.823);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.star3}]}).wait(4));

	// Layer 2
	this.star2 = new lib.sprite65();
	this.star2.setTransform(35.5,-3.2,0.823,0.823);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.star2}]}).wait(4));

	// Layer 1
	this.star1 = new lib.sprite65();
	this.star1.setTransform(-3.3,-3.2,0.823,0.823);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.star1}]}).wait(4));
  this.timeline.addTween(cjs.Tween.get(this).call(this.frame1).wait(3).call(this.frame4))
}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,109.5,30.1);


(lib.sprite46 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});
  this.frame1 = function(){this.stop()}
  this.frame4 = function(){this.stop()}
	// Layer 11
	this.instance = new lib.shape48("synched",0);

	this.instance_1 = new lib.sprite50();
	this.instance_1.setTransform(15.4,-84.2,1,1,15);

	this.instance_2 = new lib.shape55("synched",0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[]},1).to({state:[{t:this.instance_2}]},1).wait(1));

	// Layer 10
	this.arm = new lib.sprite42();
	this.arm.setTransform(18.6,-45.7,0.997,0.997,73.9);

	this.arm_1 = new lib.sprite52();
	this.arm_1.setTransform(20.5,-37.5,0.996,0.996,75.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.arm,p:{scaleX:0.997,scaleY:0.997,rotation:73.9,x:18.6,y:-45.7}}]}).to({state:[{t:this.arm,p:{scaleX:0.996,scaleY:0.996,rotation:83.7,x:17.2,y:-36.7}}]},1).to({state:[{t:this.arm,p:{scaleX:0.996,scaleY:0.996,rotation:98.7,x:17.8,y:-26}}]},1).to({state:[{t:this.arm_1}]},1).wait(1));

	// Layer 9
	this.leg = new lib.sprite40();
	this.leg.setTransform(-23.2,-15.2,0.997,0.997,61.1);

	this.timeline.addTween(cjs.Tween.get(this.leg).wait(1).to({scaleX:1,scaleY:1,rotation:47.3,x:-19.9,y:-5.8},0).wait(1).to({scaleX:1,scaleY:1,rotation:39.4,y:0.5},0).wait(1).to({rotation:20.5,x:-20,y:-4.6},0).wait(1));

	// Layer 8
	this.thigh = new lib.sprite27();
	this.thigh.setTransform(-14.2,-11.1,0.999,0.999,27);

	this.timeline.addTween(cjs.Tween.get(this.thigh).wait(1).to({rotation:12,x:-10.3,y:-4},0).wait(1).to({y:2.4},0).wait(1).to({y:-3.5},0).wait(1));

	// Layer 7
	this.instance_3 = new lib.shape54("synched",0);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(3).to({startPosition:0,_off:false},0).wait(1));

	// Layer 6
	this.instance_4 = new lib.shape47("synched",0);

	this.eyes = new lib.sprite50();
	this.eyes.setTransform(8.1,-77.2,0.997,0.997,16.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4}]}).to({state:[]},1).to({state:[{t:this.eyes}]},1).to({state:[]},1).wait(1));

	// Layer 5
	this.instance_5 = new lib.shape49("synched",0);

	this.instance_6 = new lib.shape51("synched",0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_5}]},1).to({state:[{t:this.instance_6}]},1).to({state:[]},1).wait(1));

	// Layer 4
	this.arm_2 = new lib.sprite52();
	this.arm_2.setTransform(18.1,-40,0.997,0.997,103.9);
	this.arm_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.arm_2).wait(3).to({_off:false},0).wait(1));

	// Layer 3
	this.leg2 = new lib.sprite29();
	this.leg2.setTransform(-25.6,-19.1,0.997,0.997,65.2);

	this.timeline.addTween(cjs.Tween.get(this.leg2).to({scaleX:1,scaleY:1,rotation:49.4,x:-25.4,y:-12.8},1).wait(1).to({scaleX:1,scaleY:1,rotation:33.6,x:-25.3,y:-6.7},0).wait(1).to({rotation:17.1,y:-12.7},0).wait(1));

	// Layer 2
	this.thigh2 = new lib.sprite27();
	this.thigh2.setTransform(-16.2,-16.2,0.999,0.999,12);

	this.timeline.addTween(cjs.Tween.get(this.thigh2).to({y:-10.6},1).wait(1).to({y:-5.1},0).wait(1).to({y:-11.1},0).wait(1));

	// Layer 1
	this.arm2 = new lib.sprite22();
	this.arm2.setTransform(-4.8,-54.4,0.995,0.995,11.5);

	this.timeline.addTween(cjs.Tween.get(this.arm2).wait(1).to({scaleX:0.99,scaleY:0.99,rotation:21.1,x:-6.3,y:-43.8},0).wait(1).to({rotation:6.1,x:-10.8,y:-36.4},0).to({_off:true},1).wait(1));
  this.timeline.addTween(cjs.Tween.get(this).call(this.frame1).wait(3).call(this.frame4))
}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69.2,-104.7,154.9,103.7);


(lib.sprite8 = function() {
	this.initialize();
  var self = this;
	// Layer 8
	this.scoreClip = new lib.sprite57();
	this.scoreClip.setTransform(145.5,400.8);

	// Layer 7
	this.instance = new lib.shape56("synched",0);

	// Layer 6
	this._char = new lib.sprite46();
	this._char.setTransform(253,501);

	// Layer 5
	this.groundShadow = new lib.sprite44();
	this.groundShadow.setTransform(254,317,1,1.002);

	// Layer 4
	this.swing = new lib.sprite21();
	this.swing.setTransform(250,65,0.996,0.996);
  
  
	// Layer 3
	this.starLine = new lib.sprite13();
  this.starLine.setTransform(-14,257.95);

	// Layer 2
	this.bg = new lib.sprite9();
	this.bg.setTransform(-2156.9,-90.9);

	// Layer 1
	this.bgVector = new lib.sprite9();
	this.bgVector.setTransform(-2156.9,-90.9);

	this.addChild(this.bgVector,this.bg,this.starLine,this.swing,this.groundShadow,this._char,this.instance,this.scoreClip);
	
  var char_yahoo = playSound("sound1yahoowav"); char_yahoo.stop();
  var char_ground = playSound("sound4hitGroundwav"); char_ground.stop();
  var sndSwingBack = playSound("sound3swingBackwav"); sndSwingBack.stop();
  sndSwingBack.volume = 0.5;
  var sndSwingForward = playSound("sound2swingForwardwav");sndSwingForward.stop();
  sndSwingForward.volume = 0.5;
  //var bgBitmap = new flash.display.BitmapData(2836, 437, true, 0);
  //bg.attachBitmap(bgBitmap, bg.getNextHighestDepth());
  //bgBitmap.draw(bgVector);
  this.bgVector.visible = false;
  var score = 0;
  var swingSndCount = 1;
  
  this.init = function(){  
  
  this._char.gotoAndStop(0);
  this._char.setTransform(253,501);
  
  this.groundShadow.setTransform(254,317,1,1.002);
  
  this.swing.rotation = 0;
  	
	this.swing.arm.setTransform(0,154, 1, 1, 0);
	
	this.swing.leg.setTransform(-26.5,197.3, 1, 1, 0);
    
	this.swing.thigh.setTransform(-16.8,196.4, 1, 1, 0);

	this.swing.bicep.setTransform(-0.2,153.6,1.004,1.005, 0);
	
	this.swing.body.setTransform(2.5,202, 1, 1, 0);
	
	this.swing.leg2.setTransform(-33.4,190.5, 1, 1, 0);
	
	this.swing.thigh2.setTransform(-24.1,190.1, 1, 1, 0);

	this.swing.seat.setTransform(0,206.8, 1, 1, 0);

	this.swing.arm2.setTransform(-14.9,155.5, 1, 1, 0);
	
	this.swing.body.visible = this.swing.arm.visible = this.swing.bicep.visible = this.swing.arm2.visible = this.swing.leg.visible = this.swing.leg2.visible = this.swing.thigh.visible = this.swing.thigh2.visible = true;
  
  var accel = 0;
  var vel = 0;
  var velMax = 20;
  var damp = 0.980000;
  var dir;
  var push = 0;
  var pushMax = 1;
  var pushStep = 0.020000;
  var swingLength = 206;
  var jumping = false;
  var gravity = 1.500000;
  var velDir = "right";
  stage.removeAllEventListeners("stagemousedown");
  stage.on("stagemousedown",  function (evt)
  {
    evt.remove(); //delete onMouseDown;
    char_yahoo.play();
    jumping = true;
    self.swing.body.visible = self.swing.arm.visible = self.swing.bicep.visible = self.swing.arm2.visible = self.swing.leg.visible = self.swing.leg2.visible = self.swing.thigh.visible = self.swing.thigh2.visible = false;
    self._char.x = self.charX;
    self._char.y = self.charY;
    self._char.rotation = self.swing.rotation;
    rad = 1.570796 - radians;
    velX = -3 * vel * Math.cos(rad);
    velY = 3 * vel * Math.sin(rad);
    if (velX > 0)
    {
      self.parent.removeAllEventListeners();    // delete _parent.onEnterFrame;
    } // end if
    self._char.on("tick", function (e)
    {
        velY = velY + gravity;
        self._char.x = self.charX = self.charX + velX;
        self._char.y = self._char.y + velY;
        self._char.rotation = self._char.rotation + (-self._char.rotation / 4);
        self.groundShadow.x = self._char.x;
        if (self._char.y + velY >= self.groundShadow.y)
        {
            char_yahoo.stop();
            char_ground.play();
            self._char.y = self.groundShadow.y;
            self._char.play();
            self._char.y = self.groundShadow.y;
            e.remove();   //delete this.onEnterFrame;
            score = Math.round(100 * (44 - self._char.x) / 2000);
            if (score < 0)
            {
                score = 0;
            } // end if
            if (self._char.x > self.starLine.x)
            {
                self.parent.gotoAndPlay("reset");
            }
            else
            {
                self.parent.starPoints.score();
            } // end if
        } // end else if
    });
  });
  this.removeAllEventListeners("tick");
  this.on("tick", function ()
  {
    ++swingSndCount;
    if (Math.random() * 100 < 1)
    {
        self.swing.body.head.eyes.play();
    } // end if
    pushStep = Math.abs(self.swing.rotation / 1200) + 0.020000;
    accel = -self.swing.rotation / 20 + push;
    if (Math.abs(vel + accel) < velMax)
    {
        vel = vel + accel;
    } // end if
    vel = vel * damp;
    self.swing.rotation = self.swing.rotation + vel;
    if (vel >= 0)
    {
        if (vel > 0)
        {
            if (velDir == "right" && !jumping)
            {
                sndSwingForward.play();
            } // end if
            velDir = "left";
        } // end if
    }
    else
    {
        if (velDir == "left" && !jumping)
        {
            sndSwingBack.play();
        } // end if
        velDir = "right";
    } // end else if
    if (!jumping)
    {
        radians = 3.141593 * (self.swing.rotation + 90) / 180;
        self.charX = self.groundShadow.x = self.swing.x + swingLength * Math.cos(radians);
        self.charY = self.swing.y + swingLength * Math.sin(radians);
    } // end if
    if (!(self.swing.rotation <= 0 && !jumping))
    {
        if (self.swing.rotation > 0 && !jumping)
        {
            push = push - pushStep;
        } // end if
    }
    else
    {
        push = push + pushStep;
    } // end else if
    if (jumping)
    {
        self.swing.arm.x = self.swing.arm2.x = 0;
    }
    else
    {
        self.swing.leg.rotation = self.swing.leg.rotation + (160 * push - self.swing.leg.rotation) / 1;
        self.swing.leg2.rotation = self.swing.leg2.rotation + (160 * push - self.swing.leg2.rotation) / 1;
        self.swing.body.rotation = self.swing.body.rotation + (60 * push - self.swing.body.rotation) / 2;
        self.swing.body.head.rotation = self.swing.body.rotation;
        self.swing.arm.rotation = self.swing.arm.rotation + (20 * push - self.swing.arm.rotation) / 4;
        self.swing.arm.x = self.swing.bicep.x = self.swing.bicep.x + (80 * push - self.swing.arm.x) / 4;
        self.swing.arm.y = self.swing.bicep.y = Math.abs(self.swing.arm.x) / 2 + 155;
        self.swing.arm2.rotation = self.swing.arm2.rotation + (20 * push - self.swing.arm2.rotation) / 4;
        self.swing.arm2.x = self.swing.arm2.x + (80 * push - 15 - self.swing.arm2.x) / 4;
        self.swing.arm2.y = Math.abs(self.swing.arm.x) / 2 + 155;
    } // end else if
  });	
	}
	
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2156.9,-90.9,2836.2,590.9);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;