(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.TurtleWax = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{reset:2});
  this.frame1 = function(){
   //loadMovie("/flash/GameController.swf", "GameEndClip");
   this.GameWon = false;  
  }
  this.frame2 = function(){
   this.stop ();
   this.camera.target.x = -250 - this.starPoints.currentFrame * 200; 
   this.camera.init()
  }
  this.frame31 = function(){this.gotoAndStop(1)}
	// Layer 5
	this.instance = new lib.sprite49();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).wait(31));

	// Layer 4
	this.instance_1 = new lib.shape48("synched",0);
	this.instance_1.setTransform(437,21.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).wait(31));

	// Layer 3
	this.starPoints = new lib.sprite38();
	this.starPoints.setTransform(28.1,26);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.starPoints}]}).wait(31));

	// Layer 2
	this.camera = new lib.sprite10();

	this.timeline.addTween(cjs.Tween.get(this.camera).to({_off:true},30).wait(1));

	// Layer 1
	this.instance_2 = new lib.shape9("synched",0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).wait(31));
  this.timeline.addTween(cjs.Tween.get(this).call(this.frame1).wait(1).call(this.frame2).wait(29).call(this.frame31))
}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1087.8,-57.9,1613.9,460.3);


// symbols:
(lib.image47 = function() {
	this.initialize(img.image47);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,90,15);


(lib.sprite51 = function() {
	this.initialize();

}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


(lib.sprite30 = function() {
	this.initialize();

	// Layer 1
	this.scoreFld = new cjs.Text("0", "30px Arial", "#FFFFFF");
	this.scoreFld.lineHeight = 30;
	this.scoreFld.lineWidth = 87;
	this.scoreFld.setTransform(-45.3,-19.4);

	this.addChild(this.scoreFld);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-45.3,-19.4,90.9,38.9);


(lib.sprite21 = function() {
	this.initialize();

}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


(lib.text28 = function() {
	this.initialize();

	// Layer 1
	this.text = new cjs.Text("WHEEE!", "15px Arial");
	this.text.lineHeight = 15;
	this.text.lineWidth = 63;
	this.text.setTransform(-3.9,-3.4);

	this.addChild(this.text);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-3.9,-3.4,67.1,37.6);


(lib.shape50 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#4E84DC").ss(2,1,1).p("EAnEAaQMhOHAAAMAAAg0fMBOHAAAg");
	this.shape.setTransform(250,168);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,500,336);


(lib.shape48 = function() {
	this.initialize();

	// Layer 1
	this.shape = new lib.image47(); 
	this.shape.setTransform(-45, -7.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-44.9,-7.4,90,15);


(lib.shape45 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(0,0,0,0.2)").ss(4,0,1).p("AC7ggIhVBCQgGAGgDAJQgDAJACAIIAcBqQACAIgEACIgKgCIhcg7QgGgEgKAAIgPAEIhcA7IgKACQgEgCACgIIAdhqQACgIgDgJQgDgJgHgGIhVhCQgGgGABgEQACgEAIAAIBtgGQAIAAAIgGQAIgGADgIIAnhmQADgHADAAQAEAAADAHIAnBmQADAIAIAGQAIAGAIAAIBtAGQAIAAACAEQABAEgGAGg");
	this.shape.setTransform(0,1.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.2,-17,38.5,36.6);


(lib.shape44 = function() {
	this.initialize();

	// Layer 6
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.753)"],[0,1],5.3,-0.1,-4.3,-2.6).s().p("Ag2gRIBtAEIgGAfg");
	this.shape.setTransform(-8.8,-1.3);

	// Layer 5
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.753)"],[0,1],1.3,-4.5,-3.6,4).s().p("AABg0IAeAQIg9BZg");
	this.shape_1.setTransform(-5.5,7.9);

	// Layer 4
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.753)"],[0,1],-2.4,-3.8,2.3,4.9).s().p("AgkggIAdgRIAsBkg");
	this.shape_2.setTransform(5.5,8.4);

	// Layer 3
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.753)"],[0,1],-5,0.5,4.8,-0.3).s().p("Ag2gPQA2AAA3gBIhpAhg");
	this.shape_3.setTransform(8.6,-1.3);

	// Layer 2
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.753)"],[0,1],0.4,5.4,0.9,-4.4).s().p("AgPA2IANhsIATBtg");
	this.shape_4.setTransform(0.3,-8.5);

	// Layer 1
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.rf(["#FFEF24","#FCCA01"],[0,1],0,0,0,0,0,21.8).s().p("ABsC0Ihcg7QgGgEgKAAIgPAEIhcA7IgKACQgEgCACgIIAdhqQACgIgDgJQgDgJgHgGIhVhCQgGgGABgEQACgEAIAAIBtgGQAIAAAIgGQAIgGADgIIAnhmQADgHADAAQAEAAADAHIAnBmQADAIAIAGQAIAGAIAAIBtAGQAIAAACAEQABAEgGAGIhVBCQgGAGgDAJQgDAJACAIIAcBqQACAIgEACg");

	this.addChild(this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,38.5,36.6);


(lib.shape41 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(2,0,1).p("AC7ggIhVBCQgGAGgDAJQgDAJACAIIAcBqQACAIgEACIgKgCIhcg7QgGgEgKAAIgPAEIhcA7IgKACQgEgCACgIIAdhqQACgIgDgJQgDgJgHgGIhVhCQgGgGABgEQACgEAIAAIBtgGQAIAAAIgGQAIgGADgIIAnhmQADgHADAAQAEAAADAHIAnBmQADAIAIAGQAIAGAIAAIBtAGQAIAAACAEQABAEgGAGg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0)").s().p("ABsC0Ihcg7QgGgEgKAAIgPAEIhcA7IgKACQgEgCACgIIAdhqQACgIgDgJQgDgJgHgGIhVhCQgGgGABgEQACgEAIAAIBtgGQAIAAAIgGQAIgGADgIIAnhmQADgHADAAQAEAAADAHIAnBmQADAIAIAGQAIAGAIAAIBtAGQAIAAACAEQABAEgGAGIhVBCQgGAGgDAJQgDAJACAIIAcBqQACAIgEACg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,38.5,36.6);


(lib.shape37 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("ACwjSIAAGlIiOgoIAAB4IjRkjIDRkiIAAB4g");
	this.shape.setTransform(7.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCC00").s().p("AivAAIDRkiIAAB4ICNgoIAAGlIiNgoIAAB4g");
	this.shape_1.setTransform(7.1,0);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10.4,-29,35.2,58.3);


(lib.shape34 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhYBaIBYizIBZCzg");
	this.shape.setTransform(0,-6.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.9,-16,18,18.1);


(lib.shape27 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AEtkSQB9BUAAB4QAAB2h9BUQh9BUiwAAIh2gKIAEABQiRA9gHBbQgxhqAkhsIgVgNQh9hUAAh2QAAh4B9hUQB9hUCvAAQCwAAB9BUg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AkWCRIgWgNQh8hVAAh1QAAh4B8hUQB9hUCvAAQCwAAB8BUQB+BUgBB4QABB1h+BVQh8BUiwAAIh1gKIADABQiRA9gHBbQgwhqAkhsg");

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-42.5,-35.9,85.2,71.9);


(lib.shape24 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#006600").ss(1,1,1).p("ACuAAIgDAIIgJAQAC/A1QgJAEgHAGIgEADIgIAIIgBABQgMAOgBAUAA9ABIgFAEIgEAEQgEAIADAJIABACQAIAQARABIAFAAIAVAAIAJgBIACAAIAUgFIANgFIAEgCIALgIAi+hdQAQgMARgDIAVAAIANADQAPAFAIARQAGALgEAMIgDAIQgJAPgOAOIgVAVAhzAXQALgSAQgJIAZgNIAIgCIAhgDIAIABIABAAAgBgPIAIAIQANAKAEAOIAAAEIABAKQABALgEAKIAAABQgEANgHAKIgHAMABZBrIAAgIQABgQAOgKQAOgLATgDIANgBQAKABALAH");
	this.shape.setTransform(-15.5,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#205111").ss(1,1,1).p("AEigWIgQAUQgNALgOAJIAAABIgNAJIgJAGIgKAEIggAPIgMAFIgUAHIgBAAIgMADIgPAEIgkAGIgIABIgDAAIgBAAIgOACIgJAAIgJABIgdABIgIAAIgMAAIgIAAIgVgBIAAAAIgBAAIgLgCQgcgFgagLIgBgBIgLgFIgBAAQgWgLgRgQIgKgIIgIgIIgZgbQgMgPgHgRQgIgRgBgPQgBgRAEgPIAGgUIAEgKQAGgOARgKIADgIIALgTQgSAEgOAIIgeAWIgCABIgUAVIgFAFIgSAdIgDAHIAAABIgBACIgHAfIAAAhIACANIAAACQAJAtAjAoIABACIAeAbIAiAZIAzAaIACABIAPAGIACABIARAGIASAFIADABIANAEIAFABIAuAIIAHAAIAzACIALAAIAdgDIAdgFIAkgKIASgGQAQgHAPgJIANgJQAagTARgXAEQgTIASgDAEfAbQAFgQABgL");
	this.shape_1.setTransform(-5.6,-7.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#006200").ss(1,1,1).p("AA8BlQABATARAHIALAEIACgBQAJgFALgDIADAAIALgCIAfgBADWCKIgPgLIgSgFIgTgDIgGAAIAQgJIAQgNQANgJAEgJAEmgaIgCALAkEiJQAWgDAEAXQADAQgJAQQgIAOgMANIgCADQgMAOgTAM");
	this.shape_2.setTransform(-5.4,-7.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#0B3E0B").ss(1,1,1).p("AgkgsIABAAAA2geIgDgFABWApIgHABACphsIgfARIgVAPIAgAGIAKAGIAWANIAPAPIAJANIADAFIgaAFIgRACIgRABIgJAAIgYgFQgTgHAAgSQABgPAMgOIAIgHAhhh5IALADAiTgpIgBAAIAAgBAkEghIgBgCAi5B7IAAAAAEXgtIgdANIgCABIgYAHIgJADIgHADAjbh6IgBABIgDACAkWB0IACABIACAA");
	this.shape_3.setTransform(15.4,-14.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#8F7725").ss(1,1,1).p("ACEhjIgHgDIgjgMIgDAAIACACIAVAXIASAeIACACQAGANAAAEIgBAAIgagDIgFgBIgFgBIgIAAIgeABIgHABIgdAGIAOAgIAAABIAHAgIADAkIABAIIAAACIgBAbIgCAVIgaADIgfACACJgoIAFACIAOgBIAWABIAKACIAZAFIAPAFADhgfIgDgDIgDgEIgDgEIgJgJIgSgPIgBgBIgcgRIgDgCIgZgNAgdh6IANgCIAGgBIAcgCIAlAFIAUAFAAYgmQgCgMgIgPIgSgfQgLgQgOgKACfBdIACgZIAAgGIgDgkIAAgFIgGgdIgJgVIgGgLAAYglIAAAAIgfgEIgmACIgkAJIgEABAhWgfIgBABIgJgBIgIAAIgcABIgMABIgYAFQgSADgQAJIgIAEIgbAOIAGAOQAJAQANAOIALAMAhHALIABgCIgCgJIgNgdAgLB/IgHAAIgYABIgDAAIgEAAIgBAAIAAgCIABgDIgCgPAhoB4IgDgBIgVgGQgOgFgNgLIgZgTIgDgDIgDgDIgMgKAAvB6IAEgBIAJgCIAWgGIAMgCIAigIIAfgKIABgBIAPgGIARgJQAEgBADgDIAYgPIAMgKIABgBQAFgKABgOQABgQgFgPIgKgSAgsh2IAPgEAhvhOIATAgIABADIAFAMAjfhaIACgKAjmg+QACgEAFgYAjtAGIgEgQQgCgRAFgQQACgKAGgJAhkB5IATAEIAfAD");
	this.shape_4.setTransform(-1.9,-14.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#296916").ss(1,1,1).p("AhvhkIAQgiQAIgOANgNIAFgFIAagUQAQgJATgDIAhADQARAGAFAPQAFAOgJAPQgKAPgRAKIgfASIgCABIgfAPIgHAFACIhyIgJgUQgFgRAEgRIADgIQAKgQAQgDIASgBIAPAAIAgABIAhABIAhAAQARABAQAGQAPAEAPAMIAbAZIAWAZIACACIAAABQALAOAEARIAEAgQABASgGAPQgGAPgVAQQgOAKgNAGIggAOQgQAGgQADIgjAGIgjADIgkADIgTAAIgHgBIgJgBIgkAAIghACIgDAAIgMADAAJB0IAIAAIANgBIANAAIATAAIATgBIAlADIAjAFIAgAIQATAGAFARQAGAQgQALQgPAMgQADIgiAEIgmgCIgBgBIgjgFIgagFIgJgDIgfgJIgKgEQgKgFgKgHIgQgMACIhyIAHALIAMAQIAMAPQANANAPALIAQALIAPAFIATAGIAKABIAKACIAHABAAkgOQAFgXAIgPQAIgQARgJQAPgHAQgJIAfgVAmDBQIAagYIAOgHIAigLIAjgIIATgBIACAAIAOgBIAIAAIAbAFQAMADAIAJIAHAIQAHALgCANQgBAIgGAIQgFAFgGAFIAAABIgCABQgOAKgPAGIgPAFIgHADIgDABIgJADIghAFAmOhmIACgDIAZgbIAEgDIAZgUIAigQIAigLIAhACQAPAFALASIAAABQAIANgHAQQgFAOgOAMAjthhQgOAMgOAIQgPAKgRAGIgDABAmjgsIA2gEIAigEIAagFIAFgD");
	this.shape_5.setTransform(16.8,-16.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#4E7B40").s().p("AAiCgIgGAAIAAgIQABgQAOgKQAOgLATgDIAMgBQALABALAHIgIAIIgBABQgNAOgBAUgABlCAIABgBIAIgIIAEgDQAHgGAJgEIgLgDQgSgIAAgSIAJgQIADgKIABAAIADAAIAIgBIAkgGIAPgEIAMgDIABAAIAUgHIAQANIAVALQgFAJgMAKIgRAMIgQAJIAGAAIATADIASAGIAQAKIgOAJQgOAJgQAHIgTAGIgkAKIgdAFIgdADIgLAAQABgUANgOgACDBpIgBABIABgBQAKgFAKgCIAEAAIAKgCIAfgCIgfACIgKACIgEAAQgKACgKAFgAhJCHIgBgBIgQgGIgCgBIgygaIgigZQALgSAQgLIAYgNIAIgCIAhgDIAJABIABAAIAKAFIACABIAKAIQANAMADAOIABAEIABAKQAAALgDAKIAAABQgEANgHAKIgHAMgAAVBiIgFAAQgQgBgHgQIgBgCQgDgJAEgIIAEgEIADgEIABAAIABAAIAVABIAHAAIAOAAIAIAAIAegBIAIgBIAJAAIAOgCIgDAKIgJAQIgLAIIgEACIgNAFIgVAFIgBAAIgJABgAjQAvQgjgogJgtIABgCQAQgMAQgDIAVAAIAOADQAOAFAJARQAFALgDAMIgEAHQgIAOgOAOIgVAVgAj+hWIAIgfIAAgCIAAgBIADgHIATgdIAFgFQAVgEAFAXQACARgJAQQgIANgLAOIgDACQgMAOgTANg");
	this.shape_6.setTransform(-9.4,-5.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#116214").s().p("Ag1C1IgGgBIgNgEIgCgBIgSgFIAHgMQAHgKAEgNIAAgBQADgKAAgLIgBgKIgBgEQgDgOgNgMIgKgIQAaALAbAFIALACIgFAEIgEAEQgEAIADAJIABACQAIAQARABIAFAAIATAAIAJgBIABAAIAVgFIANgFIAEgCIALgIQAAASASAIIALADQgJAEgHAGIgEADQgLgHgLgBIgMABQgTADgOALQgMAKgBAQIAAAIgADKCEIgSgGIgTgDIgGAAIAQgJIARgMQAMgKAFgJIAKAEIAgAKIAKADQgSAXgZATgAjzBOIAVgVQAOgOAIgPIAEgIQADgMgFgJQgJgRgOgFIgOgDIgVAAQgQADgQAMIgCgNQATgNAMgOIADgCQALgOAIgNQAJgQgCgRQgFgXgVAEIAUgVIABgBIAfgWQANgIATgEIgLATIgDAIQgSAKgGAOIgDAKIgGAUQgEANAAAPIABAEQABAPAIARQAHARAMAPIAZAbIAIAIIAJAIQARAQAXALIABAAIgBAAIgJgBIghADIgIACIgYANQgQALgLASgAAHBUIgMAAIgHAAIgVgBIgBAAIgBAAIgLgCQgbgFgagLIgCgBIgKgFIgBAAQgXgLgRgQIgJgIIgIgIIgZgbQgMgPgHgRQgIgRgBgPIgBgEQAAgPAEgNIAGgUIADgKQAGgOASgKIABACQgFAYgDAFQgFAJgDAKQgEAQACAQIAEATIAGAOQAJAQAMANIAMAMIAMAJIADADIADACIAYAUQANAKAOAGIAWAGIADABIACABIACAAIATAEIAfADIABgBIAEAAIADAAIAWAAIAHAAIAAgBIAhgBIAbgEIADgBIAJgCIAXgFIAMgDIAigIIAegKIACgBIAOgGIARgIIAIgEIAYgOIAMgJIASgDIgQAUQgNALgNAJIgBABIgNAJIgJAGIgJAEIghAPIgMAFIgUAHIgBAAIgMADIgPAEIgkAGIgIABIgDAAIgBAAIgOACIgJAAIgIABIgeABgAhjBBIAAAAg");
	this.shape_7.setTransform(-5.7,-8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#CF1010").s().p("AgLAhIgYgGQgTgHAAgSQABgNAMgOIAIgHIAgAGIAIAGIAVANIAQAOIAJAMIACAFIgZAFIgSACIgOACg");
	this.shape_8.setTransform(30.6,-18.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006600").s().p("AAGAoIgHgNIgPgQIgVgLIgLgGIgfgFIAUgPIAfgSIANAPQAMANANALIARAJIAPAFIASAGIALABIAJACIgdANIgCABIgYAHIgJADIgHACg");
	this.shape_9.setTransform(35.3,-21);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgBAiQgHgDAAgFQABgFAHgEIAPgEIARADQAIADgBAFQAAAEgIAEIgRAEgAgmgSQAAgFAGgFQAGgEAJgCQAJgCAGACQAFABAAADQABAGgEAEQgHAEgJACIgPABQgHgBAAgEg");
	this.shape_10.setTransform(45.5,-27.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#D9C867").s().p("AhRB9IgTgEIgCAAIgCgBIAhgFIAJgDIADgBIAIgDIACAPIgBADIAAACgAgyB+IABgDIgCgPIAPgFQAOgGAOgKIACgBIABgBIAIgKQAGgIABgIQADgNgHgLIgGgIQgIgJgLgDIgcgFIgIAAIgOABIgCAAIABgCIgCgJIgNgdIAEgBIAkgJIAmgCIAfAEIAAAAIAAAAIgfgEIgmACIgkAJIgEABIgBgCIgFgMIgBgDIgTggIATAgIABADIAFAMIgBABIgJgBIgIAAIgcABIgMABIgYAFQgSADgQAJIgIAEIgbAOIgEgQQgCgRAFgQQACgKAGgJIA2gEIAigDIAZgGIAGgDIADgBQARgGAOgKQAOgIAPgMIADgCIABgBIAPgEQAOAKALAQIASAfQAIAPACAMIAAABIABAAIAOAgIAAABIAHAgIADAkIABAIIAAACIgBAbIgCAVIgaADIgfACIgBAAIgHAAIgYABIgDAAIgEAAIgBAAgAAxBlIABgbIAAgCIgBgIIgDgkIgHggIAAgBIgOggIAdgGIAHgBIAegBIAIAAIAFABIAFABIAaADIABAAQAAgEgGgNIgCgCIgSgeIgVgXIABgCIAjAMIAHADIAZANIADACIAcARIABABIASAPIAJAJIADAEIADAEIADADIADAFIgPgFIgZgFIgKgCIgWgBIgOABIgFgCIgBAAIABAAIAFACIAOgBIAWABIAKACIAZAFIAPAFIAKASQAFAPgBAQQgBAOgFAKIgBABIgMAKIgYAPIgHAEIgRAJIgPAGIgBABIACgZIAAgGIgDgkIAAgFIgGgdIgJgVIgGgLIAGALIAJAVIAGAdIAAAFIADAkIAAAGIgCAZIgfAKIgiAIIgMACIgWAGIgJACIgEABgAgzBsgAjRAyQgNgOgJgQIgGgOIAbgOIAIgEQAQgJASgDIAYgFIAMgBIAcgBIAIAAIAJABIABgBIABACIANAdIACAJIgBACIgTACIgjAHIghALIgOAHIgaAYgAhVgdgAhWgfgAAZglgAAYglIAAgBQgCgMgIgPIgSgfQgLgQgOgKIANgCIAGgBIAcgCIAlAFIAUAFIAMADIACACIAVAXIASAeIACACQAGANAAAEIgBAAIgagDIgFgBIgFgBIgIAAIgeABIgHABIgdAGgACIgog");
	this.shape_11.setTransform(-1.9,-14.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#39A925").s().p("ABgDFIgBgBIgjgFIgagFIgJgDIgfgKIgKgDIgUgMIgQgNIAMgFIAggOIAIgFIAJgFIAIAAIANgBIANAAIATAAIATgBIAlADIAjAEIAgAIQATAHAFARQAGAQgQALQgPAMgQADIgiADgAkoCJIgVgGQgOgFgNgLIgYgTIgDgDIgEgDIgMgKIAagYIAOgHIAigLIAjgIIATgCIACAAIAOgBIAIABIAbAFQAMADAIAJIAHAIQAHAKgCANQgBAJgGAIIgLAJIAAABIgCACQgOAKgPAFIgPAGIgHACIgDABIgJAEIghAFgAAvBBQAGgLAAgOQACgPgGgRIgJgQIgEgGQAFgWAIgQQAIgQARgJIAfgQIAfgVIgJgUQgFgRAEgRIADgIQAKgQAQgDIASgBIAPAAIAgABIAhABIAhAAQARABAQAGQAPAFAPALIAbAZIAWAZIACADIAAAAQALAPAEAPIAEAhQABARgGAPQgGAQgVAQQgOAJgNAIIggANQgQAGgQADIgjAGIgjADIgkADIgTAAIgHgBIgJgBIgkgBIghADIgDAAIgMADIgGAAIgSADgAB8hFIgVAPIgIAHQgMAOgBAPQAAASATAFIAYAFIAJAAIAQgBIASgCIAZgGIAIgBIAJgCIAXgHIACgBIAegNIgKgCIgKgBIgTgGIgPgFIgQgLQgPgLgNgNIgMgPgAEQgWIgHgBgAEdhZQgHAEgBAFQAAAFAHADIARACIARgEQAIgEAAgEQABgFgIgDIgRgDgACPhnIAMAQIgMgQIgHgLgAEMiOQgJACgGAEQgGAFAAAFQAAAEAHABIAPgBQAJgCAHgEQAGgEgBgGQAAgDgHgBIgHgBIgIABgAmbhIIACgKIALgUIACgDIAZgbIAEgDIAZgTIAigRIAigLIAhACQAPAFALASIAAABQAIANgHAQQgFAOgOANIgBABIgDACQgOAMgOAIQgPAJgRAHIgDABIgFACIgaAGIgiAEIg2AEQADgFAFgXgAg+hUIgigMIgEgBIgLgCIAQgiQAIgPANgNIAFgFIAagUQAQgJATgCIAhACQARAHAFAOQAFAOgJAPQgKAPgRAKIgfASIgCACIgfAOIgHAFg");
	this.shape_12.setTransform(16.8,-16.7);

	this.addChild(this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-34.9,-36.6,93.8,47.7);


(lib.shape23 = function() {
	this.initialize();

	// Layer 4
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#296916").ss(1,1,1).p("AAmgzIgLAAIgWADIgWADIgbAJQgTAIgBACQgcAQgEAOIAAACQgJALAMAMIAEAFQAVAMAcAGIADAAIABAAIAigCIAGgCIAPgCQgCgCADABIAEgBIACgBIAagHIAEgBIABgBIAFgDIAGgBIAEgCIAKgFIAIgEIAFgDIAAgBIABAAIABAAIAAAAIAEgC");
	this.shape.setTransform(-30.4,-5.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#39A925").s().p("AglA0IgDAAQgcgGgVgMIgEgFQgMgMAJgLIAAgCQAEgOAcgQQABgCATgIIAbgJIAWgDIAWgDIALAAIAfAqIAeAVIACABIgEACIAAAAIgBAAIgBAAIAAABIgFADIgIAEIgKAFIgEACIgGABIgFADIgBABIgEABIgaAHIgCABIgEABQAAAAgBAAQAAAAAAAAQgBAAAAAAQABAAAAABIgPACIgGACIgiACg");
	this.shape_1.setTransform(-30.4,-5.6);

	// Layer 3
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#296916").ss(1,1,1).p("ABUAeIgCgEQgCgLgNgPIgBgBIAAgBIgKgLIgEgDIgWgUIgJgFIgBgBIgRgIIgTgHIgMgHIAAAAIgcACQgNAFgKASIAAABQgHANAGAQIAKAQIAGAGQAFAFALAFIANAPQAPANAmAKIAZAE");
	this.shape_2.setTransform(-31.9,-28.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#39A925").s().p("AArBBIgZgEQgmgKgPgNIgNgQQgLgEgFgFIgGgGIgKgRQgGgPAHgOIAAAAQAKgSANgFIAcgCIAAAAIAMAHIATAHIARAIIABABIAJAFIAWATIAEAEIAKALIAAAAIABACQANAPACALIACAEIAAACIgXAMIgPAVg");
	this.shape_3.setTransform(-31.9,-28.3);

	// Layer 2
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#205111").ss(1,1,1).p("ADLgkIgLAJIAAAAIgEADIgBABIgJAGIgIAFIgKAFIggAMIgNAGIgUAGIAAABIgNADIgOAEIglAGIgIAAIgDABIgBAAIgOACIgHAAIgIABIgdABIgIABIgPAAIgHAAIgVgBIgBgBIgBAAIgKgCIgDAAIgRgEIgDgBIgOgEIgEgBIgNgGIgCgBIgFgCIgJgEIgagNIgEgE");
	this.shape_4.setTransform(0.2,-3.3);

	// Layer 1
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#205111").ss(1,1,1).p("AEngWIgFALIAAALIgCAYAEDBkQgRAXgaAUIgNAJIgfAPIgTAHIgkAKIgdAFIgdADIgKAAIgzgBIgGAAIgsgHAhaCtIgWgHIgQgHQgqgTgegWAjSBwIgJgIAjdBmIgBAAAjgBkIgUgUQgmgpgJgwAkjgLIgBgGIAAgBAkmgmIACgbIAGgUIABgDIADgIIASgcIAFgGIAKgKIAKgMIABgBQAPgMAPgJIAMgFIAIgDIANgEIBJgFAEdgOIgMANAEKAFIAHgGAjDicIgCACIAAABIgFAHIgOAUIgGAVIgCAJIgBAIIAAAPQABAQAIARIAMAVIAAAAAjKgQIAGAHIAYAbIAJAIIAJAJAiYAkIADADAi7ilIAAABIgBABIgBACIgGAFAkkgUIAAACAkkgVIgCgRAhaCtIAOAEIADAAIAKAE");
	this.shape_5.setTransform(-5.2,-8.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#8F7725").ss(1,1,1).p("AiJh8IBcAGIAEgBIALgDIANgCIAGgBIAcgCIAlAEIAgAIIAEABIAiAMIAHADIAaAMIADACIAcARIABABIARAPIAJAJIADAEIADAEIADADADkgbIgQgFIgYgFIgKgBIgXgCIgNABIgFgBIAGAKIAIAWIAHAcIAAAFIADAjIAAAIIgCAYIgfAKIgiAIIgMADIgWAFIgMADACgBbIAPgGIARgIIAIgEIAYgQQAGgEAJgOIADgSIAAgLIgBgFIgDgOIgKgSAAZglIAcgHIAIAAIAdgBIAJAAIAFABIAFAAIAaADIABAAIgGgQIgCgDIgSgeQgKgOgOgLAAYglIgggDIgmABQgRACgSAHIgEABQAIAQAEANIAGAMIACAGIABAAIAAAFQAMArABAuIACALIAAAEIgBABIACAAIADAAIADAAIAZAAIAHAAAgKB/IAfgCIADgBAAYB8IARgCIAHgBIACgUIAAgbIAAgCIgBgIQAAgSgEgSIgGggIgBgCIgNgfAAYgmQgDgMgIgPQgIgQgKgPQgKgQgPgKAilhyIAcgKIAsBPIACACIAEANAi3hsIASgGAgyCAIgdgCIgBgBIgBAAIgEgBIgDAAIgUgEQgSgEgIgEIgVgOIgZgUIgDgCIgDgDIgXgWQgNgOgJgQIgGgNIgEgSQgCgQAHgYQAIgYAtgiAhXgdIgJgCIgJAAIgbABIgMACIgYAEQgSAEgRAIIgIAFIgaAP");
	this.shape_6.setTransform(-1.7,-15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#296916").ss(1,1,1).p("ABRg1QAdgfANgXQAMgXAVgKIAYgNIgIgVQgGgQAEgRIACgJIAMgLQAFgFAIgCIACAAIASgCIAPAAIAgACIAMAAIAJAAIACABIAKgBIAgAAQASABAQAGQAPAEAPAMIAbAYIAWAZIACADIAAABIAKAPIAFAPQAFAQAAAQQABANgEAMIgDAIQgFAQgVARQgOAKgOAHIgfANIggAIIgjAFIgjAFIgkACIgTAAIgHgBIgJAAIgkgBIggACIgDABIgBAAIgHACIgFAAIgGACIgDABIgCAAIgKAAIAAABIgBAAIABgHAB2BLIAJAAIAkADIAjAEIAhAIQASAGAGARIABAHQABALgMAJIgJAGIgPAHIgHACIgjAEIglgCIgBAAIgkgFIgZgFIgKgDIgggKIgKgDAg4iHQgDgXAIgPIAVgbIAFgFIAZgTQAPgKATgDQATgDARAHQAQAFAFAPQAFAOgJAPQgKAPgRAKIghASIgCACIgdAPQgFABgBADADAiIIgEgGIgGgJIgCgCAEThGIgEgBQgIgDgHgEQgJgEgIgGQgPgKgNgOIgMgOIgDgFIgEgFAAPBIIABgBAgFg8IAAgBAh1g5IgBgBIAAAAIABAAgAiaBrIAAAAAh2BoIABAAAhnCAIgDAKQgDAJgHAHIACAJQAEALAMAGIAEABIAIACIABgBIAVgHIADgBIAKgCIAggBIAPgJIAOgNIASgSIgVgMQgHgEgHgIABFBMIAHAAIACAAIALgBIATAAIAAgBABUgwIgDgFABeAXIAAgBIABgCIAAgCABsBLIAKAAAE1g/IgJgCIgKgBIgPgEAE4g9IAFgBIgIgBAgTCrIAGAAIARADIARAFIAQAKAhgC8IAKgFAhhC9IABgBAiADvQABgUANgOIAAgBIAIgIQgKgHgLgBIgKAAIgDAAQgOADgMAHIgFAEIgCABQgHAGgEAHIgDANIAAAIAhqDEIAFgEIAEgDAjgCJIgBACIAAABIgCAJIABAHIABABIAAACQAGAMAMADIAAAAIACAAIAAABIACAAIACABIACgBIAEABIAVgBIAJgBIACAAIARgDIABgBIADgBIAMgFIABAAIADgCIAKgIAmeg2QACgFAAgFQgBgEgGgBQgCgMgKADQgCgGgFABAmeg1IAAgBIAAAAAnPASIAWgTIADgDQALgNAIgPQAGgKgBgLAm7AXIAGgCIAVAAIAOADQAOAFAJARQAFALgDALIAAABIgDAIQgJAPgOAOIgQAQAnQAgIAVgJAl9CJIACgBIALgLIABAAIAYgNIAIgDIAggDAjmgzIAAABIABABAjmgyIAAgBAj8CaIAAAAIgBgDIgBgEIgFgOIgHgIAj8CbIAAgBAj9CvQAAAEgBAEIgBAAIgHARAj9CvQABgHAAgHAkMDTIgCACAkMDTIACgEIAEgHAl/CMIACgDAmGCUIAHgI");
	this.shape_7.setTransform(12.6,-12.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#0B3E0B").ss(1,1,1).p("Ag0gnIgNAVQgBASAKAIIAVAPIATAKIAOAEIAcADIATgCIAGgBAA3AkIALgB");
	this.shape_8.setTransform(37.2,-22.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#000000").ss(1,1,1).p("AABAAIgBAA");
	this.shape_9.setTransform(42.6,-18.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#256116").s().p("AAEAlIgNgEIgSgKIgVgPQgLgIABgSIAOgUIADAEIAEAGIAMANQANAOANAIQAHAGAKAEQAHAFAIACIADABIAIAFIAPAHIgGAAIgUADg");
	this.shape_10.setTransform(36.4,-22.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#279526").s().p("ABrBPIABAAIAAgBQgCAKgGAIgABtBHQABgHAAgIIABADIAAAFQAAAEgCADIgBAHIABgHgAAAAQIADgCQAQgMAQgCIABAAIABAAIAKAAIAEAAIAIABIggAEIgIACIgXANgAhshNIgCgPIAAgDIADARIAAAAIAAADg");
	this.shape_11.setTransform(-23.7,-2.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgBAiQgHgEAAgFQAAgEAIgFQAFgDAKAAIARADQAIADgBAEQAAAFgIAEQgHAEgKAAgAgfgOQgHAAgBgFQAAgFAHgEQAGgFAJgCIAPAAIAFAGQAAAEgEAEQgGAFgJACIgIACIgHgCg");
	this.shape_12.setTransform(45.7,-27.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#116214").s().p("AgyC8IgCAAIBLg3IADAAIABgCIACgCIABgBIACgBIACgBIAMgFIAKgBIAHAAQADALANAGIAEABQABAEgDADIgBABIglgDIgDACIAAAAIgDAAQgPADgMAHIgDABIgBADIgCACQgGAFgDAHIgEAJIgBAHgAg3C7IgEgBIgCgBIgDgBIgKgDIgCAAIgOgEIgBgHIABgCIAEgFIAFgBIACgKIAGgMIADgOIgDgGIAAgCIgBgGIAAgBIAAAAIACgHIABgBIgBgEIgEgGIgBgBIgEgBIgGgJIAAgCIACgCIAAgBIABAAIAKADIADABIAAABIACABIANACIACABIAGACQAFACgCAEIgBACIAAACIgCABIgDACIACAGIACAGIAAACIACAMIARAEIgYA5IgDgBgAhZCzIgBgCIAOAEIACAAIAKADQgYgCgBgDgAhaCxgADICIIgSgFIgTgDIgFAAIAPgJIAQgNIARgSIAKADIAgAKIAKADQgRAYgZASgAgXCFIgBAAIgCgBIgBgBIgBAAIA6gDIgBAAIAAABIgGAEIgVADgAjcBsIgBgBIgBgBIgDgCIgHgJIgNgLIAEgFIAQgPQAOgPAJgPIADgIIAAAAIAGgGIgCgCIgCgJIACgEIAFAAIAKAMQAFAGAYAUIABABIACABIABAAIAEADIACAEQAHAGgCAEIgLAAIgBAAIAAAAQgRACgPALIgFADIgIAEIgKAMIgBADIgIAJIgHACgAjUBqgAjMBhIgHAIIgBABgAjMBhgAhWBWIgBgEIAGAJgAhXBSgAD4AiIgEgEIgBAAIgBgCQgBgEAEgEQAEgDAFAAIADgBIABAAIAAgBIABAAIAHgFIAHgJIALgMQAGgCAAAHIgBAEIgBADIABABIABABIgDAZIgGAAIgBAAIgKACIgDAAIgBAAIgDAAIgGADIgDABgAEiADIAAABIAAgKIADAZQAAAFgDADIgDABgAESAAIAGgHIAEgEIgLAMgAkjgMIgBgBIAAgDIAAAAIABgDIADgDIADgBIAEgBIAGgDIAOgOIAIgHIAHgOIAKgPIAAgBIACgIQAGgFADAHIABAEIACATIALAYQAGAPAAAHIgLgVQgIgRgBgQIAAgPIAAAPQABAQAIARIALAVIAAAAIgBACQgFAEgFgGIgEgEIgRgDIgWAAIgGAEIgUAKQgEgBgCgDgAjNgPgAjohjIgBgKQgCgIgFgHIgJgGIgCgEIABgCIAGgCQAAgEAHgHIATgLIAKgIIAHgBIAFgGIAAgBIAHgCIAOgEIBJgFIgcAKIgQgCIgbAIIgJAGIgCABIgBABIAAABIAAABIgBABIAAAAIgBABIAAAAIgBAAIABgBIgBABIAAAAIgCABIgGAHIgBABIgBABIgBAAIgBACIgBAAIgBABIgCACIgBABIgJAMIgEAJIgCAHIgDAPIAAACIgFABgAjEivIAHgDgAi+ieIAAABIgBABIgBABIAAAAIgEAEgAi+ieIACgBIgBABg");
	this.shape_13.setTransform(-5.2,-8.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#4E7B40").s().p("ABZCgIAAAAgAAkCeIgHAAIAAgIIAEgNQADgIAIgFIACgCIAEgDQAMgIAPgCIADAAIAJgBQALACALAGIgIAJIgBAAQgMAOgBAVgABmB9IABAAIAIgJIAEgDIAFgDIABgBIAKgGIgIgBIgEgCQgNgFgDgLIgCgKIgKAJIgEABIgBABIgMAEIgCACIgCAAIgRADIgBAAIgJACIgVAAIgFAAIgCAAIgBAAIgCgBIgBAAIgBAAIAAAAQgKgDgGgNIgBgBIAAgBIgCgHIADgJIAAgCIABgBIACgCIAEgFIABAAIABABIAVABIAHAAIAOAAIAIAAIAdgBIAIgBIAJgBIAPgBIgDAJQgDAJgHAHQAHgHADgJIADgJIABAAIADgBIAIgBIAkgGIAPgDIAMgEIAAAAIAUgHQAJAIAHAFIAVALIgRASIgQAOIgPAJIggABIgLABIgDABIgUAHIgBABIABgBIAUgHIADgBIALgBIAggBIAFgBIATADIASAGIAQAKIgOAJIgeAQIgTAGIgkAKIgdAFIgdADIgKABQABgVAMgOgAhxBuIgwgYIgIgGIgBgBQgEgHANgQIAMgKIAAgBIAZgNIAIgDIAggDIABAAIABABQASAEAOAPQAMAOAEAPIAAAAIABAGQAAAIgCAGQAAAOgIAMIgMALIgCABQgJAAgvgXgAj7gpIAGgEIAUgKIAHgBIAVAAIANADQAPAEAJASQAFAKgEAMIAAAAIgDAIQgJAOgOAOIgQAPIgEAFQglgpgJgvgAj8gyIAAAAIAAgDIAAAEIABAGgAj/hGIAHgSQgHgOAhg1IADgBIAAgBQADgDAEADIABgBIAAAAIACAAIABAAIAAAAQAGAAABAJQAFAFABAKIAAABIgBABQACANgNAOIgIAKQgDAHgEADIgEADIgRAQIgKABIABAMgAjQieIAAAAIgBAAIgCAAIAAAAIgBABQADgEAFAEQADACAAAGQgBgJgGAAg");
	this.shape_14.setTransform(-9.2,-5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#D9C867").s().p("AgmCNIgHAAIgVgBIgBgBIgBAAIgLgCIgDAAIgDAAIgCgBIgKgDIgCAAIgDgBIgDgCIgKgCIgBAAIgDgBIgNgGIgDgBIgEgCIgKgEIgZgPIgEgEIgBAAIgBgBIgDgDIgDgCIgJgIIgIgIIgZgdIgFgHIgBAAIgCgDIAAgBQAAgGgGgPIgLgWIgCgTIgBgEIABgIIACgJIAFgVIAOgUIAFgHIABgBIABgCIAEgDIAAABIgBABIgCABIAFgDIADgFIABAAIAAgBIABgBIAAAAIAAgBIABgBIACgBIAJgHIAbgHQAFAEgHADQgtAigIAZQgGASAAAOIABAIIAEATIAGALQAJARANANIAXAXIADADIADACIAZATIAVAOQAIAEASAFIAUAEIADAAIAEABIABAAIABAAIAdADIgdgDIgBAAIgBAAIgEgBIgDAAIgUgEQgSgFgIgEIgVgOIgZgTIgDgCIgDgDIgXgXQgNgNgJgRIgGgLIAagRIAIgEQARgJASgDIAYgFIAMgBIAbgBIAJAAIAJABIAAgBIgEgMIgCgDIgshPIAsBPIACADIAEAMIAAABIgJgBIgJAAIgbABIgMABIgYAFQgSADgRAJIgIAEIgaARIgEgTIgBgIQAAgOAGgSQAIgZAtgiIASgGIAcgKIBcAGIAEgBIALgDIANgCIAGgBIAcgCIAlAFIAgAIIAEABIAiAMIAHACIAaANIADABIAcASIABABIARAPIAJAJIADAEIADADIADADIAEAFIgQgFIgYgEIgKgCIgXgBIgNABIgFgBIAGAKIAIAWIAHAcIAAAFIADAjIAAAHIgCAZIACgZIAAgHIgDgjIAAgFIgHgcIgIgWIgGgKIAFABIANgBIAXABIAKACIAYAEIAQAFIAKATIADAQIABAFIgBAFIgCAVQgJAPgGADIgYAQIgIAEIgRAJIgPAGIgBABIABgBIAPgGIARgJIAIgEIAYgQQAGgDAJgPIgBACIAAACIgBABIgBAEIACAAIAAAAIABgBIAKAAIABAAIADgBIgEAFIgEADIgGAJIgBACIgBAAIgHAIIgDACIgDAEIgBAAIAAAAIgBAAIgDABQgFABgEADQgEAEABADIgBABIgJAGIgIAFIgKAFIggAOIgNAGIgUAGIAAABIgMADIgPAEIgkAGIgIAAIgDABIgBAAIgPACIgJAAIgIABIgbABIgIABgAguB0IACgBIADAAIADAAIAZAAIAHAAIAAAAIAfgCIADgBIAAAAIARgCIAHgBIACgUIAAgbIAAgDIgBgHQAAgSgEgTIgGgfIgBgCIgNgfIAcgHIAIgBIAdgBIAJAAIAFABIAFAAIAaAEIABAAIgGgQIgCgDIgSgeQgKgPgOgKQAOAKAKAPIASAeIACADIAGAQIgBAAIgagEIgFAAIgFgBIgJAAIgdABIgIABIgcAHIgBgBIAAAAQgDgNgIgOQgIgRgKgPQgKgPgPgLQAPALAKAPQAKAPAIARQAIAOADANIAAAAIgggDIgmACQgRABgSAIIgEABQAIAQAEAOIAGALIgGgLQgEgOgIgQIAEgBQASgIARgBIAmgCIAgADIABABIANAfIABACIAGAfQAEATAAASIABAHIAAADIAAAbIgCAUIgHABIgRACIAAAAIgDABIgfACIAAAAIgHAAIgZAAIgDAAIgDAAIgCABIABgCIAAgDIgCgMQgBgugMgrIAAgEIgBgBIgBgGIgBABIACAFIABABIAAAEIAIBBIABATIgBAFIAFAAIACAMIAAADIgBACgAhQBvIACAAIAAAAgACEBZIgiAJIgMADIgWAFIgMADIAMgDIAWgFIAMgDIAigJIAfgJgAhSgqIABABIgBgBIgBgBgACNg0IgBgBgAjpgDgAhTgrg");
	this.shape_15.setTransform(-2.1,-13.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#20994E").s().p("AgRC4QALgJgBgLQACAGgCAGIgKAJIgJAFgAjIB5IgEAAIACgDIAFgBIAEAEgAiyB1IADAAIABAAIADAAIARABIAJABIgKAAIABgBIgBABIgTAAIgKABgAilApIABgHIAAALIgDARgAgGAAIAAAAIABAAgAAcgLIAFgDIgPgHIgIgFIAPAEIALACIAJABIgIAEIgEABIAEgBIgHAEgADIg0QgBgQgEgQIgFgPIAGAKIACAFQAHARAAAPIgEAUIgBAFIgEAAQAEgMAAgNgAhKi9IAIAAQgHABgGAFg");
	this.shape_16.setTransform(39,-17.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#39A925").s().p("AAPDFIgBAAIghgFIgagFIgKgDIgggKIgKgDIgVgMQgHgEgJgIIANgGIAggOIAKgFIAIgFIAFgBIAEAAIAHAAIAGAAIADAAIAKgBIATAAIAKAAIAHAAIAlADIAjAEIAhAIQARAGAGARIABAHQABALgLAJIgJAGIgQAHIgHACIgiAEgAlGCDIABgFIgBgTIgIhBQAMArABAugAgeBDIAAgHIABgCIADgRIAAgLIgBgFIgDgQIgKgRIgEgFQAdgfANgXQALgXAVgKIAYgNIgJgVQgGgQAEgRIADgJIALgLQAGgFAHgCIADAAIARgCIAPAAIAhACIAMAAIAJAAIACABIAKgBIAgAAQARABAQAGQAPAEAQAMIAaAYIAWAZIACADIABABIAKAPIAFAPQAEAQABAQQAAANgEAMIgCAIQgGAQgUAPQgOAKgOAHIgfAOIghAJIgiAFIgkAFIgkACIgSAAIgIgBIgIAAIgkgBIghACIgDABIAAAAIgGACIgEAAIgHACIgDABIgBAAIgKAAIgBABgACCgCIABAAIgBgBgACmgQIACABIAHgEIALgCIgLACIAIgEIAIABIgFABIAFgBIgIgBIgJgCIgLgBIgPgEIgDgBQgIgDgHgEQgKgEgHgGQgPgKgNgOIgMgOIgEgFIgDgFIgFgGIgFgJIgCgCIACACIAFAJIAFAGIgOAVQgBAUALAIIAVAPIASAKIAPAEIAdACIAUgCIAGAAgADLhZQgIAEAAAFQAAAEAHAEIARACQAKAAAHgEQAIgEAAgFQABgEgIgDIgRgDQgKAAgHAEgAC6iOQgJACgGAEQgHAFAAAEQABAFAHABQAGACAJgCQAJgDAGgFQAGgEAAgEIgHgGgAlRAgIABgDIABAIgAiQhSIgigMIgEgBQgEgXAIgPIAWgbIAEgFIAagTQAQgKAUgDQATgDAQAHQAQAFAGAPQAEAOgJAPQgJAPgRAKIgiASIgBACIgfAPQgFABgCADg");
	this.shape_17.setTransform(25.2,-16.9);

	this.addChild(this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-40.6,-36.9,100.3,48);


(lib.shape20 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#484848").ss(1,1,1,3,true).p("AGOhJQCDgHghCbIvmAAQgDhLCUhJg");
	this.shape.setTransform(50.3,-7.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCCCCC").s().p("An2BLQgDhLCUhJILzAAQCDgHghCbg");
	this.shape_1.setTransform(50.3,-7.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-15,100.7,15.1);


(lib.shape18 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("rgba(0,0,0,0.102)").ss(2,1,1,3,true).p("AAKAAIBuAAAgsAAIgtAAIgeAAAAKAAIg2AA");
	this.shape.setTransform(9,100);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#544125").ss(1,1,1,3,true).p("AgEnzIA2AAIAAPnAgxH0IAAvnIAtAA");
	this.shape_1.setTransform(5,50);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#997644").s().p("AgVHzIAAvmIArAAIAAPmg");
	this.shape_2.setTransform(2.3,50);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#B39253").s().p("AgaHzIAAvmIA1AAIAAPmg");
	this.shape_3.setTransform(7.3,50);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.9,0,24,100);


(lib.shape16 = function() {
	this.initialize();

	// Layer 3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#81302E").s().p("Ao1BQQjpghgBgvQABguDpgiQDrghFKAAQFLAADrAhQDpAiABAuQgBAvjpAhQjrAilLAAQlKAAjrgig");

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#DFDECE").s().p("A2FDJQpJhTAAh2QAAh1JJhVQJKhTM7AAQM8AAJJBTQJLBVgBB1QABB2pLBTQpJBVs8AAQs7AApKhVg");

	// Layer 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,0,0,0.251)").s().p("A2FDKQpJhUAAh2QAAh1JJhUQJKhUM7AAQM8AAJJBUQJLBUgBB1QABB2pLBUQpJBUs8AAQs7AApKhUg");
	this.shape_2.setTransform(0,3);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-199.9,-28.6,400,60.3);


(lib.shape14 = function() {
	this.initialize();

	// Layer 6
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#436600").s().p("Ak7GmQgLgVAAgVIAAgDIgTACQgoAAgTghQgVAXgeAAQgrAAgTglQgJgRgCgQQgZgDgPgQQgPAJgTAAIgHAAQAHAPAAASQAAAVgQAYQgWAggkAAQgrAAgTglIgBgDIgBAAQgrAAgTglQgLgUgBgSQgMAFgOAAQgVAAgQgJQgTATgbAAQgiAAgSgXIgBABQgXAggiAAQgrAAgUglQgLgVAAgVIACgVQglgDgSgjQgKgTgCgVQAAgoAXgUQAMgKAOgEIgJgOQgMgVAAgUIAAgCIgJABQgeAAgSgQQgVAaggAAQgrAAgUgkQgLgWAAgTIAAgCQgigDgRgeQgSAOgXAAQgrAAgTgmQgMgWAAgTQAAgoAXgVIAKgHQgTgKgLgVQgMgWAAgTQAAgoAXgVQAMgLAPgEQgEgNAAgLQAAggAPgUMAsIAAAIgBABQAUADAPAPQASASAEAcQAYAEATASQAXAWAAAiQAAAVgQAYQgWAhgkAAIgXgDIgEAIIAEADQAXAXAAApQAAAUgRAZIAAABQAGAEAGAGQAXAXAAApQAAAVgQAYQgVAfgkAAQgrAAgTgkIgFgLQgQAJgSAAIgUgCIABAMQAAAVgQAYQgUAdghACQAFAPAAASQAAAUgQAZQgOAUgSAHQACAJAAAJQAAAVgQAYQgWAggkAAQgrAAgTglQgJgRgCgQIgBAAQgqAAgUgmQgIgPgCgRIgGAAIgQgBQgEAOgKAPQgUAdgfADQADALAAAMQAAAUgQAZQgLARgPAIQAFANAAARQAAAVgQAYQgWAggkAAQgqAAgUglIgJgaIgVADQgqAAgUglIgHgSIgSgIQgUAXgfAAQgqAAgUglQgLgWAAgUQAAgRAFgPQgUgDgOgNQgVAbghAAIgMAAQgEANgJAPQgWAggkAAQgcAAgSgQQAAAVgRAXQgSAcgdAEIAAADQAAAVgRAYQgVAggkAAQgrAAgTglQgJgRgCgQIgBAAQgbAAgSgRQgVAbghAAQgpAAgUgiIgCACQgKAQgOAIQANAUAAAfQAAAegVAXQgWAYgjAAQguAAgVglgAkhD7IABgEIgGgBgAL1B8IACABIgBgEgAwZBMIACABIgBgBg");
	this.shape.setTransform(-467.3,-11.9);

	// Layer 5
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#4D7100").s().p("AlWGmQgMgVAAgVIAAgDIgUACQgsAAgVghQgWAXghAAQgvAAgVglQgKgRgCgQQgagDgRgQQgRAJgUAAIgHAAQAHAPAAASQAAAVgSAYQgXAggnAAQgvAAgVglIgBgDIgBAAQgvAAgVglQgLgUgBgSQgNAFgQAAQgXAAgQgJQgWATgdAAQgkAAgVgXIgBABQgYAggmAAQguAAgVglQgNgVAAgVIADgVQgpgDgTgjQgLgTgCgVQAAgoAZgUQAMgKAQgEIgKgOQgNgVAAgUIAAgCIgKABQggAAgTgQQgYAagjAAQguAAgVgkQgNgWAAgTIAAgCQglgDgSgeQgTAOgaAAQguAAgVgmQgNgWAAgTQAAgoAZgVIAKgHQgUgKgMgVQgNgWAAgTQAAgoAZgVQANgLARgEIgFgYQAAggARgUMAv7AAAIAAABQAWADAQAPQATASAFAcQAaAEAUASQAZAWAAAiQAAAVgSAYQgXAhgnAAIgagDIgEAIIAFADQAZAXAAApQAAAUgSAZIgBABIAOAKQAZAXAAApQAAAVgSAYQgXAfgnAAQgvAAgVgkIgFgLQgRAJgUAAIgVgCIABAMQAAAVgSAYQgWAdgjACQAFAPAAASQAAAUgSAZQgOAUgUAHQACAJAAAJQAAAVgSAYQgXAggnAAQgvAAgVglQgJgRgDgQIAAAAQguAAgWgmQgJgPgCgRIgGAAIgSgBQgEAOgLAPQgWAdghADQADALAAAMQAAAUgSAZQgMARgQAIQAGANAAARQAAAVgSAYQgXAggnAAQgvAAgVglIgKgaIgWADQgvAAgVglIgIgSIgTgIQgWAXghAAQgvAAgVglQgMgWAAgUQAAgRAGgPQgXgDgPgNQgWAbgkAAIgNAAQgEANgLAPQgXAggnAAQgfAAgTgQQgBAVgRAXQgVAcgfAEIAAADQAAAVgSAYQgXAggnAAQgvAAgVglQgJgRgDgQIAAAAQgeAAgTgRQgXAbgkAAQgtAAgVgiIgCACQgMAQgPAIQAPAUAAAfQAAAegXAXQgZAYglAAQgzAAgWglgAk6D7IABgEIgGgBgAM2B8IACABIAAgEgAxzBMIABABIAAgBg");
	this.shape_1.setTransform(-467.3,6);

	// Layer 4
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#735231").s().p("AlIUmQCbhvARlEQARlFhUmUQg0j6hNjfIgahLIgHgSQgfhUgkhRQinl6juifIgBgBICqhPIAhAlQEuFRCsGEIAAABIgEgCQgcgMgZgFQg4gLgnAWIACAGIAXA7IAbBLQBMDfBfFnQBgFoAJFZQAFFZhBAdgADCNEQgRlvBUm5QAiiqAoidQAfh6AkhwIATg7IgHgFQgZgTgvgBIhPAGQCSm1EbkOIAbgZIBCAZIBLAcQjACDiVGBQgiBYgfBfIgMAmQgkBwgfB6QgpCdggCqQhVG5ARFvQASFtCKCCIg0AJQh+iGgSlegAADnBIgFhWQgkmsh9lyIgGgQICMgMIALAZQBoEMAvH7IAHBIQgRgSgaAHQgNADgPAJIgLAIQgZARgdAfg");
	this.shape_2.setTransform(-464.9,104.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#805B37").s().p("AhtPdQBDgdgHlZQgIlZhglmQhglphMjfIgbhLIgWg7IgCgGQAngWA3ALQAZAFAcAMIAFACQAYA3AXA5QA+CiAqCqQARBJAOBKQAIh2ADhzQACh+gDh4IgGhxQAdgfAXgRIAMgIQAPgJANgDQAZgHARASIACATIAKCMIABALIAHCGIAZiGIAch4QAVhRAZhLIAEgQIBQgGQAvABAZATIAHAFIgTA7QglBwgfB6QgoCdghCsQhVG3ASFvQARFeB/CGQkMAshlAAQgVAAgOgCg");
	this.shape_3.setTransform(-460.6,141.9);

	// Layer 3
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#3C5B00").s().p("ADXGzQgYgXAAgeQAAgfAPgUQgPgIgMgQIgCgCQgWAiguAAQglAAgYgbQgUARgfAAIAAAAQgDAQgKARQgVAlgwAAQgoAAgZggQgSgYAAgVIAAgDQgggEgVgcQgSgXgBgVQgUAQgfAAQgpAAgYggIgPgcIgNAAQglAAgXgbQgQANgXADQAGAPAAARQAAAUgNAWQgVAlgwAAQgiAAgXgXIgUAIIgIASQgWAlgwAAIgXgDQgDANgIANQgVAlgwAAQgoAAgZggQgSgYAAgVQAAgRAHgNQgRgIgNgRQgSgZAAgUIADgXQgigDgWgdQgMgPgEgOIgSABIgHAAQgCARgKAPQgWAmgvAAIgBAAQgCAQgKARQgWAlgwAAQgoAAgYggQgSgYAAgVIABgSQgUgHgPgUQgSgZAAgUQAAgSAGgPQglgCgXgdQgSgYAAgVIABgMIgVACQgWAAgRgJIgFALQgWAkgwAAQgoAAgYgfQgSgYAAgVQAAgpAagXIANgKIAAgBQgTgZAAgUQAAgpAagXIAFgDIgEgIIgbADQgoAAgYghQgSgYAAgVQAAgiAagWQAUgSAbgEQAFgcAUgSQAQgPAXgDIgBgBMAxbAAAQARAUAAAgQAAALgFANQARAEAOALQAZAVAAAoQAAATgMAWQgNAVgVAKIAKAHQAaAVAAAoQAAATgNAWQgVAmgwAAQgbAAgTgOQgTAegmADIAAACQAAATgNAWQgWAkgwAAQgkAAgYgaQgUAQghAAIgLgBIAAACQAAAUgNAVIgKAOQAQAEAMAKQAaAUAAAoQgBAVgMATQgUAjgpADQACAKAAALQAAAVgNAVQgVAlgwAAQgoAAgYggIgBgBQgVAXgmAAQgeAAgWgTQgRAJgYAAQgQAAgNgFQgBASgMAUQgWAlgwAAIgBAAIgBADQgWAlgwAAQgoAAgYggQgSgYAAgVQAAgSAHgPIgHAAQgVAAgRgJQgSAQgbADQgCAQgLARQgVAlgwAAQgiAAgXgXQgWAhgtAAIgVgCIAAADQAAAVgMAVQgXAlg0AAQgnAAgZgYgAFED3IABAEIAFgFgAtRB9IACgBIgBgDgASWBNIACgBIgBAAg");
	this.shape_4.setTransform(-464.4,34);

	// Layer 2
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(0,0,0,0.051)").s().p("AnqAxQjMgUAAgdQAAgcDMgUQDMgVEeAAIHrAVQDMAUAAAcQAAAdjMAUInrAVg");
	this.shape_5.setTransform(-466.9,237);

	// Layer 1
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#70542C").ss(1,1,1).p("Eh9/gAHQHjhlDlg2QDkg2CdgFIAVgIQBpglCUAAQCAAABfAcQBFgiBgAAQA+AAAzAOQA4gSBGAAQBFAAA2ARQA3gRBEAAQA6AAAwAMIAmgQQBpgkCUAAQCUAABpAkIABABIANAAQA/gaBTAAQBTAAA+AZIAQAAQBdgZB8AAQCMAABlAgQB6gSCZAAQDYAACYAkQAwAMAhANQA6gVBKAAQA1AAAtALQA+gYBQAAQA1AAAuAKQCDgaCqAAQDeAACdAtIAQAFQBFgjBgAAQBFAAA4ARIAbgHQCZgkDXAAQCZAAB5ASQA9gYBQAAQA6AAAwAMQBfgaB/AAQBuAABWAUQA2gRBEAAQBXAABBAcIABAAQBFgjBiAAQBjAABHAkIAGADIAFAAQBogjCTAAQCSAABoAkIAPAGIDJgKQDYAACYAlIALADQAugMA3AAQBUAABAAaIAhgKQCdgtDdAAQDTAACZApQBEghBdAAQBRAAA+AYIAJAAIAPgJQBHglBjAAQBBAAA1AQQA2gRBDAAQBDAAA2AQQBlggCMAAQCNAABmAhIANAAQBOgQBgAAQCCAABgAdQBBgdBYAAQBjAABHAlIAPAJIAQgJQBGglBjAAQBGAAA3ASQA7gVBMAAQBIAAA5ATQCIgaC0AAQCxAACHAZIAlgBQBNgPBeAAQBlAABQARIA6ACICKgKQByAABZAWQA5gTBIAAQBHAAA4ASIARgBQBmgiCPAAQBuAABWAUQBBgcBXAAQBQAAA+AYQAsgKA0AAQBdAABEAgIAMgBIADgBQBpgkCUAAQBuAABWAUIAYAAQDRAACXAoIAAIt");
	this.shape_6.setTransform(-280.4,249.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.lf(["#866535","#AC8142"],[0,1],42.7,-26.8,42.7,26.7).s().p("Eh96gAbQHjhlDlg2QDkg2CdgFIAVgIQBpglCUAAQB/AABgAcQBFgiBfAAQA/AAAzAOQA4gSBGAAQBEAAA3ARQA2gRBEAAQA6AAAxAMIAmgQQBpgkCUAAQCUAABoAkIACABIANAAQA/gaBTAAQBSAAA/AZIAPAAQBegZB7AAQCMAABmAgQB6gSCZAAQDYAACYAkQAvAMAhANQA7gVBKAAQA1AAAtALQA+gYBQAAQA1AAAuAKQCDgaCqAAQDeAACcAtIAQAFQBGgjBgAAQBFAAA3ARIAcgHQCYgkDXAAQCZAAB6ASQA9gYBQAAQA5AAAwAMQBfgaCAAAQBuAABWAUQA2gRBDAAQBYAABBAcIAAAAQBGgjBiAAQBjAABGAkIAGADIAGAAQBogjCRAAQCTAABpAkIAOAGIDKgKQDYAACYAlIALADQAugMA3AAQBUAAA/AaIAigKQCcgtDeAAQDTAACZApQBDghBeAAQBRAAA+AYIAIAAIAQgJQBGglBkAAQBBAAA1AQQA2gRBDAAQBDAAA2AQQBlggCMAAQCNAABmAhIAMAAQBPgQBgAAQCBAABhAdQBBgdBXAAQBkAABGAlIAQAJIAQgJQBGglBjAAQBFAAA4ASQA7gVBMAAQBIAAA5ATQCIgaC0AAQCxAACHAZIAlgBQBMgPBfAAQBlAABQARIA5ACICLgKQByAABYAWQA6gTBIAAQBGAAA5ASIAQgBQBngiCPAAQBuAABVAUQBCgcBWAAQBRAAA+AYQAsgKA0AAQBdAABEAgIAMgBIACgBQBpgkCUAAQBvAABVAUIAZAAQDRAACXAoIAAItMj8JAAog");
	this.shape_7.setTransform(-280.9,251.2);

	this.addChild(this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1087.8,-57.9,1613.9,343);


(lib.shape13 = function() {
	this.initialize();

	// Layer 12
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.149)").s().p("AjPCzIgZgQQg2AihLAAQhRAAg4gnQg6gnAAg3QAAg3A6gkQAdgUAjgKIgCgOQAAgjAwgaQAwgYBDAAQA+AAAuAWQASgXAegSQBLguBoAAQBpAABLAuQBLAuAABCIgBAJIAngCQBUAAA6AjQA8AiAAAzQAAAzg8AkQg6AkhUAAQhUAAg6gjQgRAOgXANQhPArhuAAQhwAAhPgrg");
	this.shape.setTransform(-639.7,27.8);

	// Layer 11
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0.149)").s().p("AkSCrQgbgMgTgNIgJAGQgrAcg+gBQg9ABgsgcQgqgbAAgnQAAgnAqgcQAsgZA9AAIAEAAQgJgSAAgWQAAg5BKgqQBJgpBoAAQBlAABIAnQAOgLAQgJQBVgtB5AAQB4AABVAtQBVAtAABAQAAARgGAPIAUAKQA5AdAAAtQAAArg5AgQg5AghRAAQhRAAg5ggIgGgDQgXAWgrATQhdAqiDAAQiFAAhegqg");
	this.shape_1.setTransform(-506.8,1.6);

	// Layer 10
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.102)").s().p("AMtFjIgYgPQg2AhhMAAQhRAAg4gmQg6gnAAg3QAAgSAHgRQAMAhAnAaQA4AmBRAAQBMAAA2ghIAYAPQBQArBvAAQBwAABPgrQAYgNAQgOQA7AjBTAAQBUAAA7gkQAlgWAOgdQAIAQAAATQAAAzg7AjQg7AkhUAAQhTAAg7gjQgQAOgYANQhPArhwAAQhvAAhQgrgEAgcABVIgugZIgJAGQgrAbg9AAQg+AAgrgbQgsgbAAgnQABgRAJgQQALARAXAOQArAZA+AAQA9AAArgZIAJgGIAuAXQBeAqCFAAQCFAABegqQAqgRAXgWIAHADQA4AdBRAAQBRAAA5gdQAigSAOgWQAJAQABATQAAAqg6AfQg5AfhRAAQhRAAg4gfIgHgDQgXAWgqATQheAqiFAAQiFAAhegqgAktAWIgTgOQgbAKgjAAQg5AAgogbQgogdAAgqQAAgTAJgQQAKAUAVAQQAoAdA5AAQAjAAAbgKIATAOQBFAuBfAAQBHAAA3gYQArATA+AAQBGAAAzgaQAXgMANgOQANAQAAATQAAAigxAZQgzAahGAAQg+AAgrgTQg3AYhHAAQhfAAhFgugEglKgA3QhbAhh8AAQiNAAhjgsQhlgrABg+QAAgSAJgRQAUAoBHAeQBjAsCNAAQB8AABbghQBvAqCNAAQDBAACJhPIAlgYQA4ARBFAAQBxAABSgxQA7glAQgxQAFARAAASQAABHhQAyQhSAxhxAAQhFAAg4gRIglAYQiJBPjBAAQiNAAhvgqgAd9iiIACgEIABAEgEgqLgGNIADAOIgGABg");
	this.shape_2.setTransform(-111.8,10.2);

	// Layer 9
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,255,255,0.149)").s().p("AjmD8QhbAgh8ABQiNAAhkgsQhkgrAAg/QAAg9BkgsQA9gaBNgJQgHgXAAgaQAAhjBhhGQBhhFCJAAQB2AABZA0IAlgBQDBAACJBOQAjAVAaAXQAvgMA1AAQBzAABQAzQBRAxAABFQAABGhRAyQhQAyhzAAQhEAAg4gSIglAZQiJBOjBAAQiLAAhvgpg");
	this.shape_3.setTransform(-326.6,-20.6);

	// Layer 8
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(255,255,255,0.149)").s().p("AitB+IgTgPQgbALgjAAQg5AAgogeQgogcAAgqQAAgnAogeQAogdA5AAIAzAHIAegaQBFguBfAAIASAAQAsgeA7AAQBFAAAwApQAwApAAA6QAAAPgDAOQAmAEAfAQQAxAZAAAlQAAAjgxAaQgzAahGAAQg+AAgtgUQg3AZhFAAQhfAAhFgug");
	this.shape_4.setTransform(-124.6,-0.1);

	// Layer 7
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(255,255,255,0.149)").s().p("AjPCzIgYgQQg3AihLAAQhRAAg5gnQg5gnAAg3QAAg3A5gkQAdgUAkgKIgCgOQAAgjAwgaQAwgYBCAAQA/AAAuAWQASgXAfgSQBKguBoAAQBpAABMAuQBKAuAABCIgBAJIAmgCQBUAAA7AjQA8AiAAAzQAAAzg8AkQg7AkhUAAQhSAAg8gjIgnAbQhPArhuAAQhvAAhQgrg");
	this.shape_5.setTransform(-9.6,27.8);

	// Layer 6
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("rgba(255,255,255,0.149)").s().p("AkSCrQgbgMgTgNIgJAGQgrAcg9gBQg+ABgsgcQgqgbgBgnQABgnAqgcQAsgZA+AAIADAAQgJgSAAgWQAAg5BJgqQBKgpBoAAQBlAABIAnIAegUQBVgtB5AAQB4AABVAtQBVAtAABAQAAARgGAPIAUAKQA5AdABAtQgBArg5AgQg5AghRAAQhRAAg4ggIgHgDQgXAWgqATQhfAqiCAAQiFAAhegqg");
	this.shape_6.setTransform(123.3,1.6);

	// Layer 5
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(255,255,255,0.102)").s().p("AMtFjIgYgPQg2AhhMAAQhRAAg4gmQg6gnAAg3QAAgSAHgRQAMAhAnAaQA4AmBRAAQBMAAA2ghIAYAPQBQArBvAAQBwAABPgrQAYgNAQgOQA7AjBTAAQBUAAA7gkQAlgWAOgdQAIAQAAATQAAAzg7AjQg7AkhUAAQhTAAg7gjQgQAOgYANQhPArhwAAQhvAAhQgrgEAgcABVQgbgMgTgNIgJAGQgrAbg9AAQg+AAgrgbQgsgbAAgnQABgRAJgQQALARAXAOQArAZA+AAQA9AAArgZIAJgGQATALAbAMQBeAqCFAAQCFAABegqQAqgRAXgWIAHADQA4AdBRAAQBRAAA5gdQAigSAOgWQAJAQABATQAAAqg6AfQg5AfhRAAQhRAAg4gfIgHgDQgXAWgqATQheAqiFAAQiFAAhegqgAktAWIgTgOQgbAKgjAAQg5AAgogbQgogdAAgqQAAgTAJgQQAKAUAVAQQAoAdA5AAQAjAAAbgKIATAOQBFAuBfAAQBHAAA3gYQArATA+AAQBGAAAzgaQAXgMANgOQANAQAAATQAAAigxAZQgzAahGAAQg+AAgrgTQg3AYhHAAQhfAAhFgugEglKgA3QhbAhh8AAQiNAAhjgsQhlgrABg+QAAgSAJgRQAUAoBHAeQBjAsCNAAQB8AABbghQBvAqCNAAQDBAACJhPIAlgYQA4ARBFAAQBxAABSgxQA7glAQgxQAFARAAASQAABHhQAyQhSAxhxAAQhFAAg4gRIglAYQiJBPjBAAQiNAAhvgqgAd9iiIACgEIABAEgEgqLgGNIADAOIgGABg");
	this.shape_7.setTransform(500.6,10.2);

	// Layer 4
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(255,255,255,0.149)").s().p("AjmD8QhbAgh8ABQiNAAhkgsQhkgrAAg/QAAg9BkgsQA9gaBNgJQgHgXAAgaQAAhjBhhGQBhhFCJAAQB2AABZA0IAlgBQDBAACJBOQAjAVAaAXQAvgMA1AAQBzAABQAzQBRAxAABFQAABGhRAyQhQAyhzAAQhEAAg4gSIglAZQiJBOjBAAQiLAAhvgpg");
	this.shape_8.setTransform(285.8,-20.6);

	// Layer 3
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(255,255,255,0.149)").s().p("AitB+IgTgPQgbALgjAAQg5AAgogeQgogcAAgqQAAgnAogeQAogdA5AAIAzAHIAegaQBFguBfAAIASAAQAsgeA7AAQBFAAAwApQAwApAAA6IgDAdQAmAEAfAQQAxAZAAAlQAAAjgxAaQgzAahGAAQg+AAgtgUQg3AZhFAAQhfAAhFgug");
	this.shape_9.setTransform(487.8,-0.1);

	// Layer 2
	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(255,255,255,0.149)").s().p("AjPCzQgNgHgLgJQg3AihLAAQhRAAg5gnQg5gnAAg3QAAg3A5gkQAdgUAkgKIgCgOQAAgjAwgaQAvgYBDAAQA/AAAuAWQASgXAfgSQBKguBoAAQBpAABMAuQBKAuAABCIAAAJIAlgCQBUAAA7AjQA8AiAAAzQAAAzg8AkQg7AkhUAAQhSAAg8gjIgnAbQhPArhuAAQhvAAhQgrg");
	this.shape_10.setTransform(602.8,27.8);

	// Layer 1
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("rgba(255,255,255,0.149)").s().p("AkSCrIgugZIgJAGQgrAcg9gBQg+ABgsgcQgrgbAAgnQAAgnArgcQAsgZA+AAIADAAQgJgSAAgWQAAg5BJgqQBKgpBoAAQBlAABIAnIAegUQBVgtB5AAQB4AABVAtQBVAtAABAQAAARgGAPIAUAKQA5AdABAtQgBArg5AgQg5AghRAAQhRAAg4ggIgHgDQgXAWgqATQhfAqiCAAQiFAAhegqg");
	this.shape_11.setTransform(735.8,1.6);

	this.addChild(this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-695.5,-50,1489.6,100.1);


(lib.shape11 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(30,60,0,0.2)").s().p("Eh3EADLIAAgGQAAgpAoADIAQADIAQgNQgMgSAAgJQAAgVAPgLQAPgKAUACIAPADIAAgCQAAgpAQgcQAPgXAVgDQAPgBALAKQA/hfAWALQAaAMAVArQgJgrANgrIARgJIAOAHQALAIAHAMQAWAjASAmQgDgMADgOQAFghAcgHIARgBQAgAOAMAnQgDgLABgNQACgbAOgWQATgeAbARQAoAZATAwIgOg1QgFgYAUgPQAeATALAqQgEgwAagoIANgBQAxAKAbAyQgXgvgFg2QAAgIADgGQAJgWAYAHIBHBkQgHglAggXQAjARATApQgRgqAogXQAGgEAFACQAoALATAqQgMgjAigVIAOgHQAIADAEAHQAQAYABAhQAPgbAVgWQAYgaAegGQAIACAGAEQAGAEABAJQAEAWgIAYIAHAAQAbgZAlAHIADAQIAXAAQgMgfAIgjQAJgoAjADQAcAVgEAkQAKgbAGghQADgSAMgJIAMgDQAlgCAMAgQAFgYANgUQAFgKAIgHQAggeAeAYQAkA3gNBMQANgxAkghIADAGQAJAngDApQAcg3AygYQAGAFACAGQAUAsgEA3QACgOAKgJQAggfAmgOQAaAlgYAnQAlgYAmAJQALAWgMAYIAYgKQAvgPAXAqQAFggAagSQAKgHALgCQA6gNAnAwQgIgrAdglIAPgGQAsAPAcAnQgFgRAKgRQAQgYAdgBIAaADQAjANAGAqQADgSANgMQAzgzA3AfQAGAEAEAGIALARIAIgLQAmgmAtASQAQAGACASQACAUAAAVQAWg3A7gJQAGADAEAGQAZAhAJAsQAJgSANgOQAJgLAMgCIALgBQAiAUAGAuIALhmIADgJQARgdAbALIANAKQAkAsAJA+QAEgpAdgTQAcAYAFApQACAKADgGIADgGIBIgpQAaAeAJAqQAbguAtgWQAMAGAKAIQAWAWADAlQAIggAXgYQAVgXAbAAIAkBCQADg1AagrIAVgCQAzAaAUA9IAMhEQADgLAIgCQAzAUAWA3QgQgxAagsIAXABQAJACAGAHQAZAdANAqQgHgYAJgXQAHgXAVgHIAQACQAgASANAnQgLgpAVgnIAcACQAVAIAIAYQAPAoAaAaIAGhHQADgUATAAQAJAAAGAEQAtAZAWA1QgJgYABgYQACglAhgBIBHA2QACgxAqgJQAjAYATAqIARgsQAJgXAXAGQAJADAIAFQAeAUAOAoQAQg7A1gTIAPgBQA1AHAOA6QgFgwAmgaQAIgEAGAHQAjArAKA8QACgYAKgVIASgrQAQgmAigCQAqAiAGA+QAGgrAigYQAGACAEAFQAcAkgIA5QAWg+Ajg0QAKgQASgCIAKAIQAlBBABBQQABgsAdggQAlAZABA3QAWg5AygeQAIADAFAEQAIAHADAKQAKAfAFAhQAEgzAqgdQANAAAKAFQAuAYAIA+QABgjANgfQAUgrAogEQAwAwAQBJQACguAogWIAYgBQAoATAVArQgJgrANgrIARgJIAOAHQALAIAHAMQAWAjARAmQgDgMADgOQAGghAbgHIARgBQAgAOAMAnQgDgLABgNQACgbAOgWQAUgeAaARQAoAZATAwIgOg1QgEgYAUgPQAdATALAqQgDgwAagoIANgBQAxAKAbAyQgXgvgFg2QgBgIADgGQAKgWAXAHIBIBkQgIglAggXQAjARAUApQgRgqAngXIALgCQApALATAqQgMgjAhgVIAOgHQAJADAEAHQAQAYAAAhQAPgbAVgWQAZgaAegGQAHACAGAEQAGAEACAJQAEAegPAfQAfgqAvAJQAIAogLAnQBDhyA0AcQAcAVgEAkQAKgbAGghQADgSAMgJIAMgDQAlgCAMAgQAFgYANgUIANgRQAggeAeAYQAkA3gNBMQANgxAkghIADAGQAJAngDApQAcg3AygYQAGAFACAGQAUAsgEA3QACgOAKgJQAggfAmgOQAaAlgYAnQAlgYAmAJQALAWgMAYIAYgKQAvgPAXAqQAFggAagSQAKgHALgCQA6gNAnAwQgIgrAdglIAPgGQAsAPAcAnQgFgRAKgRQAQgYAdgBIAaADQAjANAGAqQADgSANgMQAzgzA1AfQAGAEAEAGIALARIAIgLQAmgmAtASQAQAGACASQACAUAAAVQAWg3A7gJIAKAJQAZAhAJAsQAJgSANgOQAJgLAMgCIALgBQAiAUAGAuIALhmIADgJQARgdAbALIANAKQAkAsAJA+QAEgpAdgTQAcAYAFApQACAKADgGIADgGIBIgpQAaAeAJAqQAbguAtgWIAWAOQAWAWADAlQAIggAXgYQAVgXAbAAIAkBCQADg1AagrIAVgCQAzAaAUA9IAMhEQADgLAIgCQAzAUAWA3QgQgxAagsIAXABQAJACAGAHQAZAdANAqQgHgYAJgXQAHgXAVgHIAQACQAgASANAnQgLgpAVgnIAcACQAVAIAIAYQAPAoAaAaIAGhHQADgUATAAQAJAAAGAEQAtAZAWA1QgJgYABgYQACglAhgBIBHA2QACgxAqgJQAjAYATAqIARgsQAJgXAXAGQAJADAIAFQAeAUAOAoQAQg7A1gTIAPgBQA1AHAOA6QgFgwAmgaQAIgEAGAHQAjArAKA8QACgYAKgVIASgrQAQgmAigCQAqAiAGA+QAGgrAigYQAGACAEAFQAcAkgIA5QAWg+Ajg0QAKgQASgCQAGACAEAGQAlBBABBQQABgsAdggQAlAZABA3QAWg5AygeIANAHQAIAHADAKQAKAfAFAhQAEgzAqgdQANAAAKAFQAuAYAIA+QABgjANgfQAUgrAogEQAwAwAQBJQACguAogWIAYgBQAoATAVArQgJgrANgrIARgJIAOAHQALAIAHAMQAWAjARAmQgDgMADgOQAGghAbgHIARgBQAgAOAMAnQgDgLABgNQACgbAOgWQAUgeAaARQAoAZATAwQgIgagGgbQgEgYAUgPQAdATALAqQgDgwAagoIANgBQAxAKAbAyQgXgvgFg2QgBgIADgGQAKgWAXAHIBIBkQgIglAggXQAjARAUApQgRgqAngXIALgCQApALATAqQgMgjAhgVIAOgHQAJADAEAHQAQAYAAAhQAPgbAVgWQAZgaAegGQAHACAGAEQAGAEACAJQAEAegPAfQAVgcAbgFIACgKQAJgoAjADQAcAVgEAkQAKgbAGghQADgSAMgJQAGgDAGAAQAlgCAMAgQAFgYANgUQAFgKAIgHQAggeAeAYQAkA3gNBMQANgxAkghIADAGQAJAngDApQAcg3AygYIAIALQAUAsgEA3QACgOAKgJQAggfAmgOQAaAlgYAnQAlgYAmAJQALAWgMAYIAYgKQAvgPAXAqQAFggAagSQAKgHALgCQA6gNAnAwQgIgrAdglIAPgGQAsAPAcAnQgFgRAKgRQAQgYAdgBIAaADQAjANAGAqQADgSANgMQAzgzA3AfIAKAKIALARQADgHAFgEQAmgmAtASQAQAGACASIACApQAWg3A7gJQAGADAEAGQAZAhAJAsQAJgSANgOQAJgLAMgCIALgBQAiAUAGAuIALhmQAAgFADgEQARgdAbALIANAKQAkAsAJA+QAEgpAdgTQAcAYAFApQACAKADgGIADgGIBIgpQAaAeAJAqQAbguAtgWQAMAGAKAIQAWAWADAlQAIggAXgYQAVgXAbAAIAkBCQADg1AagrIAVgCQAzAaAUA9QAFgjAHghQADgLAIgCQAzAUAWA3QgQgxAagsIAXABIAPAJQAZAdANAqQgHgYAJgXQAHgXAVgHIAQACQAgASANAnQgLgpAVgnIAcACQAVAIAIAYQAPAoAaAaQACgkAEgjQADgUATAAQAJAAAGAEQAtAZAWA1QgJgYABgYQACglAhgBIBHA2QACgxAqgJQAjAYATAqQAIgXAJgVQAJgXAXAGQAJADAIAFQAeAUAOAoQAQg7A1gTIAPgBQA1AHAOA6QgFgwAmgaQAIgEAGAHQAjArAKA8QACgYAKgVIASgrQAQgmAigCQAqAiAGA+QAGgrAigYQAGACAEAFQAcAkgIA5QAWg+Ajg0QAKgQASgCIAKAIQAlBBABBQQABgsAdggQAlAZABA3QAWg5AygeQAIADAFAEQAIAHADAKQAKAfAFAhQAEgzAqgdQANAAAKAFQAuAYAIA+QABgjANgfQAUgrAogEQAwAwAQBJQACguAogWIAYgBIAAGqUhooABkhomgByI+wAAIohDJQDOhsB9hYg");
	this.shape.setTransform(-274.1,212.2);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#4D7100").s().p("Eh4JAEWIgBgDQgGgKgBgLQAAghAggKIAygDIgCgaQAAgkAZgUQAUgQAhgBIAZACIgDgZQAAg6AsgVIgJgQQABgqAUgDQARgDAYAUIgBgKQgBgLALgSQAMgSAOgIQANgJAKAEQAqg+APAJIA2AkQgJgsANgrIARgJIAOAHQALAIAHAMQAWAjARAnQgCgNACgOQAGghAcgGIARgBQAgAOALAnQgDgLABgOQACgbAOgWQAUgdAaAQQAoAaAUAwIgPg1QgEgZAUgOQAeATAKAqQgDgwAagpIANgBQAxAKAbAyQgXgugFg3QAAgHADgHQAJgWAYAHIBHBlQgIglAggXQAjAQAUAqQgRgqAogYQAGgDAEABQApAMATApQgMgiAhgWIAPgHQAIADAEAHQAQAYABAhQAOgaAWgXQAYgZAegGQAIABAFAFQAHAEABAIQADAXgHAYIAHgBQAbgZAlAHIADARIAWgBQgLgeAHgjQAJgpAkAEQAbAVgDAkQAKgcAGggQADgTAMgIIALgEQAmgBAMAfQAFgXANgUQAFgKAHgIQAhgeAdAZQAlA3gNBLQANgwAjgiIAEAHQAJAngDApQAcg3AygYQAGAEACAGQAUAsgFA4QADgOAKgJQAggfAmgOQAaAkgYAoQAlgZAlAKQAMAWgNAXIAZgKQAvgPAXAqQAEggAbgRQAKgHALgDQA6gNAmAwQgIgrAegkIAPgHQAsAPAcAoQgFgSAKgRQAPgXAegCIAZADQAkAOAFAqQAEgSANgNQAzgyA3AfQAFAEAFAFIALARIAIgLQAlglAuARQAPAHADASQABAUAAAVQAXg3A6gKQAHAEAEAFQAZAhAJAsQAIgSAOgOQAJgLAMgCIALAAQAiATAGAuIALhmIACgJQASgdAbAMIAMAKQAlAsAIA9QAFgpAcgTQAcAYAGAqQACAKACgGIAEgGIBIgpQAaAdAJArQAbgvAtgWQAMAGAKAJQAVAWAEAkQAIggAXgYQAVgXAbABIAkBBQADg0AagsIAUgBQA0AZAUA+IAMhFQACgKAJgDQAzAVAWA2QgQgwAagtIAXABQAJADAGAGQAZAeANAqQgHgYAIgXQAHgYAWgGIAQABQAfATAOAmQgLgpAVgnIAcADQAVAIAIAYQAOAnAaAbIAHhIQADgUATAAQAJABAGAEQAtAZAWA0QgJgYABgYQACglAhgBIBHA3QACgxApgKQAjAZAUAqIAQgtQAKgWAXAGQAJACAIAGQAeAUAOAoQAQg8A0gSIAQgCQA1AHAOA7QgFgwAmgaQAIgFAGAIQAjArAKA7QACgXAKgWIASgqQAQgnAhgCQArAiAGA+QAGgqAhgYQAHABADAFQAdAlgIA4QAWg9Ajg1QAKgPASgCIAKAHQAlBBAABQQACgrAdghQAlAaABA2QAWg5AygeQAIADAEAFQAJAGADAKQAKAfAFAiQAEgzAqgeQAMABALAFQAtAYAJA9QAAgiAOgfQATgsApgDQAvAwAQBIQACguApgWIAYAAQAoATAUArQgIgsANgrIARgJIANAHQAMAIAGAMQAXAjARAnQgDgNADgOQAGghAbgGIARgBQAgAOAMAnQgDgLABgOQACgbAOgWQAUgdAaAQQAoAaATAwIgOg1QgEgZATgOQAeATALAqQgDgwAZgpIAOgBQAxAKAaAyQgWgugGg3QAAgHADgHQAKgWAXAHIBHBlQgHglAggXQAjAQAUAqQgRgqAngYIALgCQApAMASApQgLgiAhgWIAOgHQAIADAFAHQAQAYAAAhQAPgaAVgXQAZgZAdgGQAIABAGAFQAGAEACAIQAEAegPAgQAfgrAuAJQAJApgLAnQBDhyAzAcQAcAVgDAkQAKgcAGggQADgTAMgIIAMgEQAlgBAMAfQAFgXAMgUIANgSQAhgeAdAZQAlA3gNBLQANgwAjgiIAEAHQAJAngDApQAcg3AygYQAFAEADAGQAUAsgEA4QACgOAJgJQAhgfAmgOQAaAkgYAoQAlgZAlAKQAMAWgNAXIAZgKQAvgPAXAqQAFggAZgRQALgHALgDQA6gNAmAwQgHgrAdgkIAPgHQAsAPAcAoQgFgSAKgRQAPgXAegCIAaADQAjAOAFAqQAEgSAMgNQAygyA3AfQAGAEAEAFIALARIAHgLQAmglAuARQAQAHACASQABAUAAAVQAXg3A6gKIALAJQAZAhAJAsQAJgSANgOQAIgLANgCIALAAQAhATAHAuIAKhmIADgJQASgdAbAMIANAKQAjAsAKA9QADgpAdgTQAcAYAGAqQACAKADgGIADgGIBIgpQAZAdAKArQAbgvAtgWIAWAPQAVAWAEAkQAIggAXgYQAVgXAbABIAkBBQADg0AagsIAUgBQA0AZAUA+IAMhFQADgKAIgDQAzAVAWA2QgQgwAagtIAXABQAJADAGAGQAZAeANAqQgHgYAJgXQAGgYAWgGIAQABQAfATAOAmQgLgpAVgnIAcADQAVAIAIAYQAPAnAaAbIAGhIQADgUATAAQAIABAHAEQAtAZAWA0QgJgYABgYQACglAhgBIBHA3QACgxAqgKQAjAZATAqIAQgtQAKgWAWAGQAKACAIAGQAeAUAOAoQAQg8A0gSIAPgCQA1AHAPA7QgFgwAmgaQAHgFAHAIQAjArAKA7QACgXAJgWIASgqQARgnAigCQAqAiAFA+QAGgqAigYQAGABAFAFQAcAlgIA4QAWg9Ajg1QAKgPASgCQAGACAEAFQAlBBABBQQABgrAdghQAkAaABA2QAXg5AygeIANAIQAHAGAEAKQAKAfAFAiQAEgzAqgeQAMABAKAFQAvAYAHA9QABgiAOgfQAUgsAogDQAvAwAQBIQADguAngWIAZAAQAnATAWArQgKgsAOgrIARgJIANAHQAMAIAGAMQAXAjARAnQgDgNADgOQAGghAbgGIARgBQAgAOAMAnQgDgLABgOQACgbAOgWQATgdAbAQQAoAaATAwQgJgagFgbQgFgZAVgOQAdATALAqQgEgwAbgpIAMgBQAyAKAbAyQgXgugGg3QAAgHADgHQAJgWAYAHIBHBlQgHglAggXQAjAQATAqQgQgqAngYIALgCQAoAMATApQgLgiAhgWIAOgHQAIADAFAHQAPAYABAhQAPgaAVgXQAYgZAfgGQAHABAGAFQAGAEABAIQAFAegPAgQAUgcAcgGIABgJQAKgpAiAEQAcAVgDAkQAKgcAGggQADgTAMgIQAGgEAGAAQAlgBAMAfQAFgXAMgUQAFgKAJgIQAfgeAeAZQAlA3gOBLQAOgwAjgiIAEAHQAJAngDApQAcg3AygYIAIAKQATAsgDA4QACgOAJgJQAhgfAmgOQAaAkgYAoQAlgZAlAKQAMAWgNAXIAZgKQAvgPAXAqQAFggAZgRQALgHALgDQA6gNAmAwQgHgrAdgkIAPgHQAsAPAcAoQgFgSAKgRQAQgXAdgCIAaADQAjAOAFAqQAEgSAMgNQAzgyA4AfIAKAJIALARQADgGAEgFQAnglAtARQAQAHACASIACApQAWg3A7gKQAGAEAEAFQAZAhAJAsQAJgSANgOQAJgLAMgCIALAAQAhATAHAuIAKhmQAAgFADgEQASgdAbAMIANAKQAjAsAKA9QADgpAdgTQAdAYAFAqQACAKADgGIADgGIBHgpQAaAdAKArQAbgvAtgWQAMAGAKAJQAVAWAEAkQAIggAXgYQAVgXAbABIAkBBQADg0AagsIAUgBQA0AZAUA+QAFgjAHgiQACgKAJgDQAyAVAXA2QgQgwAagtIAXABIAPAJQAZAeANAqQgHgYAJgXQAGgYAWgGIAQABQAgATANAmQgLgpAVgnIAcADQAVAIAIAYQAPAnAaAbQACgkAEgkQADgUATAAQAJABAGAEQAtAZAWA0QgJgYABgYQACglAhgBIBHA3QACgxAqgKQAiAZAUAqQAIgXAJgWQAJgWAWAGQAKACAIAGQAeAUAOAoQAQg8A1gSIAOgCQA1AHAPA7QgFgwAmgaQAHgFAHAIQAjArAKA7QACgXAJgWIASgqQARgnAigCQAqAiAFA+QAHgqAigYQAFABAFAFQAcAlgIA4QAVg9Akg1QAKgPASgCIAKAHQAlBBABBQQABgrAdghQAkAaABA2QAXg5AygeQAHADAGAFQAHAGAEAKQAKAfAFAiQAEgzAqgeQAMABAKAFQAvAYAHA9QABgiAOgfQAUgsAogDQAvAwARBIQABguAogWIAZAAIAKAFIAAKQMjwIAAAIpvCIQC1hyB9hjg");
	this.shape_1.setTransform(-277.5,206.4);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1077.1,157.3,1599.2,98.4);


(lib.shape9 = function() {
	this.initialize();

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#77C9FF","#E6F8FF"],[0,1],-2.1,-99.8,-7.2,165.9).s().p("EgocATHMAAAgmNMBQ5AAAMAAAAmNg");
	this.shape.setTransform(247.8,122.4);

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#70542C").ss(1,1,1).p("EAnEAHcMhOHAAAIAAu3MBOHAAAg");
	this.shape_1.setTransform(250,292.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.lf(["#866535","#AC8142"],[0,1],0,-68.8,0,-10.8).s().p("EgnDAHcIAAu3MBOHAAAIAAO3g");
	this.shape_2.setTransform(250,292.5);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-11.1,0,518,340.1);


(lib.shape8 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.051)").s().p("AimARQgmgJAAgEQAAgYA3gQQBZgaDVATQAAADAbAJQAZAJAAAYIgiAgIg6AHIhxALg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-20.4,-5.1,41,10.5);


(lib.shape6 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhpBiQgZgZAAgjQAAgXALgQQgIgRAAgTQAAgkAZgZQAZgYAjAAQAfAAAVATIAVgCQApAAAeAdQAdAeAAApQAAAogdAdQgeAdgpAAIgMAAIgGAFQgWAZgkAAQgjAAgZgZg");
	this.shape.setTransform(0.5,-0.1);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-12.5,-12.5,26.3,24.8);


(lib.sprite49 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape50("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,500,336);


(lib.sprite43 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape44("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,38.5,36.6);


(lib.sprite40 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape41("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,38.5,36.6);


(lib.sprite39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{point:1,loss:8});
  var self = this;
	// timeline functions:
	this.frame_0 = function(){this.stop()}
	this.frame_1 = function() {
		playSound("sound42");
	}
	this.frame_7 = function(){
   this.stop ();
   if (!this.parent.gameWin)
   {
     this.parent.parent.gotoAndPlay("reset");
   }
   else
   {
     //this.parent.parent.GameEndClip.gotoAndPlay("GameWonPlayground");
     this.parent.parent.GameWon = true;
   } // end else if	
	}
	
	this.frame_8 = function() {
		playSound("sound46");
    var damp = 7.000000E-001;
    for (var i = 1; i <= 20; i++)
    {
    this["puff" + i] = new lib.sprite5Puff(); //attachMovie("Puff", "puff" + i, i);
    this["puff" + i].rotation = Math.random() * 360;
    this["puff" + i].scaleX = this["puff" + i].scaleY = (Math.random() * 40 + 80)/100;
    this["puff" + i].velX = Math.random() * 40 - 20;
    this["puff" + i].velY = Math.random() * 40 - 20;
    this["puff" + i].step = Math.random() * 10 + 10;
    this["puff" + i].on("tick", function (evt)
    {
        evt.currentTarget.velX = evt.currentTarget.velX * damp;
        evt.currentTarget.velY = evt.currentTarget.velY * damp;
        evt.currentTarget.x = evt.currentTarget.x + evt.currentTarget.velX;
        evt.currentTarget.y = evt.currentTarget.y + evt.currentTarget.velY;
        evt.currentTarget.scaleX = evt.currentTarget.scaleY = evt.currentTarget.scaleY - evt.currentTarget.step;
        if (evt.currentTarget.scaleX <= 0)
        {
            self.removeChild(evt.currentTarget);
            evt.remove();
            delete evt.currentTarget
        } // end if
    });
    } // end of for		
	}
  this.frame_14 = function(){
    this.parent.gotoAndStop(this.parent.currentFrame - 1);  
    this.parent.lose();  
  }
	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(6).call(this.frame_7).wait(1).call(this.frame_8).wait(6).call(this.frame_14));

	// Layer 3
	this.instance = new lib.sprite40();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).wait(1).to({scaleX:1.19,scaleY:1.19},0).wait(1).to({scaleX:1.25,scaleY:1.25},0).wait(1).to({scaleX:1.21,scaleY:1.21},0).to({scaleX:1.13,scaleY:1.13},1).wait(1).to({scaleX:1.05,scaleY:1.05},0).wait(1).to({scaleX:1,scaleY:1},0).wait(8));

	// Layer 2
	this.instance_1 = new lib.sprite43();
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).wait(1).to({scaleX:1.19,scaleY:1.19,alpha:0.75},0).wait(1).to({scaleX:1.25,scaleY:1.25,alpha:1},0).wait(1).to({scaleX:1.21,scaleY:1.21},0).wait(1).to({scaleX:1.13,scaleY:1.13},0).to({scaleX:1.07,scaleY:1.07},1).wait(1).to({scaleX:1,scaleY:1},0).to({_off:true},1).wait(7));

	// Layer 1
	this.instance_2 = new lib.shape45("synched",0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(3).to({startPosition:0,_off:false},0).to({_off:true},5).wait(7));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,38.5,36.6);


(lib.sprite38 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});
  this.frame1 = function(){
   this.score = function ()
   {
     this.gotoAndStop(this.currentFrame + 1); 
     this["star" + this.currentFrame].gotoAndPlay("point");
   } // End of the function
   this.lose = function ()
   {
    if (this.currentFrame > 0)
    {
        this["star" + this.currentFrame].gotoAndPlay("loss");
    } // end if
   } // End of the function
   this.stop ();
   this.gameWin = false;  
  }
  this.frame4 = function(){
   this.gameWin = true
  }
  
	// Layer 3
	this.star3 = new lib.sprite39();
	this.star3.setTransform(74.4,-3.2,0.823,0.823);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.star3}]}).wait(4));

	// Layer 2
	this.star2 = new lib.sprite39();
	this.star2.setTransform(35.5,-3.2,0.823,0.823);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.star2}]}).wait(4));

	// Layer 1
	this.star1 = new lib.sprite39();
	this.star1.setTransform(-3.3,-3.2,0.823,0.823);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.star1}]}).wait(4));
  this.timeline.addTween(cjs.Tween.get(this).call(this.frame1).wait(3).call(this.frame4))
}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-19.2,-18.2,109.5,30.1);


(lib.sprite36 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape37("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10.4,-29,35.2,58.3);


(lib.sprite35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sprite36();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:8},4).wait(1).to({x:10},0).to({x:2.5},3).wait(1).to({x:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10.4,-29,35.2,58.3);


(lib.sprite33 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape34("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-8.9,-16,18,18.1);


(lib.sprite26 = function() {
	this.initialize();

	// Layer 2
	this.instance = new lib.text28("synched",0);
	this.instance.setTransform(-32,-14.7);

	// Layer 1
	this.instance_1 = new lib.shape27("synched",0);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-42.5,-35.9,85.2,71.9);


(lib.sprite25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop=false,{});

	// Layer 1
	this.instance = new lib.sprite26();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:0.043},21).wait(1).to({alpha:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-42.5,-35.9,85.2,71.9);


(lib.sprite22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});
  this.frame1 = function(){this.stop()}
	// Layer 3
	this.instance = new lib.shape23("synched",0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(1));

	// Layer 2
	this.instance_1 = new lib.sprite25();
	this.instance_1.setTransform(67.6,-60,1,1,45);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1).to({_off:false},0).wait(1));

	// Layer 1
	this.instance_2 = new lib.shape24("synched",0);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1).to({startPosition:0,_off:false},0).wait(1));
  this.timeline.addTween(cjs.Tween.get(this).call(this.frame1).wait(2))
}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-40.6,-36.9,100.3,48);


(lib.sprite19 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape20("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,-15,100.7,15.1);


(lib.sprite17 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape18("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.9,0,24,100);


(lib.sprite15 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape16("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-199.9,-28.6,400,60.3);


(lib.sprite12 = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape13("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-695.5,-50,1489.6,100.1);


(lib.sprite10 = function() {
	this.initialize();
  var self = this;
	// Layer 13
	this.scrollHint = new lib.sprite35();
	this.scrollHint.setTransform(55.8,170);
  this.scrollHint.cursor = "pointer";
	// Layer 12
	this.pointer = new lib.sprite33();
	this.pointer.setTransform(163.4,339,0.997,1);

	// Layer 11
	this.scoreClip = new lib.sprite30();
	this.scoreClip.setTransform(258.6,382.8);

	// Layer 10
	this.side1 = new lib.sprite19();
	this.side1.setTransform(180,322);

	// Layer 9
	this.turtle = new lib.sprite22();
	this.turtle.setTransform(267.4,184.6);
  this.turtle.cursor = "pointer";
	// Layer 8
	this.stilt1 = new lib.sprite17();
	this.stilt1.setTransform(271,229);

  //Layer 7
  this.middle = new cjs.Shape(); 
  
	// Layer 6
	this.side2 = new lib.sprite19();
	this.side2.setTransform(165,287);

	// Layer 5
	this.stilt2 = new lib.sprite17();
	this.stilt2.setTransform(256,226);

	// Layer 4
	this.target = new lib.sprite15();
	this.target.setTransform(-249.9,302.9);

	// Layer 3
	this.instance = new lib.shape14("synched",0);

	// Layer 2
	this.instance_1 = new lib.sprite12();
	this.instance_1.setTransform(-277.2,64.7);
	this.instance_1.alpha = 0.801;

	// Layer 1
	this.instance_2 = new lib.shape11("synched",0);

  this.muds = new cjs.Container();
	this.addChild(this.instance_2,this.instance_1,this.instance,this.target,this.stilt2,this.side2,this.middle,this.stilt1,this.turtle,this.side1,this.scoreClip,this.pointer,this.scrollHint, this.muds);
	
  function scrollWindow()
  {
    if (stage.mouseX/ratio >= 100)
    {
        if (stage.mouseX/ratio > 400)
        {
            scrollSpeed = (400 - stage.mouseX/ratio) / 2;
            if (self.x + scrollSpeed <= 0)
            {
                self.x = 0;
            }
            else
            {
                self.x = self.x + scrollSpeed;
            } // end if
        } // end else if
    }
    else
    {
        scrollSpeed = (100 - stage.mouseX/ratio) / 2;
        self.scrollHint.visible = false;
        if (self.x + scrollSpeed >= 1000)
        {
            self.x = 1000;
        }
        else
        {
            self.x = self.x + scrollSpeed;
        } // end else if
    } // end else if
   } // End of the function
   function adjustSlide()
   {
    delX = stage.mouseX/ratio - self.x - baseX;
    delY = stage.mouseY/ratio - self.y - baseY;
    dist = Math.sqrt(delX * delX + delY * delY);
    radians = Math.atan(delY / delX);
    if (delX < 0)
    {
        radians = radians + 3.141593E+000;
    } // end if
    if (!(radians < -1.047198E+000 || radians > 1.570796E+000))
    {
        if (radians > -2.617994E-001)
        {
            radians = -2.617994E-001;
        } // end if
    }
    else
    {
        radians = -1.047198E+000;
    } // end else if
    positionTurtle();
    drawSlide();
    self.x = self.x - self.x / 4;
   } // End of the function
   function positionTurtle()
   {
    self.side1.rotation = self.side2.rotation = self.turtle.rotation = 180 * radians / 3.141593E+000;
    self.side1.scaleX = self.side2.scaleX = dist/100;
    self.turtle.x = baseX + dist * Math.cos(radians);
    self.turtle.y = baseY + dist * Math.sin(radians);
   } // End of the function
   function drawSlide()
   {
    self.middle.graphics.clear();
    self.middle.graphics.beginStroke("rgba(0, 0, 0, 0)").setStrokeStyle(0);
    self.middle.graphics.beginFill("rgba(72, 72, 72, 0.15)"); 
    self.middle.graphics.moveTo(self.side1.x, self.side1.y);
    self.middle.graphics.lineTo(self.side2.x, self.side2.y);
    self.middle.graphics.lineTo(self.side2.x + dist * Math.cos(radians) + topLength, self.side2.y);
    self.middle.graphics.lineTo(self.side1.x + dist * Math.cos(radians) + topLength, self.side1.y);
    self.middle.graphics.endFill();
    self.middle.graphics.beginStroke("rgb(72, 72, 72)").setStrokeStyle(1); 
    self.middle.graphics.beginFill("rgb(170, 170, 170)");
    self.middle.graphics.moveTo(self.side1.x, self.side1.y);
    self.middle.graphics.lineTo(self.side2.x, self.side2.y);
    self.middle.graphics.lineTo(self.side2.x + dist * Math.cos(radians), self.side2.y + dist * Math.sin(radians));
    self.middle.graphics.lineTo(self.side1.x + dist * Math.cos(radians), self.side1.y + dist * Math.sin(radians));
    self.middle.graphics.endFill();
    self.middle.graphics.beginFill("rgb(187, 187, 187)");
    self.middle.graphics.moveTo(self.side2.x + dist * Math.cos(radians), self.side2.y + dist * Math.sin(radians));
    self.middle.graphics.lineTo(self.side1.x + dist * Math.cos(radians), self.side1.y + dist * Math.sin(radians));
    self.middle.graphics.lineTo(self.side1.x + dist * Math.cos(radians) + topLength, self.side1.y + dist * Math.sin(radians));
    self.middle.graphics.lineTo(self.side2.x + dist * Math.cos(radians) + topLength, self.side2.y + dist * Math.sin(radians));
    self.middle.graphics.endFill();
    self.stilt1.x = self.side1.x + dist * Math.cos(radians);
    self.stilt1.y = self.side1.y + dist * Math.sin(radians);
    self.stilt1.height = self.side1.y - self.stilt1.y;
    self.stilt2.x = self.side2.x + dist * Math.cos(radians);
    self.stilt2.y = self.side2.y + dist * Math.sin(radians);
    self.stilt2.height = self.side2.y - self.stilt2.y;
   } // End of the function
   function startSlide(evt)
   {
    radians2 = -1.570796E+000 - radians;
    speed = gravity * Math.cos(radians2);
    accelX = speed * Math.sin(radians2);
    accelY = speed * Math.cos(radians2);
    velX = velX + accelX;
    velY = velY + accelY;
    speed = Math.sqrt(velX * velX + velY * velY);
    self.turtle.x = self.turtle.x + velX;
    self.turtle.y = self.turtle.y + velY;
    if (self.turtle.y >= baseY)
    {
        self.turtle.y = baseY;
        evt.remove();
        self.on("tick", finishSlide);
    } // end if
   } // End of the function
   function finishSlide(evt)
   {
    if (turtleSlide == 1)
    {
        sndSkid.play();
        turtleSlide = 0;
    } // end if
    if (speed > 2)
    {
        ++mudDepth;
        self["mud" + mudDepth] = new lib.sprite7Mud(); //attachMovie("Mud", "mud" + mudDepth, mudDepth);
        self.muds.addChild(self["mud" + mudDepth]);
        self["mud" + mudDepth].x = self.turtle.x;
        self["mud" + mudDepth].y = self.turtle.y + Math.random() * 6 - 3;
    } // end if
    self.turtle.rotation = self.turtle.rotation - self.turtle.rotation / 4;
    if (speed >= 5)
    {
        speed = speed * fastDamp;
    }
    else
    {
        speed = speed * slowDamp;
    } // end else if
    self.turtle.x = self.turtle.x - speed;
    if (speed < 5.000000E-002)
    {
        score = Math.round((200 - Math.abs(self.turtle.x - self.target.x)) / 2);
        if (score >= 0)
        {
            if (score >= 50)
            {
                turtle_yeah.play();
                self.parent.starPoints.score();
            }
            else
            {
                turtle_haha.play();
                self.parent.starPoints.score();
            } // end else if
        }
        else
        {
            turtle_haha.play();
            self.parent.gotoAndPlay("reset");
        } // end else if
        if (score < 0)
        {
            score = 0;
        } // end if
        evt.remove();
    } // end if
    self.pointer.x = self.turtle.x;
    if (self.pointer.alpha < 1)
    {
        self.pointer.alpha = self.pointer.alpha + 0.1;
    } // end if
    if (self.turtle.x < 500 / 4)
    {
        self.x = 500 / 4 - self.turtle.x;
    } // end if
  } // End of the function
  
  var topLength = 10;
  var velX = 0;
  var velY = 0;
  var speed = 0;
  var gravity = 2;
  var friction = 0;
  var fastDamp = 9.700000E-001;
  var slowDamp = 9.000000E-001;
  var radians = -5.235988E-001;
  var dist = 200;
  var baseX = (this.side1.x + this.side2.x) / 2;
  var baseY = (this.side1.y + this.side2.y) / 2;
  var score = 0;
  var turtleDepth = 500000;
  var mudDepth = 100000;
  //turtle.swapDepths(turtleDepth);
  //side1.swapDepths(turtleDepth + 1);
  var scrollSpeed = 0;
  var turtleSlid = 0;
  
  var turtle_whee = playSound("sound2wheewav"); turtle_whee.stop();
  var turtle_haha = playSound("sound4hahawav"); turtle_haha.stop();
  var turtle_yeah = playSound("sound1yeahwav"); turtle_yeah.stop();
  var sndSkid = playSound("sound3skidwav"); sndSkid.stop();
  
  this.init = function(){
    topLength = 10;
    velX = 0;
    velY = 0;
    speed = 0;
    gravity = 2;
    friction = 0;
    fastDamp = 9.700000E-001;
    slowDamp = 9.000000E-001;
    radians = -5.235988E-001;
    dist = 200;
    baseX = (this.side1.x + this.side2.x) / 2;
    baseY = (this.side1.y + this.side2.y) / 2;
    score = 0;
    turtleDepth = 500000;
    mudDepth = 100000;
  //turtle.swapDepths(turtleDepth);
  //side1.swapDepths(turtleDepth + 1);
    scrollSpeed = 0;
    turtleSlid = 0;  
    positionTurtle();
    drawSlide();
    this.x = 0;
    this.pointer.alpha = 0;
    this.scrollHint.visible = true;
    this.scrollHint.alpha = 1;
    this.scrollHint.on("rollover", function ()
    {
     self.on("tick",  scrollWindow);
    });    
    this.turtle.gotoAndStop(0);
    this.muds.removeAllChildren();
  }  

  this.turtle.on("mousedown", function ()
  {
    self.on("tick",  adjustSlide);
    self.scrollHint.removeAllEventListeners("rollover"); //delete scrollHint.onRollOver;
    self.scrollHint.on("tick", function (evt)
    {
        if (evt.currentTarget.alpha <= 0)
        {
            evt.currentTarget.visible = false;
            evt.remove()
        }
        else
        {
            evt.currentTarget.alpha = evt.currentTarget.alpha - 0.1;
        } // end else if
    });
  });
  this.turtle.on("pressup", function ()
  {
    turtleSlide = 1;
    turtle_whee.play();
    self.turtle.gotoAndStop(self.turtle.currentFrame + 1);  
    self.removeAllEventListeners("tick");
    self.on("tick", startSlide);
  });

	
	
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1087.8,-57.9,1613.9,460.2);


(lib.sprite7Mud = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape8("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-20.4,-5.1,41,10.5);


(lib.sprite5Puff = function() {
	this.initialize();

	// Layer 1
	this.instance = new lib.shape6("synched",0);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-12.5,-12.5,26.3,24.8);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;